### ISSUE TITLE
What methods are available on the `RAML` global object?

### ISSUE THREAD

**Issue by baig** [raml-org/raml-js-parser-2#10]

**Comment by KonstantinSviridov** [comment]
`RAML.loadApi(absolute path)` -- load API
`RAML.toJSON()` -- print as JSON any non scalar node of Parser Model

**Comment by sichvoge** [comment]
Can we create a global documentation around what is available and what is it. Some documentation will help anyone who wants to use them to build some tooling.

**Comment by KonstantinSviridov** [comment]
There is no more `RAML` gloabal object since today. Instead, `raml1Parser` module is used. For today it has three functions:
```
export declare function loadApi(apiPath: string, expandTraitsAndResourceTypes?: boolean): Opt<RamlWrapper.Api>;
export declare function loadApiAsync(apiPath: string, expandTraitsAndResourceTypes?: boolean): Promise<RamlWrapper.Api>;
export declare function toJSON(node: parserCore.BasicSuperNode, serializeOptions?: json2lowlevel.SerializeOptions): any;
```

For more information about particular functions or classes check the `/parser-typings` root folder.
