### ISSUE TITLE
Examples with application/xml media type returns example in JSON format 

### ISSUE THREAD

**Issue by Narkhip** [raml-org/raml-js-parser-2#103]
The following RAML file has the media type defined as _application/xml_

``` raml
#%RAML 1.0
title: API with Types
baseUri: /media

types:
  Person:
    type: object
    properties:
      firstname:
        type: string
        description: example description
      lastname: 
        type: string
        required: false
      addresses: string[]
      age: number  

/users:
  get:
    body:
      application/json:
        type: object
        properties:
          developer: string
          test: string
          animal: string
          car: string

    responses:
      200:
        body:
          application/xml:
            type: Person
            properties: 
              juan: string
            example:
              lastname: arkhipenko
              firstname: nicolas
              juan: juan
              addresses:
                - myadress
              age: 123 
```

the example output is displayed in JSON:

```JSON
{
  "lastname": "arkhipenko",
  "firstname": "nicolas",
  "juan": "juan",
  "addresses": [
    "myadress"
  ],
  "age": 123
}
```

**Comment by ddenisenko** [comment]
The type of example output is a string. Example is a property of a type. The type can be used in many places, the inplace type in a method body is one of many cases.

That string is agnostic to where you put that example to, it only depends on example contents itself. Example contents may be one of the following: 
* A string, whether there is XML or JSON inside, does not matter
* YAML

The string you get by calling `example()` method of `TypeDeclaration` class contains the following for the listed cases:
* For a string example it will contain that string
* For YAML example it will contain YAML contents serialized to JSON.

**Comment by juancoen** [comment]
is there any way for the client to convert a YAML example to XML? what are the rules for that conversion?

Thanks!

**Comment by sichvoge** [comment]
I'd say use one of the existing libs that can easily do that. There are no specific rules specified on the spec. On npm I found https://www.npmjs.com/package/data-convert

**Comment by ddenisenko** [comment]
There are no rules, yet. There was a draft for XML conversion to RAML type instances and backwards (as well as type<->xsd), but that is far from being official. So no conversion for now.

**Comment by petrochenko-pavel-a** [comment]
@dreamflyer please handle it next in the line after #136

**Comment by petrochenko-pavel-a** [comment]
@sichvoge @Narkhip  we discussed this issue with @ddenisenko and @dreamflyer  today. It is pretty clear that we should support this functionality in top level API, so we all agreed to add method asXMLString() to `IExpandableExample` interface in type system. @dreamflyer has almost all required functionality already. But there is a conceptual question about how it should look in JSON output. 

As for me we have three possible options for solving this issue:
1)  auto convert example to xml string when type is used in the context of xml related media type
2) add special entry to JSON output in the cases when type is used in the context of xml related media type
3) always add XML representation of example in JSON output.
4) Make this configurable in `SerializeOptions`interface. 

All this options might affect current consumers of the parser so for now we decided to add the special setting `dumpXMLRepresentationOfExamples` to `SerializeOptions` interface which will allow to control dumping xml representation of examples.

Regards,
Pavel

**Comment by dreamflyer** [comment]
4th option from post above is implemented

**Comment by frickua** [comment]
@dreamflyer, how can i use this in mule API Manager, or Anypoint Studion. I need xml format for my examples. Thanks for a reply.

**Comment by ddenisenko** [comment]
@frickua well, this is JS Parser functionality, and I dont think it is exposed at API Manager or Anypoint Studio level.

**Comment by jarrodek** [comment]
According to this document: http://raml-org.github.io/raml-js-parser-2/interfaces/_src_raml1_highlevelast_.serializeoptions.html and this source: https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/highLevelAST.ts#L24
there's no `dumpXMLRepresentationOfExamples` property.
Is it possible to gen XML example when calling `toJSON`?
