### ISSUE TITLE
Unknown facet:format

### ISSUE THREAD

**Issue by nnance** [raml-org/raml-js-parser-2#111]
In the new parser (0.2.0). We have some types defined with a format: int32 and format: int64 and we are getting an error of unknown facet:format.  Example below:

int32:
    description: An integer that can fit into a signed 32-bit type
    type: integer
    format: int32

**Comment by sichvoge** [comment]
duplicate: https://github.com/mulesoft/api-workbench/issues/147 

It is fixed and waiting to be tested. There is another minor release with several bug fixes (including that) today.

**Comment by nnance** [comment]
@sichvoge thanks for the quick response

**Comment by nnance** [comment]
@sichvoge any idea when there will be a release of the api workbench that includes this fix?  Right now the current version of the workbench shows our raml as invalid

**Comment by sichvoge** [comment]
The changes will be visible inside the workbench in our release tomorrow. We are currently incorporating several fixes for the console that is part of this release.
