### ISSUE TITLE
Breaking changes v0.2.2

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#114]
Again there seem to be changes which broke my project build.

```javascript
{ code: 11,
  message: 'property badge range type has error:array is expected',
  path: 'index.raml',
  start: 778,
  end: 787,
  line: 22,
  column: 0,
  range:
   [ { line: 22, column: 0, position: 778 },
     { line: 22, column: 9, position: 787 } ],
  isWarning: false }
```

This error I could trace down to snippets like these:

```yaml
    /thumbnail:
        post:
            description: Sets the thumbnail of the channel.
            is: [ rateLimited: { bucket: upload }, permissible: { permission: "channel:update" } ]
            securedBy: [ cookie ]
            body:
                multipart/form-data:
                    properties:
                        thumbnail:
                            description: The file to upload.
                            type: file
                            fileTypes: image/*
                            maxLength: 8388608
            responses:
                200:
                    body:
                        type: ExpandedChannel
```

Changing `fileTypes` to an array fixed the error, not sure if this is intentional or a regression.

Also proper traces would be appreciate, `divide and conquer` isn't a pleasant debugging strategy 😞

**Comment by SimonSchick** [comment]
The latter seems to be a regression where `filesTypes` MUST be an array, previously a single value worked.

**Comment by sichvoge** [comment]
Seems that the new version did fix a bug; the spec states that the value of `fileTypes` is a list of values (sequence / array).

**Comment by SimonSchick** [comment]
I guess, I looked into the spec and that wasn't really clear to me.

**Comment by sichvoge** [comment]
Do you think we should make that more clear?

**Comment by SimonSchick** [comment]
Probably, the [document](https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md) states it's existence but doesn't have any examples.

**Comment by sichvoge** [comment]
True! Let me think about that and add an issue to the spec repo. Thanks @SimonSchick
