### ISSUE TITLE
RAML.loadApi should be asynchronous

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#12]
Parsing a RAML can be a heavy load operation, so it makes sense to make the operation asynchronous. It's also a good practice to do it using Promises.

**Comment by petrochenko-pavel-a** [comment]
@juancoen yep, we have a request to support it . @KonstantinSviridov  is working on it.

**Comment by juancoen** [comment]
:+1:

**Comment by KonstantinSviridov** [comment]
It's ready
