### ISSUE TITLE
Boolean types have a kind() of TypeDeclaration

### ISSUE THREAD

**Issue by nnance** [raml-org/raml-js-parser-2#125]
Given the following raml.

Food:
    type: object
    properties:
      name: string
      isVegetarian: boolean
      weight: number

when calling kind() on isVegetarian it is reported as "TypeDeclaration" and not BooleanTypeDeclaration.

**Comment by petrochenko-pavel-a** [comment]
Pushed to RC2.

**Comment by nnance** [comment]
@petrochenko-pavel-a not sure why this was closed.  I don't understand your comment.  This is still a bug when testing with release 0.2.6
