### ISSUE TITLE
Examples for number[] with doubles no longer validates

### ISSUE THREAD

**Issue by rocketraman** [raml-org/raml-js-parser-2#134]
In the most recent releases of API workbench (0.8.25 and 0.8.26), the following type no longer validates:

```
   GeoPoint:
    type: number[]
    example: [100.0, 0.0]
```

It shows the validation error: "number is expected" on the `example` line. This was working in 0.8.23. I note that if I change the contents of the array to ints, the error goes away.

I also have a similar error on another type which depends indirectly on this one: "array is expected" even though the value is actually an array. This was also working before.

**Comment by petrochenko-pavel-a** [comment]
Thanks for reporting this,
pushed to RC2 (will be visible in workbench as soon as it will be switched to use RC2 version of the parser)

Regards,
Pavel
