### ISSUE TITLE
Inconsistent behavior between schema/example for RAML 0.8

### ISSUE THREAD

**Issue by xaka** [raml-org/raml-js-parser-2#137]
RAML 0.8 spec doesn't allow `schema` and `example` properties to contain structured values like:

```
example:
  value: 10
```

which has to be re-written as:

```
example: |
  {"value": 10}
```

-

What happens right now with parser is that it enforces RAML 0.8 spec for `schema` property as expected, BUT it doesn't do so for `example` property. I'd expect parser to fail for the following RAML:

```
#%RAML 0.8
title: Test
/:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              value: 10
```

**Comment by petrochenko-pavel-a** [comment]
Thanks for bringing this in. I will fix it ASAP.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
Fixed in RC2.
