### ISSUE TITLE
When loading RAML from URL without path and ending in /, the parser calls the incorrect resolver

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#138]
Loading a RAML from a URL like `http://127.0.0.1:8081/`, the `contentAsync` method in `fsResolver` with argument `/http:/127.0.0.1:8081` instead of calling `getResourceAsync` from `httpResolver`

**Comment by petrochenko-pavel-a** [comment]
Pushed to RC2.
