### ISSUE TITLE
Error messages in multiple examples are a bit off

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#141]
Error position is a bit off as you can see when defining multiple examples. The problem is that the `phone` property needs to be a string, but the error is positioned on the key. Using the parser that would be hard to find.

![image](https://cloud.githubusercontent.com/assets/498114/14909951/fc8e74ca-0de0-11e6-9ff4-b225115700a4.png)

**Comment by petrochenko-pavel-a** [comment]
Fixed this and couple of similar issues with error positioning, pushed to RC2.

Please report more if see something similar.

Regards,
Pavel
