### ISSUE TITLE
Bad wording on error message

### ISSUE THREAD

**Issue by damimj** [raml-org/raml-js-parser-2#144]
When you modify a RAML from 0.8 to 1.0 and you have Traits on it, an error message is marked. If you mouse over on the error shows this message "traits should be map in RAML 1.0". 
Should be "traits should be a map in RAML 1.0"

![image](https://cloud.githubusercontent.com/assets/9253676/14962651/4de8b42e-1076-11e6-9356-1f76b31c3f88.png)

**Comment by petrochenko-pavel-a** [comment]
Pushed to RC2.
