### ISSUE TITLE
Error running `npm run build`

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-js-parser-2#166]
When I'm trying to run `npm run build` I receive following error: 

> src/raml1/highLevelImpl.ts(768,56): error TS2339: Property 'SourceProvider' does not exist on type 'typeof "/Users/pawelpsztyc/workspace/raml-js-parser-2/node_modules/raml-definition-system/dist/de...'.
> src/raml1/highLevelImpl.ts(958,35): error TS2339: Property 'SOURCE_EXTRA' does not exist on type 'typeof "/Users/pawelpsztyc/workspace/raml-js-parser-2/node_modules/raml-definition-system/dist/de...'

Therefore I can't build browser version of the parser.

**Comment by jarrodek** [comment]
After running steps again I get different error:

> ML-PPSZT-OSX-EMEA:raml-js-parser-2 pawelpsztyc$ npm run build

> raml-1-parser@0.2.9 build /Users/pawelpsztyc/workspace/raml-js-parser-2
> npm run compile && npm run generateTopLevel


> raml-1-parser@0.2.9 compile /Users/pawelpsztyc/workspace/raml-js-parser-2
> rimraf dist && tsc


> raml-1-parser@0.2.9 generateTopLevel /Users/pawelpsztyc/workspace/raml-js-parser-2
> node dist/topLevelGenerator/buildParsers.js

> [SyntaxError: Unexpected token *]

**Comment by ddenisenko** [comment]
The first issue is not reproducible for me and for CI.

The last one is harmless, but fixed it.
