### ISSUE TITLE
Overlay fails to parse due to type override

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#177]
When I extend my API with an Overlay, it fails with the errors that I have attached as screenshots.

[My_Alainn_Cosmetics_Mobile_API-v1.0.8.zip](https://github.com/raml-org/raml-js-parser-2/files/263499/My_Alainn_Cosmetics_Mobile_API-v1.0.8.zip)

![image](https://cloud.githubusercontent.com/assets/498114/15251756/c3f3b650-1922-11e6-80d2-8bc76eeb1cf5.png)

![image](https://cloud.githubusercontent.com/assets/498114/15251759/c7c1f896-1922-11e6-887a-9923c6fcc129.png)

**Comment by juancoen** [comment]
A simpler example that shows this issue:

api.raml
```
#%RAML 1.0
title: Test
version: 1.0.0

types:
  item:
    type: object

resourceTypes:
  base:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName>>
              
/item:
  type: base
```

overlay.raml
```
#%RAML 1.0 Overlay

extends: api.raml

/item:
  get:
    description: Test
```

**Comment by petrochenko-pavel-a** [comment]
According to the spec:
```
The behavior-invariance restrictions of an overlay are defined as follows: after applying the merging algorithm and before applying any inheritances of types, resource types, traits, and annotation types, the tree of nodes in the merged document is compared with the tree of nodes in the master RAML document after resolving all !include tags. Any differences in the documents MUST be only in the nodes listed in the following table.
```
the get node does not exists in the original document (before expansion), so it is illegal to overlay it.

**Comment by nialdarbey** [comment]
Master has get defined in base type

**Comment by sichvoge** [comment]
@nialdarbey, thats what the spec says. It is not allowed through the expansion of any traits and resource types. Obviously you use resource types here, there fore Overlays does not know anything about that `get` node.

**Comment by nialdarbey** [comment]
That effectively renders Overlays useless. Should I stop using resource types so I can use Overlays? That won't happen: resource types, traits and types bring a huge degree of brevity to the document that I am not willing to sacrifice. Overlays looked very promising when I first saw them. With this restriction I am forced to ignore them.

**Comment by petrochenko-pavel-a** [comment]
This is something what I does not understand a bit:
1) At first you can use `Extension` instead of `Overlay` and in this case you example will be perfectly valid.

```
#%RAML 1.0 Extension

extends: api.raml

/item:
  get:
    description: Test
```
will work fine and will give you same AST structure.

2) You always can overlay trait definition and in this case description overlaid in the trait should be propagated to the expanded nodes.

Regards,
Pavel.

**Comment by nialdarbey** [comment]
Tried that.
<img width="526" alt="screen shot 2016-05-14 at 6 06 39 am" src="https://cloud.githubusercontent.com/assets/402424/15268621/19651f58-199a-11e6-910e-bc99f5dddf7f.png">

**Comment by petrochenko-pavel-a** [comment]
Give me a sec. (will test and look what happens)

**Comment by nialdarbey** [comment]
Ok, I used the annotations in the master api.raml. 
I have taken that out and I'm left with an error about unknown type.

**Comment by nialdarbey** [comment]
Anyway, it's not appropriate that I use Extensions for this case, as I am not modifying the behaviour. I am simply revisiting different parts of the API to enhance the information that I want to convey to client developers.

**Comment by petrochenko-pavel-a** [comment]
Just tested: annotation works fine for me in API workbench (so probably this issue already fixed in latest parser version), but I also see unknown type issue. Will fix it asap.

**Comment by petrochenko-pavel-a** [comment]
According to Overlays applied before expansion please raise issue on the spec.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
Original examples should path validation now (both for Overlays/Extensions). Will work on PR/ issue for the spec when will have some sleep.

Regards,
Pavel
