### ISSUE TITLE
Array in "example" has only half of elements

### ISSUE THREAD

**Issue by capt4net** [raml-org/raml-js-parser-2#19]
Hi,
After the last update I found out that boolean arrays in "example" part have only halt of elements.
For example, I have the description: 

example:
      aesOutput1:
        [ true, false, false, false ]
      aesOutput2:
        [ false, true, false, false ]

and when I try to output them by toString() I have:

true,false
false,true

Although in the previous version of raml-js-parser-2 I had four elements for each array.

**Comment by sichvoge** [comment]
Thanks for reporting @capt4net. We will investigate that ASAP. Try to have a look at the new documentation in the `documentation`. Feedback is very much appreciated ;)

**Comment by capt4net** [comment]
You are welcome,
I need to generate some sources from my RAML1.0 document, so I need working parser :)

**Comment by sichvoge** [comment]
I understand - hope that will be fixed soon.

**Comment by capt4net** [comment]
OK, Thanks!

**Comment by KonstantinSviridov** [comment]
Thanks for the report. It's ok now.

**Comment by capt4net** [comment]
Sehr gut!
Danke schoen!
