### ISSUE TITLE
schema validation is off

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#192]
The schema validation seems to be not working as expected. Take the following project.

[BrokenSchema 2.zip](https://github.com/raml-org/raml-js-parser-2/files/266517/BrokenSchema.2.zip)

It contains a fully valid schema, but the parser complains.

**Comment by petrochenko-pavel-a** [comment]
Fixed in the type system. It was an issue with an unconditional call to schema auto conversion.

Please note, to test issue you will need fresh type system from a repository. Or next JS parser build

Regards,
Pavel
