### ISSUE TITLE
Multiple parser errors with an RAML 0.8 

### ISSUE THREAD

**Issue by Narkhip** [raml-org/raml-js-parser-2#197]
## Observed Result

See attached Facebook API that contains the multiple 
[facebook.zip](https://github.com/raml-org/raml-js-parser-2/files/267397/facebook.zip)

**Comment by Narkhip** [comment]
[stackExchange.zip](https://github.com/raml-org/raml-js-parser-2/files/267429/stackExchange.zip)

Adding another example

**Comment by sichvoge** [comment]
Can you please add more details to the actual problems.

**Comment by sichvoge** [comment]
OK, raised all the issues with the facebook example as separated issues and referenced them to this one.

**Comment by sichvoge** [comment]
The issues for the stackExchange example are limited to #203 only. Fixing that will fix the example.

**Comment by petrochenko-pavel-a** [comment]
Works fine after closing #203 and #204
