### ISSUE TITLE
Parser validates oauth2 Security Scheme has a missing property

### ISSUE THREAD

**Issue by Narkhip** [raml-org/raml-js-parser-2#199]
## Description

I can't confirm that this was ignored by the old parser (since it's not in production anymore). But the RAML attached that was expected to be working before using the new parser, is failing because the parser is properly saying there is a missing required property in the Security Schema.

If we want to keep 100% backward Compatibility we should review if we have to ignore this validation too.
[squareup.zip](https://github.com/raml-org/raml-js-parser-2/files/267422/squareup.zip)

**Comment by sichvoge** [comment]
I can validate that this behaviour is 100% correct. The property `accessTokenUri` is required in 0.8 and there is a test in the old parser [here](https://github.com/raml-org/raml-js-parser/blob/980ce34036149f703205452552be8a970049cacc/test/specs/validator.js#L282) that confirms the behaviour. 

So the parser is not doing anything wrong. Please check with whom ever you got that example.
