### ISSUE TITLE
Validation message with "Example does not conform to Schema" for RAML 0.8

### ISSUE THREAD

**Issue by Narkhip** [raml-org/raml-js-parser-2#201]
# Description

Attached RAML example has multiple validations messages, but the following is interesting because we removed all the schema validations against examples for RAML 0.8.

[zendesk.zip](https://github.com/raml-org/raml-js-parser-2/files/267465/zendesk.zip)

![image](https://cloud.githubusercontent.com/assets/6545134/15312235/ac1f6ed0-1bd8-11e6-837f-1f4caef0853e.png)

**Comment by sichvoge** [comment]
Does the parser not respond with warnings here? @petrochenko-pavel-a can you confirm.

**Comment by petrochenko-pavel-a** [comment]
hm, for me it highlights with warnings.

**Comment by petrochenko-pavel-a** [comment]
I have just tested it with latest parser from npm (0.2.11)
```
{ code: 11,
    message: 'Example does not conform to schema:Content is not valid according to schema:Expected type object but found type null object,null',
    path: 'api.raml',
    start: 26655,
    end: 26669,
    line: 344,
    column: 4,
    range: [ [Object], [Object] ],
    isWarning: true },
  { code: 11,
    message: 'Example does not conform to schema:Content is not valid according to schema:Expected type object but found type null object,null',
    path: 'api.raml',
    start: 26718,
    end: 26724,
    line: 345,
    column: 4,
    range: [ [Object], [Object] ],
    isWarning: true },

```

So it seems that problem is not on our side.
Regards,
Pavel
