### ISSUE TITLE
fix "Keys should not have spaces" error

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#202]
Some RAML files have keys, eg "auth_dialog_perms_explanation ", that contain white spaces. Thats does not really violate anything. Part of #197

**Comment by sichvoge** [comment]
@petrochenko-pavel-a: seems that https://github.com/raml-org/raml-js-parser-2/issues/191 solves the problem. Can you double check if that is the same for 0.8 and 1.0. If yes, please feel free to close it.

**Comment by petrochenko-pavel-a** [comment]
Works fine both in 1.0 (warnings)
