### ISSUE TITLE
"Resources share same URI" error

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#203]
Using the example in #197, I am getting an error on "Resources share same URI". It seems the old parser did not complain about the fact that you have two resources with the same URI parameter. Another candidate for warnings?

That was fully valid before:

```yaml
/{path}:
/{path1}:
```

**Comment by dmartinezg** [comment]
Technically, they _may_ be different resources, and the validity of the resource should be based on the domain of the parameter. 

Even if the domains overlapped, It is definitely _not_ an error, a warning _may_ be useful but I am not sure that I would expect the parser to barf on anything that _may be_ an error. I would remove the check, and not add a warning.

**Comment by petrochenko-pavel-a** [comment]
Agree, after some thoughts, however overlapped domains have potential issue for server generation, so probably I would reimplement this warnings in optional additional linter rules later.

Regards,
Pavel
