### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-js-parser-2#21]
I would like to be able to use the RAML 1.0 parser as a dependency of my projects, can this be published on NPM?

**Comment by sichvoge** [comment]
+1

**Comment by ddenisenko** [comment]
Of course we will do it.

**Comment by domarmstrong** [comment]
Would be great if you could get this up, it kind of messes up my dev automated deployment at the moment :(

**Comment by sichvoge** [comment]
Agree - we are currently finalising RAML 1.0 with couple of changes that needs to be implemented into the parser. After that we will publish it on NPM.
