### ISSUE TITLE
Change test raml to stick RAML 1.0 definition

### ISSUE THREAD

**Issue by sucotronic** [raml-org/raml-js-parser-2#210]
In the raml test of the project (test/raml-specs/XKCD/api.raml) there are *schema* nodes, but the [RAML 1.0 spec says](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#the-root-of-the-document):

> API definitions should use "types" and "type", as "schemas" and "schema" are deprecated and might be removed in a future RAML version.

I would suggest to change it to *type* to comply with the spec ;)

**Comment by sichvoge** [comment]
Its fully valid to have either schemas or types, or schema or type. The test needs to cover these scenarios as well to avoid any problems.

But you are right in general. It is recommended to use types and type from now on.

**Comment by sucotronic** [comment]
Ok. What about adding in the test .raml some entry with "type" besides the "schema" nodes?

**Comment by sichvoge** [comment]
They are mutual exclusive so you can't have both defined on the same node :)

**Comment by sucotronic** [comment]
So true, but it could also be used as a fail test :P

**Comment by sichvoge** [comment]
haha - very true :) I would not mind, if there is no test that does that, to have a PR that tests that ;)

**Comment by sucotronic** [comment]
Great! I'll close the issue then 👍
