### ISSUE TITLE
Schemas in RAML 0.8 files

### ISSUE THREAD

**Issue by nicolasgnr** [raml-org/raml-js-parser-2#221]
The parser is not replacing the schema references that are defined in the root node 'schemas' for RAML 0.8 files.

**Comment by petrochenko-pavel-a** [comment]
Why it should?

**Comment by nicolasgnr** [comment]
Because the previous parser used to do it and the new one should be compatible.

Regards,
Nicolas

**Comment by sichvoge** [comment]
@petrochenko-pavel-a is there any limitation to not replace it with the actual content during expansion?

**Comment by petrochenko-pavel-a** [comment]
Yep. 

At first if we will change it again we will again break compatibility (we already have guys using it), secondary there are reasons why we are not doing replacements any more:

a) Inlining schemas means loosing information about original text, however getting schema content is as simple as one lookup to global schemas object. 
b) You do not want to store to lot of redundant information in the resulting JSON (imagine serialising a real size API) so if information is easily restorable (in this case it is one lookup), it is better to avoid duplication.

P.S. if you still feel that you need this functionality please file an enhancement and I will add serialisation setting which turns on schema inlining.

Regards,
Pavel

**Comment by sichvoge** [comment]
the problem here is that we change behaviour that is expected to be the same. Many implementation have been build on top of that. I am not too concerned about making changes in 1.0, but lets keep compatibility with the old parser where ever possible.

Do I need to create a separated issue @petrochenko-pavel-a

**Comment by petrochenko-pavel-a** [comment]
Option `dumpSchemaContents` added to JSON serialization options (affects 0.8 files only), pushed to master
