### ISSUE TITLE
Wrong displayName in parser output

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#226]
Consider following example:

``` yaml
#%RAML 1.0
title: API used to test broken features
mediaType: application/json

types:
  myType:
    type: string
    description: string return
    minLength: 12
    maxLength: 12
    displayName: "Christian"

/:
  get:
    responses:
      200:
        body:
          type: myType
```

Using that, this is what I get back from the JSON object:

```
{ code: '200',
  body: 
   { 'application/json': 
      { name: 'application/json',
        displayName: 'application/json',
        type: [Object],
        repeat: false,
        required: true,
        __METADATA__: [Object] } } }
```

Please focus on the displayName. Inlining the type definition without using references, the json output is different.

```
{ code: '200',
  body: 
   { 'application/json': 
      { name: 'application/json',
        displayName: 'Christian',
        type: [Object],
        repeat: false,
        required: true,
        description: 'string return',
        minLength: 12,
        maxLength: 12,
        __METADATA__: [Object] } } }
```

Why is there such a difference with the displayName?

**Comment by petrochenko-pavel-a** [comment]
The difference is created by the fact that in first case you `displayName` is calculated by default calculator, so it defaults to the name of the type, and in the second case it is just settled manually.

Regards,
Pavel

**Comment by sichvoge** [comment]
So almost never get the right displayName?

**Comment by petrochenko-pavel-a** [comment]
What do you mean by right?

**Comment by sichvoge** [comment]
I defined my displayName to be "Christian", but get "application/json"

**Comment by sichvoge** [comment]
I think the behaviour is wrong, @ddenisenko can you please have a look on that.

**Comment by sichvoge** [comment]
Let's close this issue. It's an internal parser behaviour and how media types are implemented as part of the type system.
