### ISSUE TITLE
Provide a changelog please

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#231]
As there have been lots of releases recently I'd highly appreciate if you kept a changelog going, can be as simple as:

CHANGELOG:
```
# major
## minor
### patch
- changes
- morechanges
```

**Comment by sichvoge** [comment]
Whats the difference to providing better descriptions inside the releases here on github? I'd rather put more information there than creating another file and copy&paste the content between these two.

**Comment by SimonSchick** [comment]
It was an example, I don't really care what format the changelogs have as long they are somewhere.
Right now the releases don't feature any description other than how to install them (which is rather redundant btw).

**Comment by sichvoge** [comment]
We changed that and hope its more clear now.
