### ISSUE TITLE
Include paths management

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#233]
The new parser resolves include paths in a different way than the old parser being the key aspect where the root of the 'virtual fs' defined by the include paths is placed.
For the old parser, the root is the location where the root RAML file lives.

So, when the RAML is loaded using a URL (ex. `http://localhost/api/1/version/1/root.raml`), the root of the API is `http://localhost/api/1/version/1/` and all include file paths should be resolved against that root.

For example:
- absolute paths: `!include /examples/response.json` -> `http://localhost/api/1/version/1/examples/response.json`

- relative paths: `!include ../examples/response.json` will depend on where they appear. If the include is made in `http://localhost/api/1/version/1/traits/trait.yaml` the file must be loaded from `http://localhost/api/1/version/1/examples/response.json`; if it's included in `http://localhost/api/1/version/1/root.raml` -> `http://localhost/api/1/version/1/examples/response.json` because there can't be any files below the root of the API.

This can be better seen with a FS example. If an api located in `/api.raml` has this include `!include ../examples/example.json`, the file will be loaded from `/examples/example.json` because there is nothing below the root `/`

**Comment by ddenisenko** [comment]
The new parser does not have any roots.

I see no reason why we should not allow the parser to access the files, which are located a folder above the RAML file, and this is what you effectively propose. This will break lots of things, in example, API workbench users will be unable to open RAML files located in subfolders.

If user types in "../" in his include path, user should be responsible for that characters and not expect, that the instruction to move pointer one folder above will be magically ignored depending on where this instruction is located.

**Comment by juancoen** [comment]
The issue here is that the parser behaves differently when the RAML is loaded from a URL vs. from a 'local' path.

As specified before, when loaded from URL, the paths in includes in the root RAML with `../` are passed to `getResourceAsync` as resources in a lower level, for example if the include `!include ../examples/response.json` is being made in `http://localhost/api/1/version/1/root.raml`, the path is passed as `http://localhost/api/1/version/examples/response.json`, which fails.

The problem is that in the Designer, the same RAML is loaded using a path: `/root.raml`. In that case, the path passed to `contentAsync` for that same include is `/examples/response.json`, which resolved correctly to the included file.

This is a problem because it does not warn users about the error they are making in Designer, and things fail when loading the RAML using a URL. The parser should behave consistently, returning `../examples/response.json` to `contentAsync` and failing if that's the way it will work when loaded from a URL

**Comment by ddenisenko** [comment]
This case look correct for me:

`http://localhost/api/1/version/1/root.raml` + `../examples/response.json` = `http://localhost/api/1/version/examples/response.json`

Regarding the following case:
`/root.raml`  + `../examples/response.json` = `/examples/response.json`
I agree, that the result is questionable. 

Effectivelly, nothing exists above `/` path, so there is no way to resolve `/` + `..` . We can probably report an error in this case for consistency.

**Comment by juancoen** [comment]
👍 please report error in `/` + `..` case

Thanks!

**Comment by KonstantinSviridov** [comment]
Ok. Now there is a warning produced for paths exceedidn file system root
