### ISSUE TITLE
null value in the response type not allowed

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#234]
I have a raml and this part with the null value (˜) is being validated by the JS parser as 'Inheriting from unknown type'

  ``` yaml
        responses: 
          201: 
            body: 
              application/json: ˜
```

NOTE: It is a valid yaml

- I've been reading the spec and I've only found this:
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#null-type

- Could you please clarify me why it is not valid? Or is it a bug? 

Thanks
Eleonora

**Comment by petrochenko-pavel-a** [comment]
Hi @eleonoraortega ,

Looking on your sample:

```raml
 responses: 
          201: 
            body: 
              application/json: ˜
```

RAML 1.0 specifies that body parts of responses are actually type declarations (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#response-declaration). Type declarations on it own have the shortcut which allows you to declare a type as an sub type of a known type in a one line. For example following type declaration states that type `phoneNumber ` is a sub type of the `string`

```raml
types:
    phoneNumber: string
```

So in your case parser observes:
```raml
 application/json: ˜
```
which is equivalent to:
```raml
 application/json: 
    type: ~
```

and then logically complains that you are extending from unknown type named `~`

Regards,
Pavel

**Comment by KonstantinSviridov** [comment]
@petrochenko-pavel-a 
As per spec,
```
application/json: 
    type: ~
```
must not produce any error, but must be equivalent to
```
application/json: 
    type: null
```
