### ISSUE TITLE
Use white-spaces and single quotes in error messages

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#256]
A lot error messages contain no white-spaces between the static message and the dynamic part usually a name or another error message wrapped into it. For example: "specifying unknown facet:discriminator". As you can see, there is no white-space between the colon and "discriminator". That sometime makes reading harder.

As you can also see in there, there are no single quotes around the node name to indicate that its not part of the static message. There are cases where the dynamic injected part is part of the error message somewhere in between without a clear separation. It would be good if we can use single quotes so that you might get something like: "your example 'input1' does not conform to the provided schema".

**Comment by KonstantinSviridov** [comment]
to be released in 1.1.4
