### ISSUE TITLE
Browser distribution is bit heavy for browsers

### ISSUE THREAD

**Issue by jorgegarciamule** [raml-org/raml-js-parser-2#277]
Generated file browserVersion/raml-1-parser.js is 16MB. Compiled with Google closure using ADVANCED_OPTIMIZATIONS it went down to 5.1M. With gzip it goes to 1.2M. This represents around 60% on weight on this project https://github.com/mulesoft/api-console (assuming advanced minification).

**Comment by ddenisenko** [comment]
We agree. This is something we are trying to solve, the latest 1.1.2 release weights 3.4 MBs unarchived when used without (now) optional XML validation package. Please see https://github.com/raml-org/raml-js-parser-2/issues/432 for the current progress. 

I am closing this issue as duplicate as there's more content in the linked issue, so its easier to use that one to track.
