### ISSUE TITLE
Error message for invalid use of type expression for types defined with schemas

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#286]
The error message shown in the image example below is not very helpful. It should be more something like the comment behind `Person[]`.

![image](https://cloud.githubusercontent.com/assets/498114/16230729/df5ce54a-37ba-11e6-9239-39683804db4b.png)

**Comment by KonstantinSviridov** [comment]
@sichvoge This case is to similar to the following one:
```
...........
Board:
  properties:
    members:
      type: array:
      items: Person
```
These cases are semanticaly the same while of the different syntax. Think it's natural to have the same message for both of them. As the second case does not involve `[]` expression, the message should be something like
```
It is not allowed to use external types as array component types in types and type properties declarations
```
What do you think?

**Comment by eduardo-rubio** [comment]
You are right, please do that.

**Comment by postatum** [comment]
Closing for now as no answers. Feel free to provide more information and re-open if this is still relevant
