### ISSUE TITLE
Error message should be more clear about what facets it refers to

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#287]
In the following very invalid RAML example, the error message does not really help me to identify the conflicting facets. 

![image](https://cloud.githubusercontent.com/assets/498114/16230955/d9458a6c-37bb-11e6-8d64-7e16a405103a.png)

**Comment by KonstantinSviridov** [comment]
This is how the message is going to look:
![errornew](https://cloud.githubusercontent.com/assets/6206034/16816714/a80b0c34-4958-11e6-852e-802534272e10.png)

**Comment by sichvoge** [comment]
Isn't the actual problem

> Restriction conflict in type 'Number3': [ 'Number1.maximum=2' is less than 'Number2.minimum=4'. The minimum cannot be higher than the maximum. ]

**Comment by KonstantinSviridov** [comment]
Ok, I'll apply the same message pattern to all the pairs of MinMax restrictions:
```
minimum - maximum
minLength - maxLength
minItems - maxItems
minProperties - maxProperties
```

**Comment by sichvoge** [comment]
Perfect! We should always try to have a very clear message thats why I also mention that the conflict happens in type 'Number3'. I think we shouldn't always rely on the fact that a user uses an IDE but maybe purely the parser. It should be very easy to identify also from the message what the problem is.
