### ISSUE TITLE
Add support to parse RAML API fromt text instead of using a file path

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#3]
Currently, the only way to use the parser is to do:
```
var apiFilePath = 'api.raml';
var api = RAML.loadApi(apiFilePath).getOrElse(null);
```

There should be a way to pass the RAML text directly, for example:
```
var ramlText = '#%RAML 0.8\ntitle: Anypoint Exchange';
var api = RAML.loadApiText(ramlText).getOrElse(null);
```

**Comment by ddenisenko** [comment]
How are we going to deal with includes in such a case?

**Comment by juancoen** [comment]
There are multiple alternatives to deal with them.
For example, the old parser defined a "FileReader" interface and let the client provide an implementation of "FileReader", which is called each time an include is found.

**Comment by sichvoge** [comment]
Can you not provide an overload method - one that takes RAML text and another that takes a filereader as @juancoen suggested.

**Comment by petrochenko-pavel-a** [comment]
methods `parseRAMLSync` and `parseRAML` was added to parse API.
pushed to RC2.

Regards,
Pavel
