### ISSUE TITLE
Add support for modularization

### ISSUE THREAD

**Issue by rpaterson** [raml-org/raml-js-parser-2#30]
Add support for Overlays and Extensions.  Need to be able to handle multiple RAML files, so it probably won't fit in the current API.  Perhaps the `loadApi(...)` and `loadApiAsync(...)` methods could be overloaded to accept arrays of paths in addition to single paths?

I opened a PR https://github.com/raml-org/raml-js-parser-2/pull/29 with a test using the modularization examples from the spec.  See also discussion on the forum: http://forums.raml.org/t/how-to-include-an-extension-typed-fragment.

**Comment by ddenisenko** [comment]
Hi @rpaterson , this is something planned to be done quite soon.

**Comment by rpaterson** [comment]
great!

**Comment by rpaterson** [comment]
Fixed by https://github.com/raml-org/raml-js-parser-2/pull/55
