### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#300]
With parser 0.2.25. When I try and use a library all keys yield:

```
{ code: 2,
  message: 'Unknown node: usage',
  path: 'api.raml',
  start: 110,
  end: 114,
  line: 7,
  column: 0,
  range: 
   [ { line: 7, column: 0, position: 110 },
     { line: 7, column: 4, position: 114 } ],
  isWarning: false }
```

If I remove `usage` then next key with give the same error. I've tried a bunch of example libraries, all giving the same errors, even the example from the docs.

**Comment by KonstantinSviridov** [comment]
Hi, @domarmstrong 

I do not quite understand your case.
If you're trying to attach a library by means of `usage` key, then the error is correct, as the right key is `uses`.

If you obtain the error trying to specify `usage` (which, as the spec claims, "Describes the content or purpose of a specific library") for a library, then it's a bug.

**Comment by domarmstrong** [comment]
Turns out this was user error.
```
uses:
  common: !include libraries/foo.raml
```

Note I was using `!include`. I removed this and that fixed the problem. Although that was maybe not obvious and I'm not sure why the choice to not use include for libraries as it makes sence.

I did hit a bunch of other issues though. The library consists of a main library file including files in sibling level folders. These files seem to have some issues including types defined in the main file. Also resourceTypes exposed in the library where not recognised in the api definition with `common.MyResourceType`.

**Comment by KonstantinSviridov** [comment]
`!include` tag means plain text insertion. As the libraries have been allowed to have cyclic dependencies, the tag can no longer be used with them.

Could you, please, provide an example of what's going wrong.

**Comment by sichvoge** [comment]
@domarmstrong do you use parameters inside your libraries to inject types from your main?

**Comment by domarmstrong** [comment]
Going to close this one. I'll open more specific tickets if I hit them again.
