### ISSUE TITLE
Create a Language Server based on Microsoft's Language Server Protocol

### ISSUE THREAD

**Issue by aldonline** [raml-org/raml-js-parser-2#308]
Microsoft and others are working on a standard protocol to expose language services in a decoupled way (from a particular IDE). See:  https://github.com/Microsoft/language-server-protocol

Implementing an LSP based language server is an obvious next step for RAML tooling.

As a reminder, the original idea behind the modular design of the API workbench (exposing RAML parsers and tooling as stand-alone modules on different technologies) was meant to allow quick integration of RAML capabilities into popular IDEs.

**Comment by aldonline** [comment]
Work is happening here --> https://github.com/raml-org/raml-language-server

**Comment by sichvoge** [comment]
@aldonline does that really reside here on this repository. It seems that the language server and the repo you linked is sufficient enough, and there is no additional work on the parser (not yet at least). Agree?

**Comment by sichvoge** [comment]
I am closing that since it is not really related to that parser repo.
