### ISSUE TITLE
Method responses:  Response code 20x is invalid

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#312]
```yaml
#%RAML 1.0
title: test
types:
  TestType:
      type: object
      properties:
        field: string
      example:
        field: value
/test:
  get:
    responses:
      20x:
```

**Actual result:**
JS parser takes as valid the response code 20x, 40x, etc

**Expected result:**
It is not valid as it is not defined in the spec the usage of this

**Comment by ddenisenko** [comment]
From the spec, `Responses` section: 

```Keys are often numeric, for example 200 or 204. Processors MUST treat these numeric keys as string keys in all situations. ```

**Comment by sichvoge** [comment]
@ddenisenko that might be true for 1.0 but not 0.8; hence this seems to be a bug in 0.8 at least. If that is the case for 1.0, we will see. I doubt the goal was to provide you with the ability to define a response code like "20x". Where for example did we define that in the spec?

![image](https://cloud.githubusercontent.com/assets/498114/16378742/80e70612-3c65-11e6-8fb9-159a2647c518.png)

We need to double check the intention here.

**Comment by sichvoge** [comment]
Had a chat with Uri. There has been some intention in the past to support that, but was not implemented in the final version of the specification. That said, "x" should not be supported!
