### ISSUE TITLE
[TCK] TC004 Method responses: Validate missing 'type:' key

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#313]
```yaml 
#%RAML 1.0
title: test
types:
   TestType:
      type: object
      properties:
        field: string
      example:
        field: value
/test:
  get:
    responses:
      200:
        body:
          application/json: TestType
```

**Actual result:**
JS parser does not validate when type: key is missing

**Expected result:**
An error must be displayed when missing type: key is missing

**Comment by KonstantinSviridov** [comment]
Hi, @eleonoraortega 

The spec states about object under the `body` key:

Each key name MUST be a media type string conforming to the media type specification in RFC6838. The values are the corresponding data type declaration **or data type name** describing the request body. 

Thus, your example is correct from the spec view point.

Moreover the value is allowed to be empty, as data type declaration is allowed to be such.
