### ISSUE TITLE
Improve error messages for library chaining

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#328]
we should improve the error message when you use chaining of namespaces / libraries. currently you get: "inheriting from unknown type"

![image](https://cloud.githubusercontent.com/assets/498114/16486759/aefdf730-3ebe-11e6-8bf9-2f124cc40943.png)

**Comment by KonstantinSviridov** [comment]
Now the message is
```
 "Inheriting the 'files.file-type.File' type imported through a library chain. Library chaining is not allowed."
```

![chainigmessage](https://user-images.githubusercontent.com/6206034/30492848-2333ca6c-9a6c-11e7-8dee-71c26db330a4.jpg)

**Comment by sichvoge** [comment]
MH we probably have to englishify the message a little bit :) Let me think about that next week when I am back from OOO.
