### ISSUE TITLE
confusing error message when something is wrong in an example

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#332]
The attached project illustrates a very confusing error messages that indicates an error that an "object is expected" on an example (see image below). 

![image](https://cloud.githubusercontent.com/assets/498114/16519970/af9406fa-3f84-11e6-90d2-337cc88602be.png)

The actual problem is actually not that the example is not an object but rather some type errors inside the example object. Doing the expansion "manually" you get the following:

![image](https://cloud.githubusercontent.com/assets/498114/16520032/291882b2-3f85-11e6-9484-486d0d853404.png)

You see that there are for attributes that have an integer as value which must be string. Should the parser not be able to trace that down? It's hard to find it w/o manually copy & paste the example into the respective context. Additionally, we should not just say "string is expected" but rather call the attribute out where the problem occurs.

[customer-api.zip](https://github.com/raml-org/raml-js-parser-2/files/343314/customer-api.zip)

**Comment by KonstantinSviridov** [comment]
@sichvoge Actually, what can be observed in workbench now is
![trace](https://cloud.githubusercontent.com/assets/6206034/16700998/a3c0f098-4576-11e6-8898-c43817f0e2a8.png)
Isn't that enough?

**Comment by sichvoge** [comment]
Its confusing and not really intuitive just looking at the error message that is displayed at the bottom. Maybe that's why changing the order for error messages makes a lot of sense. If you hover over the error you might see more, but the initial error ("object is expected") is actually not the problem and shouldn't be displayed like that.

**Comment by KonstantinSviridov** [comment]
The initial "object is expected" message is incorrect and was being displayed due to https://github.com/raml-org/raml-js-parser-2/issues/339.

Thus, in this example both error and trace have same error messages, and reversing the order will not help.

(Note that in this example there are actually four errors with same messages, which are collapsed into one error, which provides traces of the original errors)
