### ISSUE TITLE
Unclear error message using discriminator

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#357]
![image](https://cloud.githubusercontent.com/assets/498114/16873731/f74be43c-4a8c-11e6-8c18-58742f5ed3a0.png)

The error messages are not very clear to me and what I need to do. The first `PersonOrDog` should indicate that I am not allowed to define the `discriminator` facet on unions. From the spec:

> Neither discriminator nor discriminatorValue can be defined for any inline type declarations or union types.

**Comment by KonstantinSviridov** [comment]
to be released in 1.1.4
