### ISSUE TITLE
require('raml-1-parser') takes ~4s

### ISSUE THREAD

**Issue by kamilzasada** [raml-org/raml-js-parser-2#361]
Hi. I'm working on a tool for generating documentation from RAML spec. This is command line tool so in my opinion performance is crucial...and I have performance problems with RAML parser: `var raml = require('raml-1-parser');` - this takes around 4s! Do you have some advice on how to reduce this time?

> package.json - "raml-1-parser": "^0.2.27"

**Comment by ddenisenko** [comment]
Its rather strange that it takes that long for you, but, anyway, this is related to the parser size. 

Please try 1.1.2 version of the parser, its rather smaller than the older versions. 

Please watch for https://github.com/raml-org/raml-js-parser-2/issues/432 for the further progress in parser size reduction.
