### ISSUE TITLE
Additional Properties must be allowed in responses

### ISSUE THREAD

**Issue by eleonoraortega** [raml-org/raml-js-parser-2#367]
```yaml

#%RAML 1.0
title: hello
mediaType: application/json
types:
  MyType:
    properties:
      x: string

/hello:
  get:
  post:
    responses:
      202:
        body:
          application/json:
            type: object
            properties:
              hello:
                type: number
                minimum: 0
                maximum: 10
                format: int
              key:
                type: object
                properties:
                  x: string
                example:
                  x2: 123
          application/xml:
            type: string
/world:

```

**Actual result:**
```
{
      "code": 11,
      "message": "Unknown property:x2",
      "path": "lala.raml",
      "start": 522,
      "end": 524,
      "line": 27,
      "column": 18,
      "range": [
        {
          "line": 27,
          "column": 18,
          "position": 522
        },
        {
          "line": 27,
          "column": 20,
          "position": 524
        }
      ],
      "isWarning": true
    }
```

**Expected result:**

Additional properties are by default true, therefore x2 is valid

**Comment by ddenisenko** [comment]
Well, the resulting validation issue is a warning. That looks correct for me.

**Comment by sichvoge** [comment]
But in case of the spec, its clear that additional properties in any instance is by default allowed. So there shouldn't be any warning or error

**Comment by ddenisenko** [comment]
Warning is pointing to a potential error, not to something being forbidden by the spec.

The probability of user simply mistyping the property name is high. Parser just provides help by asking: "are you sure its intentional?" that way.

**Comment by sichvoge** [comment]
The question is if the TCK should test against warnings as well. That is something that we don't call out explicitely in the spec and only do for convenience inside the js parser. So let's not test against warnings.

@svacas @KonstantinSviridov @eleonoraortega any objections?

**Comment by ddenisenko** [comment]
It really depends, which amount of compatibility between the parsers we want to have, and when we want it.

At the moment it is even unclear if we are going to have compatibility on number of errors level, left alone error messages, positioning, warnings and JSON structure. So, skipping warnings comparison sounds pretty fine for me until we want to make parsers more compatible.

**Comment by sichvoge** [comment]
Let's ignore warnings for this release.
