### ISSUE TITLE
Improve error messages for nodes that are not allowed on other nodes as per spec

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#395]
Currently, every time someone uses a node that is not allowed in another since the spec does not allow it we send a very generic message back "Unknown node: xxx". For example

![image](https://cloud.githubusercontent.com/assets/498114/17210559/95d3f314-54bb-11e6-9983-a60efe242f55.png)

IMHO, we have enough information to give the dev enough information to point out that it is not allowed in the specification. In the example above we could say: "RAML 0.8 does not allow the usage of `displayName`  within methods.", or something else.

**Comment by KonstantinSviridov** [comment]
I suggest using the following message template for properties with known names used in inappropriate types:
```
{{ramlVersion}} does not allow using '{{propName}}' property within the '{{typeName}}' type.
```

**Comment by KonstantinSviridov** [comment]
In yuor case it is goung to be

RAML 0.8 does not allow using 'displayName' property within the 'Method' type.

**Comment by sichvoge** [comment]
MH not sure about the `type` in the end.

**Comment by KonstantinSviridov** [comment]
I've finally realized that we can easily change words to plural form and changed the message template to
```
{{ramlVersion}} does not allow using '{{propName}}' property within {{typeName | !pluralize | !lowercase}}.
```
So, for method case it's just `methods`, not `'Method' type`
