### ISSUE TITLE
expand array type expressions

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#407]
The parser should remove the type expression for arrays `[]` and kinda "expand" it to its original type form `type: array`. That will help to avoid consumer to always parse both `type: array` and `[]`, and do the expansion by themself. For example:

`type: Bank[]` should be

```yaml
type: array
items: Bank
```

**Comment by KonstantinSviridov** [comment]
Implemented in 
https://github.com/raml-org/raml-js-parser-2/commit/ee143418c3648df9c0a5a8435c0b7230f02ed9a3
