### ISSUE TITLE
Array type

### ISSUE THREAD

**Issue by capt4net** [raml-org/raml-js-parser-2#41]
Hi,
Is it OK that 

`response.body()[0].type()` is SysManagementTypes.Channel[]

but 

`response.body()[0].definition().allSuperTypes()[0]` is String[] 

?

BTW, How can I get access to properties/examples of properties of type from response.body()[idx] ?

For example, I have response body type SysManagementTypes.Channel which have some properties:

 ``` Channel:
    properties:
      id: number
      name: string
      protocol: ChannelProtocol
      ipAddress: IpAddress
      port: number
      status: ChannelStatus
    example:
      id: 1
      name: Sample Channel
      protocol: Udp
      ipAddress: 192.168.218.109
      port: 2077
      status: Playing
```

and I can get this type by `response.body()[0].type()`. But I need to iterate all properties of the Channel type. How to do that? 

And what if body type is `Channel[]` (an array)?

**Comment by ddenisenko** [comment]
@capt4net We'll add types section to https://github.com/raml-org/raml-js-parser-2/blob/gh-pages/GettingStarted.md in order to clarify such cases very soon.

**Comment by capt4net** [comment]
Thanks!

**Comment by petrochenko-pavel-a** [comment]
I guess it is safe to close it now. 
Regards,
Pavel
