### ISSUE TITLE
parsing returns null

### ISSUE THREAD

**Issue by woodp** [raml-org/raml-js-parser-2#42]
Parsing [this RAML](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/Raml.Tools.Tests/files/twitter.raml) and [this RAML](https://github.com/mulesoft-labs/raml-dotnet-tools/blob/master/Raml.Tools.Tests/files/instagram.raml) return null

**Comment by sichvoge** [comment]
Did you try to see if there has been any errors?

**Comment by woodp** [comment]
Yes, can't get any errors as the returned object is null

**Comment by ddenisenko** [comment]
Fixed in 0.8.9.
