### ISSUE TITLE
What's "unknown type null"

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#428]
![image](https://cloud.githubusercontent.com/assets/498114/17776811/f001d93c-6555-11e6-8322-7382385044da.png)

it should be "unknown type 'date'"

**Comment by KonstantinSviridov** [comment]
Hi, Christian. I'm having problems with reproducing this issue in `master` and with the published parser. Could you upload the whole RAML project here, please?

**Comment by ddenisenko** [comment]
```
#%RAML 1.0

title: test

types:
  TestType:
    properties:
      prop:
        type: date
        required: false
```

Reproducible.
