### ISSUE TITLE
Recursivity Example File is Not Validated

### ISSUE THREAD

**Issue by fescobar** [raml-org/raml-js-parser-2#430]
When an example file include itself it doesn't appear error message.

File examples/entities.json
`!include examples/entities.json`

Complete example (see attachment):
[API_Recursive-v1.0.zip](https://github.com/raml-org/raml-js-parser-2/files/433196/API_Recursive-v1.0.zip)

**Comment by KonstantinSviridov** [comment]
Hi, @fescobar 

As far as I see, the parser produces a warning for your case:

![recursiveexample](https://cloud.githubusercontent.com/assets/6206034/17906171/69f4811a-69a0-11e6-9723-d5ce0f94f28c.png)

The reason for producing a warning rather then an error is to maintain compatibility with the previous RAML 0.8 JS parser, which does not validate examples.

**Comment by fescobar** [comment]
I prove this case in the Designer of API Platform. I suppose is another version of js-parser.

**Comment by KonstantinSviridov** [comment]
What you observe may happen due to API Designer skipping warnings.

**Comment by fescobar** [comment]
Ok, thanks! You can close this issue.
