### ISSUE TITLE
Optional responses are not accepted 

### ISSUE THREAD

**Issue by mpfau** [raml-org/raml-js-parser-2#436]
The error `Only method nodes can be optional` is thrown, when responses are marked as optional. This was perfectly fine in RAML 0.8 and we use it to encapsulate our error handling in a library.

Is this the expected behaviour? Only workaround for us would be to define a separate trait for each response. But that whould complicate the whole error handling which has been so simple with RAML 0.8.

Example:

``` yaml
#%RAML 1.0
title: optional-bug
traits:
  throwingErrors:
    responses:
      400?:
        description: Bad Request
      404?:
        description: Not found
/test:
  post:
    is: [ throwingErrors ]
    responses:
      400:
```

**Comment by KonstantinSviridov** [comment]
Hi, @mpfau 

Yes, this behavior is expected. In 1.0 only methods are alowed to be optional
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#declaring-http-methods-as-optional

Regards, Konstantin

**Comment by mpfau** [comment]
Hi @KonstantinSviridov,
that's too bad :(

I guess we have to define a separate trait for each error. Or do you have an idea on how to simplify this?

Thanks!
Matthias

**Comment by KonstantinSviridov** [comment]
Yes, it seems that you have to define a separate trait for each response.

@sichvoge , may be we should alow optional responses?

**Comment by mpfau** [comment]
@KonstantinSviridov @sichvoge 
I would be very happy if you would allow optional responses. This would enables appropriate abstractions for the whole error handling.

We are currently using 0.1.0-beta.7 of the parser where optional responses were still possible.

Best,
Matthias

**Comment by sichvoge** [comment]
That might be more a discussions for the spec rather than the parser ;)

**Comment by KonstantinSviridov** [comment]
Closing util the decision on spec is made.
