### ISSUE TITLE
problem with expanding external files including parameters

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#438]
According to https://github.com/raml-org/raml-spec/issues/560, there is an issue with expanding external files that include parameters such as `<<resourcePathName>>`. I tried the example and can confirm that the parser does not replace the parameters with its value (see image below).

![image](https://cloud.githubusercontent.com/assets/498114/18166090/fb8b0d50-7040-11e6-81e0-5bc2e05f2237.png)

Also the API Workbench does not throw any error here as well. Does that mean its being done correctly inside the workbench? I only get an error inside the type fragment for the resource type obviously since the trait is not available in there and thats ok, and also to be expected. But the main file is the one that concerns me a bit. No error and the data model output of the expanded tree does not contain the correct type.

**Comment by sichvoge** [comment]
That actually is the same if I put everything into libraries and reference from there.

**Comment by sichvoge** [comment]
So it seems only parameters in the `type` node do not get replaced. All the other parameters that has been placed on other nodes such as `description`, have been resolved perfectly fine.

**Comment by KonstantinSviridov** [comment]
@sichvoge For me it works fine with `type` also. I guess, the reason is that we do not support multiple transforming functions.

**Comment by sichvoge** [comment]
but it did not work even for a single function. not in the workbench, nor the parser. or should i try that with the newest again? can you add your output in here so that we can compare

**Comment by KonstantinSviridov** [comment]
ok.
api.raml:
```
#%RAML 1.0
title: test API
resourceTypes:
    collection: !include rt.raml

/example:
  type: collection
```
rt.raml:
```
#%RAML 1.0 ResourceType
description: A collection of <<resourcePathName|!uppercamelcase>>
post:
  description: |
    Get all <<resourcePathName|!uppercamelcase>>,
    optionally filtered
  body:
    application/json: <<resourcePathName|!uppercamelcase>>
```

**Comment by KonstantinSviridov** [comment]
output:
```
{
  "ramlVersion": "RAML10",
  "type": "Api",
  "specification": {
    "resourceTypes": [
      {
        "collection": {
          "description": "A collection of <<resourcePathName|!uppercamelcase>>",
          "name": "collection",
          "post": {
            "body": {
              "application/json": {
                "name": "application/json",
                "displayName": "application/json",
                "type": [
                  "<<resourcePathName|!uppercamelcase>>"
                ],
                "required": true
                }
              }
            },
            "description": "Get all <<resourcePathName|!uppercamelcase>>,\noptionally filtered\n",
            "method": "post"
          }
        }
      }
    ],
    "title": "test API",
    "resources": [
      {
        "methods": [
          {
            "body": {
              "application/json": {
                "name": "application/json",
                "displayName": "application/json",
                "type": [
                  "Example"
                ],
                "required": true
                }
              }
            },
            "description": "Get all Example,\noptionally filtered\n",
            "method": "post"
          }
        ],
        "type": "collection",
        "description": "A collection of Example",
        "relativeUri": "/example",
        "displayName": "/example"
        },
        "relativeUriPathSegments": [
          "example"
        ]
      }
    ]
  },
  "errors": [
    {
      "code": 11,
      "message": "inheriting from unknown type",
    }
  ]
}
```

**Comment by sichvoge** [comment]
Can you try that example that is linked in #443 please. Thats the original one and why I created that issue.

**Comment by KonstantinSviridov** [comment]
I have `[ "song" ]` for `/songs/post/body/application/json/type` in the output JSON

**Comment by KonstantinSviridov** [comment]
Do you get something else?

**Comment by sichvoge** [comment]
ok then it might be fixed in the current version; let me confirm that.

**Comment by sichvoge** [comment]
Try this example, linked the wrong in my last comment. It appears that the parameter does not get resolved.

[testing.zip](https://github.com/raml-org/raml-js-parser-2/files/456897/testing.zip)
