### ISSUE TITLE
Add toJSON methods on nodes

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#44]
Adding toJSON methods on the nodes would ease some of the navigation of the ast.

**Comment by sichvoge** [comment]
Are they not there? Seeing them in the documentation https://raml-org.github.io/raml-js-parser-2/modules/_raml1_artifacts_raml10parser_.html

**Comment by domarmstrong** [comment]
Ah ye they are on some things but not all

**Comment by sichvoge** [comment]
haha - do you know which ones?

**Comment by domarmstrong** [comment]
For example you annotations() returns a list of annotation references, which you can't just call toJSON on to get the object. Exploring these things feels quite archaic at the moment.

method.annotations(), resource.uriParameters(), resource.securedBy(). These kinds of items. Also uriParameters don't have `value().toHighLevel()`. Basically it feels pretty much like you there is not consistent way to interact with various nodes.

**Comment by petrochenko-pavel-a** [comment]
Hi @domarmstrong as well as I see from @KonstantinSviridov commit, this issue should be fixed now.
Please let me know if you see a room for further improvements.
Regards,
Pavel
