### ISSUE TITLE
API Console does not change example when mediaType is changed.

### ISSUE THREAD

**Issue by brettkroeder** [raml-org/raml-js-parser-2#440]
When I change the mediaType to XML the example remains JSON.
<img width="508" alt="anypoint_platform_for_apis___api_administration___customer_-_1_2___designer" src="https://cloud.githubusercontent.com/assets/8449580/18183550/e320be28-7062-11e6-8b5d-8b7a596bd3f8.png">

**Comment by sichvoge** [comment]
closing that as this is not relevant for the js parser
