### ISSUE TITLE
Error messages on JSON schema validation not really helpful

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#444]
This is related to #443 and I am using the same example that is attached there.

![image](https://cloud.githubusercontent.com/assets/498114/18245475/60ad3810-735d-11e6-8597-f0d6fcbc77b4.png)

As you can see I am getting a very long message that tells me two times that the example / content is not valid according to the schema, followed by an error string that I can not identify what the actual problem is. Even worse, the error mark is on `/songs` and the trace information gets me up to the resource type which is not helpful either.

@ddenisenko we need to work on the error messages as part of the refactoring!

**Comment by ddenisenko** [comment]
Christian, I cant reproduce the error to be reported both in parser and in workbench.

I had to break the example intentionally to get some error: changed `ID` inside `jukebox-include-song-new.sample` file to contain more than 36 symbols.

As a result, I see the error with the trace pointing to `songs` and `example` in `collection/post`.
It looks reasonable for me: the `songs` resource is the first "real" (existing in original RAML code) node, which is broken, then we are pointed to `example` node, which contain the invalid example after expansion.

**Comment by KonstantinSviridov** [comment]
Well, error messaging is still imperfect for this case.

![emessage](https://user-images.githubusercontent.com/6206034/27489086-757f03ae-5863-11e7-972f-76c23dd84c60.jpg)

**Comment by sichvoge** [comment]
It would be good to know what property expects a string value and also we should probably mark the example that fails. Is it `exampleCollection` or `exampleItem`?

**Comment by KonstantinSviridov** [comment]
Yoy're right

**Comment by KonstantinSviridov** [comment]
Ok. Now the message has better positioning, and its trace points to all necessary places including the one in the external JSON example.

![invalidexamplepassedasparam](https://user-images.githubusercontent.com/6206034/28734534-94f69364-740b-11e7-8c19-355d802d5a1b.jpg)

**Comment by petrochenko-pavel-a** [comment]
Ugh, sounds like a pretty cool feature!
