### ISSUE TITLE
Cannot run: No /dist directory in build

### ISSUE THREAD

**Issue by ashleydw** [raml-org/raml-js-parser-2#445]
The package file is relying in `/dist/index.js` to run, but there seems to be no dist directory in the root.

**Comment by KonstantinSviridov** [comment]
Hi, @ashleydw 

Have you checked out the module from the present repository?
If so, you have to follow the procedure: https://github.com/raml-org/raml-js-parser-2/blob/master/README.md#setting-up-parser-development-environment

If you do not need to deal with code of dependencies (such as typesystem, definition system, etc), you may skip cloning dependencies, removing them from `node_modules` and linking them.

Regards, Konstantin
