### ISSUE TITLE
add method to automatically import inherited items

### ISSUE THREAD

**Issue by cascer1** [raml-org/raml-js-parser-2#447]
Right now, when I go through an API spec to write documentation, I have to loop through all items to find types, kinds, is's and the likes and manually add them to the corresponding item so I can insert them in the templating language (the templating language I use doesn't support calling methods on an item). I would like to see a method like `api.resolveInheritance()` that automatically does all this for me. So instead of it outputting something like:

```
"body": {
  "application/json": {
    "name": "application/json",
    "displayName": "application/json",
    "type": [
      "AnotherEntry"
    ],
    "required": true,
  }
}
```

as a method response body, it will output the fully resolved version.

**Comment by ddenisenko** [comment]
Do I get it right that you want to have a mechanism for RAML types, which inserts data, like properties, from super types, recursively?

**Comment by cascer1** [comment]
Exactly!

**Comment by ddenisenko** [comment]
This is a work in progress, but I have no estimations of when it will be available.

**Comment by cascer1** [comment]
Thanks for the update, I can't wait :)

**Comment by sichvoge** [comment]
That's kinda done [here](https://github.com/raml-org/raml-parser-toolbelt/tree/master/tools/datatype-expansion) already. Its a tool outside the parser that you could use. 

But please bear in mind that resolving types is not an easy to solve problem as you might imagine.

**Comment by cascer1** [comment]
Thanks for the suggestion, I'll see if I can use that tool for something!

I understand the type resolving is not an easy problem to solve, which is why I hoped someone else already did it :)

**Comment by ddenisenko** [comment]
Type expansion including the enhancement you want (adding properties from the super-type) was implemented. I am not sure when it's going to be released, but probably quite soon. Please check new releases for type expansion feature.
