### ISSUE TITLE
The code location of error generated by the parser is wrong

### ISSUE THREAD

**Issue by e-cloud** [raml-org/raml-js-parser-2#450]
After checking the error object, the location of the code where error occurs is **1 line above**.

That's say, if the error object shows **range is from line 33**, in fact, it's **from line 34**.

you can reproduce the problem from [the sample code of another issue](https://github.com/raml-org/raml-js-parser-2/issues/449#user-content-example-anchor)

**Comment by ddenisenko** [comment]
@KonstantinSviridov It looks like we're calculating lines starting from 0, not 1. Is that intentional?

**Comment by KonstantinSviridov** [comment]
Right, line number, column and position all start from 0, not 1.
This circumstance is already reflected in descriptions inside schemas for parser JSON of both formats. We should also make this information available in JS-doc comments for the error interface.
