### ISSUE TITLE
Very confusing package naming

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser-2#452]
RAML 0.8: NPM package raml-parser, url https://github.com/raml-org/raml-js-parser
RAML 1.0: NPM package raml-1-parser, url https://github.com/raml-org/raml-js-parser-2

I don't understand the differences between `raml-parser` and `raml-js-parser`, and why the second version isn't just the same NPM package but with a new major version number? Or at least have the `-2` postfix as well? 

It continues to break my brain every time I need to install any of these packages or search for them. Maybe a start is to rename this repo to raml-1-parser, so that it's the same as the NPM package?

**Comment by sichvoge** [comment]
I agree with you. Its kinda confusing naming convention and the repo + npm package name should be the same. I still can't live with `raml-1-parser` since it might indicate its only for RAML 1.0; but it isn't. I could live with `raml-js-parser` for both though.

**Comment by postatum** [comment]
Note that raml-js-parser-2 has been deprecated, the new official parser is [webapi-parser](https://github.com/raml-org/webapi-parser).
