### ISSUE TITLE
Shouldn't the POST responses body be expanded here?

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser-2#455]
Using this example: https://github.com/raml-org/raml-examples/blob/master/others/world-music-api/api.raml.

```
types:
  Entry: |
    {
      "type": "array",
      "items": {
        "$ref": "#/definitions/song"
      },
      "definitions": {
        "song": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "artist": {
              "type": "string"
            }
          }
        }
      }
    }
  AnotherEntry:
    type: Entry
    description: |
      This is just another entry to simulate that you can add facets also on JSON
      schema defined types. Although you can only add documentation-based facets.
/entry:
  post:
    responses:
      200:
        body: AnotherEntry
```

So the POST method for the `/entry` resource has a 200 response defined, with the body pointing to the `AnotherEntry` type.

Now I am looking in the parsed raml object and I get something like this for the 200 body: 

```
{ name: 'application/json',
  displayName: 'application/json',
  type: [ 'AnotherEntry' ],
  required: true
}
```

Maybe I am just being stupid here, but shouldn't I expect information from the `AnotherEntry` type here, like the description? Or is this not "expanded" into the raml object like what kinda happened with the GET resource that is added because of main resource type has one defined (see #454)?

It feels like the output would be a lot more usable if the actual type properties would be moved into the thing that uses it, if that makes sense.

**Comment by sichvoge** [comment]
The type information are not expanded. That is on purpose since types are the only information that are very useful for clients and we want to preserve them. Hence, a full expansion would not make sense in the standard output of the parser.

**Comment by kevinrenskers** [comment]
Ah, then it confuses me that the GET method is added to the response because of a type on the resource (see that other ticket). I am very happy that it happens, but it feels inconsistent.

**Comment by kevinrenskers** [comment]
Also makes me wonder where this name, displayName and required properties come from, since that is not in the RAML file:

```
/entry:
  post:
    responses:
      200:
        body: AnotherEntry
```

Are those all the default values?

**Comment by sichvoge** [comment]
> GET method is added to the response because of a type on the resource (see that other ticket).

Thats because `type` in this case is a resource type not a RAML data type :) I know its a bit confusing.

**Comment by kevinrenskers** [comment]
Alrighty then

**Comment by usarid** [comment]
@sichvoge said:
>That is on purpose since types are the only information that are very useful for clients and we want to preserve them.

Types are not at all the only pre-expansion information important to clients, for example to documentation generators, enterprise pattern validators, etc. Information about the resource types, traits, and security schemes used to generate the flattened HTTP behavior us important to be kept and made available for use by clients.
