### ISSUE TITLE
securedBy responses not added to method?

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser-2#463]
I'm using this example RAML file: https://github.com/raml-org/raml-examples/tree/master/others/world-music-api/

`GET /songs` is securedBy oauth_2_0, and because of that it gets an extra queryParameter, namely `access_token`. But the 401 and 403 responses that are defined in the oauth_2_0 scheme are not added to the method. Why is the queryParameter added to the method but not the responses?

**Comment by ddenisenko** [comment]
I am pretty sure I was answering this question already (maybe other ticket, do not remember), but `GET /songs` is not getting its `access_token` from security scheme, it is getting the parameter from its trait `secured`
