### ISSUE TITLE
Parser should return the protocol(s) specified at the baseUri if the protocols property is not defined

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#47]
As defined in the 1.0 spec:

The OPTIONAL protocols property specifies the protocols that an API supports. **If the protocols property is not explicitly included, the protocol(s) specified at the baseUri property is (are) used**

**Comment by KonstantinSviridov** [comment]
Ok. Looks like one more helper method.

**Comment by ddenisenko** [comment]
Fixed. Fix should be available in 0.1.0-beta.2.
