### ISSUE TITLE
Unsupported annotation target 'NamedExample'

### ISSUE THREAD

**Issue by eduramiba** [raml-org/raml-js-parser-2#471]
When importing an annotations library, an error is shown, while it's not shown in the annotation file.

Annotation file (`exampleInput.raml`):

```raml
#%RAML 1.0 AnnotationTypeDeclaration
displayName: exampleInput
description: input values for an example
allowedTargets: NamedExample
type: object
```

Import file (`annotationsLibrary.raml`) - Shows an error in the parser:

```raml
#%RAML 1.0 Library
annotationTypes:
  exampleInput: !include exampleInput.raml
```

I have also seen this error produce an infinite loop on our long api.raml file, but I can't reproduce it with a minimum example. It happens in the following part of the code, where there is a cyclic reference:

![1](https://cloud.githubusercontent.com/assets/197285/18756335/df67ca18-80ef-11e6-84e5-6454e8753261.jpg)
![2](https://cloud.githubusercontent.com/assets/197285/18756358/f1cae672-80ef-11e6-8df5-ec0b10943b3a.jpg)

Thank you!

**Comment by ddenisenko** [comment]
Reproduced the first part, thank you.

**Comment by KonstantinSviridov** [comment]
@ddenisenko The first part is fixed. Unable to reproduce the second part.

@eduramiba are you sure that the infinite cycle is caused by this issue? Does the infinite cycle persist if you remove the `allowedTargets` property from the fragment?

**Comment by eduramiba** [comment]
@KonstantinSviridov Yes, the problem disappears if I remove the allowedTargets property, but it might be a side effect.

**Comment by ddenisenko** [comment]
Closing as fixed for the original (part 1). Please create a ticket if the way to reproduce the deadloop is found.

**Comment by eduramiba** [comment]
Great, thanks!

I tried to reproduced it with a small example but I was not able to find the actual problem. Seems to be something related to uses of uses that have issues...

**Comment by eduramiba** [comment]
Hi,
I guess correct `allowedTarget` is `Example` then, and not `NamedExample`, right?

**Comment by KonstantinSviridov** [comment]
Hi, @eduramiba 
You're right. The correct value of `allowedTargets` property is `Example`

**Comment by eduramiba** [comment]
I see, thanks!
