### ISSUE TITLE
Missing method.displayName 

### ISSUE THREAD

**Issue by cascer1** [raml-org/raml-js-parser-2#472]
Hi,

I'm writing a documentation tool for RAML API specs and want to use the method.displayName attribute to display human-friendly titles. 

According to [the spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#methods), methods do support the displayName attribute. However, the parser does not seem to support this. 

For example, I have the following spec:

```
/users:
  displayName: Users
  description: Create, manage and remove users
  post:
    displayName: Create user
...
```

I get the following output from the parser:

```
{
	"resources": [{
		"relativeUri": "/users",
		"displayName": "Users",
		"methods": [{
			"method": "POST"
		}]
	}]
}
```

Instead, the displayName attribute for the method is missing.

**Comment by ashleydw** [comment]
You mean description, right?

**Comment by cascer1** [comment]
No, I mean displayName.

According to [the spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#methods), methods can have a displayName.

**Comment by ashleydw** [comment]
But it's right there?

```
{
    "resources": [{
        "relativeUri": "/users",
        "displayName": "Users",
        "methods": [{
            "method": "POST",
            "displayName": "Create user" <== displayName
        }]
    }]
}
```

**Comment by cascer1** [comment]
Oh, that's because I typed what I *wanted* to see but didn't really label it as such..

**Comment by ashleydw** [comment]
I ran this using 1.1.3 parser:

```
#%RAML 1.0
title: Test

/users:
  displayName: Users
  description: Create, manage and remove users
  post:
    displayName: Create user
    description: Something something
```

```
const raml = require('raml-1-parser');
const util = require('util')
raml.loadApi('test.raml', { rejectOnErrors: true }).then((result) => {
  console.log(
    util.inspect(result.expand(true).toJSON({ serializeMetadata: false }), {showHidden: false, depth: null})
  );
}).catch(function(error) {
    console.error(error)
})
```

Output:

```{ title: 'Test',
  resources:
   [ { methods:
        [ { description: 'Something something',
            displayName: 'Create user',
            method: 'post' } ],
       description: 'Create, manage and remove users',
       relativeUri: '/users',
       displayName: 'Users', <== displayName
       relativeUriPathSegments: [ 'users' ] } ] }```

**Comment by cascer1** [comment]
Oh God I just realised, I'm testing with a RAML 0.8 document, those didn't support method displayNames yet.
