### ISSUE TITLE
toJSON should include absolute Uri

### ISSUE THREAD

**Issue by cascer1** [raml-org/raml-js-parser-2#473]
Hi,

I noticed that the api.toJSON() method does not include resource.absoluteUri in its output. It would be very useful if this were included, because now I have to recurse over everything myself and modify the JSON output to include the absoluteUri that I need in a tool I'm making.

**Comment by KonstantinSviridov** [comment]
Hi, @cascer1 

the `absoluteUri` field will appear in 1.1.5

**Comment by KonstantinSviridov** [comment]
https://github.com/raml-org/raml-js-parser-2/commit/bfb9005f05f55fb45e6bacda1af559a888b5c5fd
https://github.com/raml-org/raml-js-parser-2/commit/f08d381f81ee67d12cfda168f5414d1702dd08de

**Comment by cascer1** [comment]
I'm using 1.1.5 but do not see the `absoluteUri` field anywhere in the generated JSON.

**Comment by sichvoge** [comment]
@cascer1 1.1.5 is a hotfix for a couple of major issues only. See [release notes](https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.5). This will probably go in for the next sprint release.
