### ISSUE TITLE
How to build an AST from toJSON()

### ISSUE THREAD

**Issue by baloo** [raml-org/raml-js-parser-2#474]
Hello there, 

Usecase: server in express, reading local files, with `!include http://somewhere/else.raml `, then replying to client in JSON. The react client side rebuilds html from the server output. It's easier to reason about the AST than a pure json. 

Is there any way to rebuild an AST object from the `toJSON()` output?

**Comment by ddenisenko** [comment]
No, there is no way to rebuild AST object from toJSON() output. I'd also recommend to avoid relying on the current AST (top-level layer) as there are chances that this layer will be deprecated, in future, toJSON() and high-level layer will remain untouched.
