### ISSUE TITLE
ArrayTypeDeclaration.items() does not work for scalar array types defined by "[]" expression

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#475]
This still doesn't work for scalar types like string[]. items() and findComponentTypeDeclaration() both return null. I would expect a StringTypeDeclaration to be returned. How else would you know this is a string array?

I would also expect type expressions like (string | number)[] to be expanded to array.items() == UnionTypeDeclaration.

**Comment by KonstantinSviridov** [comment]
Hi, @domarmstrong 

The purpose of `items` method is to return value of `items` property which has been entered by the user. For purposes of analysing types defined by expressions runtime type system should be used.

For instance, string array types as
```
types:
  MyType: string[]
```
may be detected by the following code:
```
function isStringArray(MyType){
  var rt = MyType.runtimeDefinition();
  if(!rt.isArray()){
    return false;
  }
  var ct = rt.componentType();
  return ct.nameId() == "StringType";
}
```

and string subtype arrays
```
types:
  MyStringType: string
  MyType: MyStringType[]
```
may bew detecte by:
```
function isStringSubtypeArray(MyType){
  var rt = MyType.runtimeDefinition();
  if(!rt.isArray()){
    return false;
  }
  var ct = rt.componentType();
  return ct.allSuperTypes().filter(x=>x.isValueType()&&x.nameId()=="StringType").length>0;
}
```

Regards, Konstantin

**Comment by domarmstrong** [comment]
Thanks
