### ISSUE TITLE
types: Foo: [] yields unexpected StringTypeDeclaration

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#476]
```
types:
  Foo: []
```

This gave me the unexpected result StringTypeDeclaration. I'm guessing this isn't actually valid to just use [] to define an array as it says in the spec:

> Array types are declared by using either the array qualifier [] at the end of a type expression or array

This should probably fail at parse time? Or it should just be synonymous of `array`.

**Comment by KonstantinSviridov** [comment]
Hi, @domarmstrong 

In the example you specify zero supertypes for the `Foo` type ([see](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#multiple-inheritance)), which is equivalent to not specifying `type` at all, which, in turn, is equivalent to specifying `string`.

At the same time, to me `Foo: []` looks more like a typo then a shortcut for `Foo: string`. So, producing an error may be better in this case. @ddenisenko , @sichvoge, what do you think?
