### ISSUE TITLE
Question: Inherited and Union TypeDeclarations

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#477]
```
types:
  Foo:
    properties:
      foo: string
  Bar:
    properties:
      bar: string
  Baz: [ Foo, Bar ]
```

Baz is an ObjectTypeDeclaration but properties() returns []. Other than getting the type() string and parsing myself, I'm unclear how I get this information out.

Likewise:

```
types:
  Foo: string | number
```

Foo is a UnionTypeDeclaration, how do I get the types this union is made from without parsing type() string again?

I'm assuming there is an easier way!?

**Comment by ddenisenko** [comment]
Depends on which level you operate. If that is JSON, you have no tools but to parse "type".
If that is AST level, you can call `runtimeType` level to get runtime types hierarchy and use it to analyze the types.

**Comment by domarmstrong** [comment]
So I'm using AST directly. Lets say I have an AST union type (number | string) node. Can you give me an example of exactly how I would find out that this is a string|number union. I could not seem to find out how to get this information.

**Comment by domarmstrong** [comment]
I'm still a bit stumped with this..

So
```
type:
  Foo: string
```
From this I get a nice StringTypeDeclaration which has minLength etc etc.

```
type:
  Foo: string | number
```
From this I get a UnionTypeDeclaration. And I cant get string | number information without diving into runtimeType which has a completely different and unfriendly api. I would then have to handle all of this completely differently!

Would it not make more sense to be able to:
```
type = ast.types()[0] (UnionTypeDeclaration)
left = type.left() (StringTypeDeclaration)
minLength = left.minLength();
```

**Comment by ddenisenko** [comment]
Its all depends on what information you want to get.
AST itself represents what user actually typed.
Runtime type model represents how what user typed can be interpreted.

Runtime types API may be not too convenient, but it simplifies the work with type hierarchies.

In example, for RAML:

```
#%RAML 1.0
title: test

types:
  TestValueType:
    type: string
    minLength: 5
  TestValueType2:
    type: TestValueType
    maxLength: 10
  TestUnionType:
    type: TestValueType2 | number
  TestUnionType2:
    type: TestUnionType
    facets:
      NewFacet: string
```

Following JS code:

```
    var types = api.types();
    var astTestUnionType2 = types.find(function(current){return current.name() == "TestUnionType2"});

    var runtimeTestUnionType2 = astTestUnionType2.runtimeType();

    if (runtimeTestUnionType2.hasUnionInHierarchy()){
        //there is union type
        var unionType = runtimeTestUnionType2.unionInHierarchy();
        console.log("Found union type in hierarchy of this type: "
            + unionType.nameId());

        var left = unionType.leftType();

        //the left type can be anything complex, but lets check that it is a value type
        if (left.isValueType()) {
            console.log("Found that left part of the union is valeu type: "
                + left.nameId())

            //this value type can have an arbitrary hierarchy,
            // but lets find out its ancestor builtin type
            var builtinAncestor = left.allSuperTypes().find(function(s){
                return s.isBuiltIn() && s.isValueType()
            })
            console.log("Our left value type is descending from: "
                + builtinAncestor.nameId())
        }

        //lets check, which facets we collected (fixed) along
        // the potentially long hierarchy of supertypes:
        var fixedFacets = left.getFixedFacets();
        for (fixedFacetName in fixedFacets) {
            console.log("Facet " + fixedFacetName + " : " + fixedFacets[fixedFacetName]);
        }
    }
```

Results in:

```
Found union type in hierarchy of this type: TestUnionType
Found that left part of the union is valeu type: TestValueType2
Our left value type is descending from: StringType
Facet maxLength : 10
Facet minLength : 5
```

Also please note that top-level AST layer may be deprecated in future, while JSON and high-level, including runtime types will remain unchanged.

**Comment by domarmstrong** [comment]
Thanks. This helped
