### ISSUE TITLE
Type and example objects are inconsistent?

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser-2#479]
```
#%RAML 1.0
title: Hello world # required title
version: 1
baseUri: http://example.com/{version}

/helloworld: # optional resource
  description: This is the top level description for /helloworld.

  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            type: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: # example how a response looks like
              {
                "message": "Hello world"
              }
  /test:
    displayName: TEST
    get:
      description: a sub resource
```

Now when I output the body of that 200 response (`obj.resources[0].methods[0].responses['200'].body['application/json']`) I am kind of surprised to find that the type is an array with the string `{\n  "title": "Hello world Response",\n  "type": "object",\n  "properties": {\n    "message": {\n      "type": "string"\n    }\n  }\n}\n` yet the example is an actual object `{ message: 'Hello world' }`.

Why isn't the type also an object, or the example also a string?

**Comment by sichvoge** [comment]
It's a very good question and there is a little `|` missing behind `example:`. So it should be `example: |` Look up the example again [here](https://github.com/raml-org/raml-examples/blob/master/helloworld/helloworld.raml). I changed that already. 

Still, a very valid question on how that gets parsed anyways. @ddenisenko any comments?

**Comment by kevinrenskers** [comment]
I know *your* example was changes, but was this is valid RAML and raml2html has to deal with it.. :) For my use case I am now simply using `structuredExample.value` which *is* always a string. Good workaround, but wondering why the parser works the way it does.

**Comment by ddenisenko** [comment]
Type is an array of strings because type is always an array of strings. Your type set as a strign was wrapped to an array.

Example is JSON object because by default we try to return examples in the structured (JSON) view, including conversion of JSON strings to JSON.
