### ISSUE TITLE
Parsing inexisting file could throw or return a "readable" error

### ISSUE THREAD

**Issue by ghlecl** [raml-org/raml-js-parser-2#49]
Sorry if this is not the place to "ask a question / make a suggestion" like that.

I have tried the following *really* useless code:
```
'use strict';
var raml = require( 'raml-1-0-parser' );
try
{
   var foo = raml.loadApi( './file-that-does-not-exists.file' );
   console.log( foo );
}
catch( e )
{
   console.log( e );
}
```
Although I realize the code is not realistic, the error (mistyping a file path) is.  I wanted to know what happens in this situation while trying to determine the error behavior of raml-js-parser-2 to use it in another project.

The result I have had is that `null` is returned in `foo` and printed to the console.  No error is thrown and nothing to indicate the source of the error.

If this is normal behavior, I would like to suggest that it should not be.  Wouldn't it be possible to throw an error saying that the file does not exist.

**Comment by ddenisenko** [comment]
Sounds very reasonable. Actually, it works like you want when you run asynchronous version of loadApi (those methods were renamed, and its asynchronous version is now called loadApi, while synchronous one is called loadApiSync) with "rejectOnErrors" option set to true.

Like this:

```js
var parseResult = raml.loadApi(fName9, {
    rejectOnErrors : true
})

parseResult.then(function (api) {

},function (theError) {
    console.log(theError)
})
```

the output is:

```
{ [Error: ENOENT: no such file or directory, open '/Users/munch/work/workspaces/ParserTest/test91.raml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/munch/work/workspaces/ParserTest/test91.raml' }
```

All in all, this is a bug in synchronous version of the method.

**Comment by petrochenko-pavel-a** [comment]
Hi @ghlecl. I changed behaviour of sync method to throw error when it can not resolve the path.
Fix is pushed to RC2.
Regards,
Pavel
