### ISSUE TITLE
Add RAML documentation to JSON schema

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#493]
As JSON schema of RAML output is becoming the main descriptor of how to use RAML parser, we need to add documentation from definition system and current top-level layer to JSON schema so users can see it directly and also to use JSON schema for documentation generation.

**Comment by ddenisenko** [comment]
Done.

**Comment by sichvoge** [comment]
Can we add more information on where we can find that?

**Comment by ddenisenko** [comment]
Here it is: https://github.com/raml-org/raml-js-parser-2/blob/schema/tckJsonSchema.json
