### ISSUE TITLE
Errors in extended files does not include tracing information

### ISSUE THREAD

**Issue by carowright** [raml-org/raml-js-parser-2#495]
I have the following files :
![screen shot 2016-10-04 at 9 51 54 am](https://cloud.githubusercontent.com/assets/13999213/19074785/4af778ec-8a18-11e6-80c5-5ffac20387da.png)

![screen shot 2016-10-04 at 9 53 32 am](https://cloud.githubusercontent.com/assets/13999213/19074810/71feefa6-8a18-11e6-8c80-7bce3beb5c30.png)

The first one has an error in line 6. The second one should have an error with tracing information in the line where the first file is extended, but insted the error is : 

```
{"code":2,
"message":"property: 'documentation' should be a sequence",
"path":"librarybooks.raml",
"range":{
  "start":{
    "line":5,
    "column":0,
    "position":125},
  "end":{
    "line":5,
    "column":13,
    "position":138}
    },
"isWarning":false}
```

**Comment by ddenisenko** [comment]
Fixed in hotfix-for-1.1.4-2 , will be released in 1.1.5
