### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by a2dude** [raml-org/raml-js-parser-2#499]
I installed the mulesoft raml tool into vs2015 from vs gallery, created an asp.net 5 webapi project and attempted to upload a pre-existing raml 0.8 definition.

This generated an exception in raml-1-0-parser reported in the dialog textbox and an alert from my av that the script contained a virus. The offending file has been deleted and I now get an exception stating the parser file is not found.

I went to npmjs and could not find raml-1-0-parser which seems curious.

Of course this could have been a pre-existing issue but my belief is that the offending file(s) arrived on my machine as a result of installing your product. Are you aware of any issues and can you offer any guidance?

**Comment by a2dude** [comment]
Cleaned machine and reinstalled. This virus issue was reproduced:

C:\Users\andy\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\bztayrjk.qkc\node_modules\raml-1-0-parser\node_modules\xmllint-hack2\xmllint.js;"Virus found XPL/Gen.K.90_30";"Unresolved";"Unresolved";"High"

**Comment by sichvoge** [comment]
As in https://github.com/mulesoft/api-workbench/issues/189#issuecomment-251686120 reported. It appears on Windows and AVG.

**Comment by sichvoge** [comment]
**Update**

It seems that the issue also appears with the original [xmllint module](https://www.npmjs.com/package/xmllint). See image below:

![image](https://cloud.githubusercontent.com/assets/498114/19121577/f4b9fa92-8b1e-11e6-8043-f68eef160586.png)

So its **not** the name or anything that we changed. We will further investigate the problem but I suggest to remove xmllint and therefore the XML validation completely from the build package until we found a proper solution. @ddenisenko any comments?

**Comment by ddenisenko** [comment]
This is certainly a false alarm case. Both the original library and the modified version were applied for AVG whitelisting, lets see if AVG can whitelist it fast.

**Comment by sichvoge** [comment]
**Update**

So we contacted AVG to add the original xmllint library into their whitelist.

**Comment by sichvoge** [comment]
It seems that AVG does not report the libs as malicious anymore. @a2dude can you double check please.

**Comment by ddenisenko** [comment]
This one is fixed, AVG virus database update required.
