### ISSUE TITLE
Status codes have strange prefix in generated JSON

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#5]
All status codes (200, 400, etc.) are prefixed with `__$EscapedKey$__` in the generated JSON. Why is that needed? Can it be removed?

Example:
```
var api = RAML.loadApi(apiPath).getOrElse(null);
var apiJSON = RAML.toJSON(api);
console.log(apiJSON);
```

Result (fragment):
```
"errorCodes": {
        "responses": {
          "__$EscapedKey$__400": {
            "description": "Bad Request.",
```

**Comment by ddenisenko** [comment]
This prefix is added as some versions of Nashorn under certain jdks have trooubles with digital JSON keys. We should remove the keys for general use cases.

**Comment by juancoen** [comment]
I agree, thanks!

**Comment by KonstantinSviridov** [comment]
Prefixes are no longer inserted by default
