### ISSUE TITLE
Improve error messages for 'example' validation

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#500]
This is a list of error messages that needs to be improved:

* `Required property: <property name> is missed` -> `missing required property '<property name>'`
* `Can not parse JSON example:Unexpected token d` -> `can not parse JSON example: Unexpected token d` (white space between `example:` and `Unexpected`
* `Unknown property:z` -> `Unknown property: 'z'`
* `value should be one of:aaa,bbb,3` -> `value should be one of: 'aaa', 'bbb', '3'`
* `array should have not less then 5 items` -> `array should not have less than 5 items`
* `object should have not less then 2 properties` -> `object should not have less than 2 properties` (especially here we should check if its 1 that ends with property, or more that ends with properties)
* in general: `... should be not less then ...` -> `... should not be less than ...`; also `more then` -> `more than`

In general, I can see a lot of error messages that have missing spaces between colon `:` and the actual error message like [here](https://github.com/raml-org/typesystem-ts/blob/d61a8b8ed4eade05fba6584e400ba58a1b6fd9c9/src/restrictions.ts#L57). Lets add some spaces. Also every node name should be enclosed in `'<property name>'` so that you can distinguish between the message and the name. Sometimes that is a bit hard. Same for values.

**Comment by KonstantinSviridov** [comment]
Most changes are implemented in fix for https://github.com/raml-org/raml-js-parser-2/issues/256
