### ISSUE TITLE
Reduce the number of AST layers

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#502]
Right now JS parser has the following layers, from bottom to top:
- YAML-level - pure YAML representation.
- Low-level - also YAML representation, hiding some of the details not needed by higher level layers, also handles include instructions.
- High-level - the tree, which nodes contain type information set up by definition (it knows, that this node is a method, and that node is a type). Each node has children and attributes, node has a link to its type, which set up the properties the node can have.
- Top-level - user-friendly representation of high-level layer: the nodes of this tree are named after their types (API, Resource, Method etc) and contain property-related methods, in example, API node has resources() method.
- JSON output - top-level layer, serialized to JSON with some transformations along the way.

All those levels are available for consumers.

It looks like the real consumers mostly use JSON output in case of more simple tools and high-level in case of more complicated tools.

Top-level was initially designed to be the layer and API to be used the most across the consumers, but it looks like the clients prefer to use JSON instead.

In order to make it easier the consumers, and also reduce parser size and complexity, we need to modify the API layers. This requires us to create the plan for the changes and ask existing users if the plan is suitable for their tools.

The following is the initial proposal:
- Top-level layer is removed altogether.
- JSON output is renamed to “high-level”.
- Current high-level and all of its sublayers are renamed to “low-level”, current low-level and yaml-level are hidden from consumers. The level is well-documented.
- Parser API is modified so that user gets either high-level or low-level on calling parsing method.

As a result, for the consumers, the whole layers sandwich is going to have only two levels:
- High-level JSON designed for more simple tools 
- Low-level layer designed for IDEs and more complex tools. 

This ticket hosts the discussion and should result in the final plan for the changes affect 2.0 version of the parser.

**Comment by ddenisenko** [comment]
https://github.com/raml-org/raml-js-parser-2/issues/494 is related

**Comment by eduramiba** [comment]
Will we still be able to programmatically navigate resources, methods, responses... and perform validation on types (response body for example) with arbitrary data? This is useful for a REST service validator.

Thanks

**Comment by ddenisenko** [comment]
You will be able to programmatically navigate nodes both using JSON layer and current high-level layer (to be renamed to low-level).
Types validation will be still available via typesystem as it is now.

**Comment by eduramiba** [comment]
Awesome, thanks!

**Comment by sichvoge** [comment]
@ddenisenko can you explain what the parser API will look like and maybe some examples on how people will use it in the future?

**Comment by ddenisenko** [comment]
@sichvoge 

Stage 1: will happen soon.

At this stage we do not remove anything, just add a part of the new interface, which is designed to be simple and require as less user actions/parameters as possible.

Here, the proposal is to add two methods:

`load(ramlPath: string, options?: Options): Promise<JSON>`
The method accepts RAML path and a map of options with a single boolean property `expandLibraries`. Not sure what should be the default.

This method will perform all validations, expansions etc inside and result in a promise with the final JSON: the one, which users get now after performing all steps manually and calling `toJSON`.

The second method is its sync version working in the same way:
`loadSync(ramlPath: string, options?: Options): JSON`

Stage 2: will happen at some point in future
At this stage we will remove the current top level layer entirely. Existing users of top-level layer will be able to use the new interface for quite some time, so they have chance to provide us with a feedback of what is missing in JSON for them to rely on it.

I guess, some of the users will miss an ability to access runtime types, so we will have to add IDs to the type instances in JSON and add a standalone method to get runtime type from such an ID.

**Comment by sichvoge** [comment]
Can you highlight the different options please? For `expandLibraries`, is it necessary to have that option? If there is a justifiable reason and we have that, I would default it to `true`.

**Comment by sichvoge** [comment]
Also, does `load` respond either with an 0.8 or 1.0 JSON? Are those different JSON's? Should we start to build a consistent JSON for that new method so that we don't have to change it after people adapted the `load` method? IMHO, it would make sense to improve the JSON and let `load` respond with that. People that still use the old methods `api.expand().toJSON()` still have the old JSON just to keep some backwards capabilities and give them time to adapt the new. We should still indicate that the old method is `deprecated` in our documentation. 

Another questions where I'd like to have more input: should the load method only care about root RAML files (including overlays & extensions)? It would make a lot of things easier for the final schema. People who want to parse a fragment could still do it with the `parse` method right?!

**Comment by ddenisenko** [comment]
>an you highlight the different options please? For expandLibraries, is it necessary to have that option? If there is a justifiable reason and we have that, I would default it to true.

For now, `expandLibraries` is the only one. We could just have it as a parameter, but lets make some space for potential future use cases.
Regarding whether we need this option at all, or not - I'd rather have it, even if it's true by default. Limiting users to a view on the data, which is the most distant from the original of all views that we have may prove to be inconvenient.

>Also, does load respond either with an 0.8 or 1.0 JSON? Are those different JSON's?

load responds with exactly the same JSON, you would get by calling `toJSON` right now. We essentially skip several operations, we do not change anything in the output for now.

>Are those different JSON's?
Right now there are differences in those JSONs, which are covered by the schema.

>hould we start to build a consistent JSON for that new method so that we don't have to change it after people adapted the load method?
>People that still use the old methods api.expand().toJSON() still have the old JSON just to keep some backwards capabilities and give them time to adapt the new.

These are two different operations: providing a new way to obtain the JSON, and improving the JSON.

I would not mix those two: lets make the new interface first, whcih provides exactly the same JSON as the current interface so that we can test this interface against current TCK, then start improving it. Whether we should only improve the JSON, which is an output of the new interface and leave old interface having the old JSON format - not sure.

**Comment by KonstantinSviridov** [comment]
see https://github.com/raml-org/raml-js-parser-2/pull/556
