### ISSUE TITLE
high-level should be documented better

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#503]
As high-level will be probably getting more usage in 2.0 version, we need to improve its documentation.

**Comment by KonstantinSviridov** [comment]
[The tutorial](https://github.com/raml-org/raml-js-parser-2/blob/highlevel-documentation/examples/highlevel-AST-usage/tutorial.md)
[Example JS script](https://github.com/raml-org/raml-js-parser-2/blob/highlevel-documentation/examples/highlevel-AST-usage/script.js)
