### ISSUE TITLE
Error externalization and numbering

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#505]
Currently error messages are built in to the validation code. Instead, such messages will be extracted to a separate file, each error will be granted with unique ID number.

This will provide us with an ability to easily change error messages without digging through the code. This will also provide us with an ability to easier translate messages to other languages, if needed.

An additional benefit if using error IDs instead of error messages is that non-JS parsers (namely, Java parser) may have its own set of error messages, but we can still compare errors to each other.

**Comment by KonstantinSviridov** [comment]
Use the following branches:
https://github.com/raml-org/raml-js-parser-2/tree/messages-externalization
https://github.com/raml-org/typesystem-ts/tree/messages-externalization
