### ISSUE TITLE
Introduce validation plugins

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#506]
This is an epic which groups up the tickets regarding validation plugins. More detailed tickets list will be added later.

**Comment by KonstantinSviridov** [comment]
Initial results are
https://github.com/raml-org/typesystem-ts/pull/85/files
https://github.com/raml-org/raml-js-parser-2/pull/527/files

**Comment by KonstantinSviridov** [comment]
[Here](https://github.com/raml-org/raml-js-parser-2/tree/validation-plugins/examples/validationPlugins) is an example of the plugins usage. After executing `npm run buildall` transit to the example directory and run `node script.js`.

Four kinds of plugins are supported:

1. AST node validator. Should implement [`INodeValidationPlugin`](https://github.com/raml-org/raml-js-parser-2/blob/validation-plugins/src/raml1/highLevelAST.ts#L470-L483). [Example](https://github.com/raml-org/raml-js-parser-2/blob/validation-plugins/examples/validationPlugins/plugins/resourceUriValidationPlugin.js)

2. AST node annotations validator. Should implement [`ASTAnnotationValidationPlugin `](https://github.com/raml-org/raml-js-parser-2/blob/validation-plugins/src/raml1/highLevelAST.ts#L518-L530). [Example](https://github.com/raml-org/raml-js-parser-2/blob/validation-plugins/examples/validationPlugins/plugins/crudAnnotationsValidator.js)

3. Types validator. Should implement [`ITypeValidationPlugin`](https://github.com/raml-org/typesystem-ts/blob/validation-plugins/src/typesystem-interfaces.ts#L357-L369). [Example](https://github.com/raml-org/raml-js-parser-2/blob/validation-plugins/examples/validationPlugins/plugins/uninheritedTypesDetector.js)

4. Typesystem annotations validator. Should implement [`IAnnotationValidationPlugin`](https://github.com/raml-org/typesystem-ts/blob/validation-plugins/src/typesystem-interfaces.ts#L418-L430). [Example](https://github.com/raml-org/raml-js-parser-2/blob/validation-plugins/examples/validationPlugins/plugins/xmlAnnotationsValidator.js)

Plugins of each kind should be registered in a certain property of the `ramlValidation` global variable (see examples for details).
