### ISSUE TITLE
Replacing error messages with IDs in TCK

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#510]
After https://github.com/raml-org/raml-js-parser-2/issues/505 is implemented, TCK suite and contents should be migrated to use error IDs instead of error messages.

**Comment by KonstantinSviridov** [comment]
The result of setting IDs and removing messages is located in the following branch:
https://github.com/mulesoft-labs/raml-tck/tree/error-codes

In my opinion, removing messages makes it harder to understand what particular test is about. Think we should preserve the messages but ignore them in JSON comparison.  @ddenisenko , what do you think?
