### ISSUE TITLE
Spike on the parser performance

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#512]
The parser gets significant slower having a big RAML document, or a RAML definition splitted into several fragments.

This epic groups up parser performance improvements.

After the investigation, additional tickets regarding the concrete enhancements should be added here.

**Comment by ddenisenko** [comment]
- [ ] []()
- [ ] []()

**Comment by postatum** [comment]
Closing for now as no answers. Feel free re-open if this is still relevant.
