### ISSUE TITLE
No errors from extended files

### ISSUE THREAD

**Issue by carowright** [raml-org/raml-js-parser-2#513]
The root file has an error in line 4, so there should be an error in the extension file that extends it.

![screen shot 2016-10-06 at 10 34 39 am](https://cloud.githubusercontent.com/assets/13999213/19154358/934bb2cc-8bb0-11e6-8e37-ec1845b6693f.png)

![screen shot 2016-10-06 at 10 34 49 am](https://cloud.githubusercontent.com/assets/13999213/19154365/989908c4-8bb0-11e6-9b1c-ba098d363597.png)

The parsed extension file does not include any error nor warning

**Comment by ddenisenko** [comment]
Reproducible, thank you.

**Comment by ddenisenko** [comment]
Fixed. Fix will be published in 1.1.5.

**Comment by ddenisenko** [comment]
While generally the errors are propagated, the missing title is not.
