### ISSUE TITLE
Autovalidating examples by schemas is not work

### ISSUE THREAD

**Issue by galk-in** [raml-org/raml-js-parser-2#520]
On 1.1.4 and 1.1.5 the parser doesn't check body examples by schemas. File:
```
#%RAML 0.8
---
title: Test
/customers:
  get:
    responses:
      200:
        body:
          application/json:
            schema:  |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "id": "customer",
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "surname": {
                    "type": "string"
                  }
                }
              }
            example:  |
              {
                "firstName": true,
                "surname": "Smith"
              }
```

On 1.1.3 version parser.loadApiSync(<file>).errors():
``` js
[ { code: 7,
    message: 'Example does not conform to schema:Content is not valid according to schema:Expected type string but found type boolean string,boolean',
    path: <file>,
    range: { start: [Object], end: [Object] },
    isWarning: true } ]
```

On 1.1.4 and 1.1.5 parser.loadApiSync(<file>).errors() is [].

**Comment by galk-in** [comment]
@ddenisenko, @KonstantinSviridov,  hello, guys.
If you do not complicate, please confirm this bug.
Maybe, you simply removed this feature.

**Comment by ddenisenko** [comment]
XML validation was extracted to a separate plugin. Please make sure you do include XML validation into your package. Same for JSON validation.

Please read release comments of builds https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.2 and https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.4

Let me know if you do include the plugin and still have troubles with the validation.

**Comment by galk-in** [comment]
Thank you! It's my fault, I did not read the release notes.
