### ISSUE TITLE
Browser version after minification fails with syntax error

### ISSUE THREAD

**Issue by tscislo** [raml-org/raml-js-parser-2#524]
Browser version is not minified when using npm run generateBrowserVersion, when I forced minification it trowed me some exceptions when I was trying to use the output browser version. It was some error with some regexp.

**Comment by tscislo** [comment]
Any resons why this was closed without any resolution?

**Comment by ddenisenko** [comment]
Missed the comment for this one. Browser version of the  parser is being delivered with all 3 parts of it minified. You can find it attached here: https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.8

Same minified version is going to be delivered as a bower packages as soon as this one is implemented: https://github.com/raml-org/raml-js-parser-2/issues/521

**Comment by tscislo** [comment]
Can you provide it as an npm package instead? No one is really useing bower anymore. I posted my comment in #521 Thanks!
