### ISSUE TITLE
There is an issue with scalar annotations

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#532]
@KonstantinSviridov please provide an examples.

**Comment by KonstantinSviridov** [comment]
Annotations on scalar properties of types are not comprehanded by the validator. 

For example,
![sannotations](https://cloud.githubusercontent.com/assets/6206034/19971678/4e2b76b4-a212-11e6-9440-626c9a77cb6d.png)

Should be
![sannotations2](https://cloud.githubusercontent.com/assets/6206034/19971805/b981e10a-a212-11e6-99df-d0e7dbf8387a.png)


See [annotating scalar valued nodes](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#annotating-scalar-valued-nodes) for details.
