### ISSUE TITLE
Unexpected console output "null"

### ISSUE THREAD

**Issue by baoti** [raml-org/raml-js-parser-2#535]
When I use [raml2html](https://github.com/raml2html/raml2html) to generate html from raml, output is:

```
null
<!DOCTYPE HTML>
<html>
...
</html>
```

The first line "null" comes from [jsyaml2lowLevel.ts#L2199](https://github.com/raml-org/raml-js-parser-2/blob/557a17e922717cc630bd6f21b3c0127893bbdedf/src/raml1/jsyaml/jsyaml2lowLevel.ts#L2199)

I had submitted a PR #442 before.

**Comment by KonstantinSviridov** [comment]
Thanks, @baoti 

Th PR is merged
