### ISSUE TITLE
We need to deliver browser versions as npm packages

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#537]
The npm part of https://github.com/raml-org/raml-js-parser-2/issues/521

**Comment by dreamflyer** [comment]
will be published in v1.1.9.

**Comment by tscislo** [comment]
It would be enough to have a compiled js file as AMD module with appropriate reference in package.json (main section). Thanks!

**Comment by dreamflyer** [comment]
@tscislo available npm modules are: raml-1-parser-browser, raml-json-validation-browser, raml-xml-validation-browser.

**Comment by tscislo** [comment]
@dreamflyer thanks! Do I need to install all 3 modules to use RAML to JSON parsing or is it just enough to install raml-1-parser-browser?
