### ISSUE TITLE
There's a bunch of module paths in the code

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-js-parser-2#54]
```
"modulePath": "c:\\GIT-repos\\api-workbench\\src\\raml1\\spec-1.0\\api.ts"
```

**Comment by sichvoge** [comment]
Looking for that again I actually can't find it anymore. Guess that has been obsolete since exposing the actual source code. Closing it for now. If anyone still sees that, please feel free to open the issue again.
