### ISSUE TITLE
Huge node module because of documentation

### ISSUE THREAD

**Issue by thomaschaaf** [raml-org/raml-js-parser-2#554]
I am using you project and I find it very helpful. Sadly your package is our biggest package with almost 50 MB. 

```
5,5M	node_modules/raml-1-parser//dist
 37M	node_modules/raml-1-parser//documentation
2,8M	node_modules/raml-1-parser//examples
216K	node_modules/raml-1-parser//node_modules
 16K	node_modules/raml-1-parser//resources
 32K	node_modules/raml-1-parser//test
 12K	node_modules/raml-1-parser//web-tools
 46M	node_modules/raml-1-parser/
```

Would it be possible to remove the documentation before publishing the module? I think it is helpful in the git repository but not in the npm package.

**Comment by ddenisenko** [comment]
Sounds reasonable. We'll see how we can reduce the size.

**Comment by thomaschaaf** [comment]
🎉🎊
