### ISSUE TITLE
Post method body no functions.

### ISSUE THREAD

**Issue by joanvila** [raml-org/raml-js-parser-2#558]
Hi!

I have the following resource definition:

```
/task:
    post:
        description: |
            Creates a task
        body:
            application/x-www-form-urlencoded:
                properties:
                    name:
                        description: Nam of the task
                        type: string
                        example: Code things
                    owner:
                        description: Who's going to do it
                        type: string
                        example: Joan
        responses:
            200:
```

And I want to get the name and the owner example variables. However, I cannot access inside the body.

The fact is that if I try to do `method.toJSON()` I get the expected result:

```
{ responses: { '200': { code: '200' } },
  body:
   { 'application/x-www-form-urlencoded':
      { name: 'application/x-www-form-urlencoded',
        displayName: 'application/x-www-form-urlencoded',
        type: [Object],
        required: true,
        properties: [Object],
        __METADATA__: [Object] } },
  protocols: [ 'HTTP' ],
  description: 'Creates a task\n',
  method: 'post',
  __METADATA__: { primitiveValuesMeta: { protocols: [Object] } } }
```

But when I try to access any properties of the body, for example `method.body().toJSON()` I get this error:
```
TypeError: method.body(...).toJSON is not a function
```

I'm not sure if this is an issue or an error on my side.
Do you have any thoughts on this?

Thank you 🙂

**Comment by ddenisenko** [comment]
As per https://raml-org.github.io/raml-js-parser-2/interfaces/_src_raml1_artifacts_raml10parserapi_.method.html#body body is an array of types. So to invoke toJSON you first need to iterate it.

Please note that top-level layer that you are calling `toJSON()` method for is probably going to be deprecated, instead JSON and high-level will remain. Please try using `api.toJSON()` call results as a primary source of data. If you are missing something in the current JSON, let us know in https://github.com/raml-org/raml-js-parser-2/issues/502 ticket.

**Comment by joanvila** [comment]
Sorry for not seeing that @ddenisenko. And thanks for the deprecation notice. In fact, I try to avoid the `toJSON()` call and use the specific getters instead.

Thanks for your help!
