### ISSUE TITLE
Parser `toJSON()` method sets `"required": true` on types

### ISSUE THREAD

**Issue by jstoiko** [raml-org/raml-js-parser-2#560]
given the RAML file below:
```raml
#%RAML 1.0
title: Person API

types:
  Address:
    type: object
    properties:
      street:
        type: string
  Person:
    type: object
    properties:
      home_address:
        type: Address
      work_address:
        type: Address
        required: false

/humans:
  post:
    body:
      application/json:
        type: Person

```

and the following snippet:
```js
require('raml-1-parser')
    .loadRAML(file, { rejectOnErrors: true })
    .then(function (ramlApi) {
      var raml = ramlApi.expand(true).toJSON({
        serializeMetadata: false
      })
      console.log(JSON.stringify(raml, null, 2))
}
```

`raml` will output:
```json
{
  "types": [
    {
      "Address": {
        "name": "Address",
        "displayName": "Address",
        "type": [
          "object"
        ],
        "required": true,
        "properties": {
          "street": {
            "name": "street",
            "displayName": "street",
            "type": [
              "string"
            ],
            "required": true
          }
        }
      }
    },
    {
      "Person": {
        "name": "Person",
        "displayName": "Person",
        "type": [
          "object"
        ],
        "required": true,
        "properties": {
          "home_address": {
            "name": "home_address",
            "displayName": "home_address",
            "type": [
              "Address"
            ],
            "required": true
          },
          "work_address": {
            "name": "work_address",
            "displayName": "work_address",
            "type": [
              "Address"
            ],
            "required": false
          }
        }
      }
    }
  ],
  "title": "Person API",
  "resources": [
    {
      "methods": [
        {
          "body": {
            "application/json": {
              "name": "application/json",
              "displayName": "application/json",
              "type": [
                "Person"
              ],
              "required": true
            }
          },
          "method": "post"
        }
      ],
      "relativeUri": "/humans",
      "displayName": "/humans",
      "relativeUriPathSegments": [
        "humans"
      ]
    }
  ]
}
```

The issue is that the type `Address` has had `"required": true` set by the parser and as a result, any properties that would try to inherit from it, e.g. `Person.work_address` will not be able to (see [this](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#object-type-specialization)).

**Comment by ddenisenko** [comment]
Not sure I understand the issue.

Parser eats the example with no errors, the output contains `"required": false` for `Person.work_address` property. So the inheritance works. 

`required:true` in top-level types is really just an artifact with no big meaning.

**Comment by jstoiko** [comment]
The issue is that if a type has `required:true`, anything that inherits from it must have `required:true` as well because as the [RAML 1.0 specs state](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#object-type-specialization): `A sub-type can override properties of its parent type with the following restrictions: 1) a required property in the parent type cannot be changed to optional in the sub-type, and 2) the type declaration of a defined property in the parent type can only be changed to a narrower type (a specialization of the parent type) in the sub-type.`

The parser does not throw any error but other tools that depend on it will if they follow that part of the RAML 1.0 specs. @petrochenko-pavel-a might be able to shed some light on the issue.

**Comment by ddenisenko** [comment]
Which, exactly, property had `required:true` and got `required:false` in your example to make it against the spec?

**Comment by jstoiko** [comment]
the output of `toJSON()` above sets `required:true` on `types.Address` which would prevent the property `work_address` of `types.Person` from inheriting from `types.Address` because `work_address` has `required:false`

**Comment by ddenisenko** [comment]
I do not agree with this spec interpretation. `required: true` in question is set for the type `Address` itself, not for one of its properties. 

Spec in this paragraph regulates the changes of `required` for the properties in subclasses.

Example:

This works:
```
types:
  Address:
    type: object
    properties:
      street:
        type: string
        required: true
  Person:
    type: object
    properties:
      home_address:
        type: Address
      work_address:
        type: Address
        properties:
          street:
            type: string
            required: true
```

And this does not:

```
types:
  Address:
    type: object
    properties:
      street:
        type: string
        required: true
  Person:
    type: object
    properties:
      home_address:
        type: Address
      work_address:
        type: Address
        properties:
          street:
            type: string
            required: false
```

Notice `required` changed to false in the `street` property of `work_address` property of `Person` type.

I understand that this `required` in top-level type makes it more difficult for you to analyze types. We can consider removing it from top-level types. 

For now you can use `__METADATA__` to find out where attribute is originating from, in other words you can determine whether an attribute does actually exist in RAML code, or is added by the parser.

In your example, JSON with metadata turned on is the following:
```
        "Address": {
          "name": "Address",
          "displayName": "Address",
          "type": [
            "object"
          ],
          "required": true,
          "properties": {
            "street": {
              "name": "street",
              "displayName": "street",
              "type": [
                "string"
              ],
              "required": true,
              "__METADATA__": {
                "primitiveValuesMeta": {
                  "displayName": {
                    "calculated": true
                  }
                }
              }
            }
          },
          "__METADATA__": {
            "primitiveValuesMeta": {
              "displayName": {
                "calculated": true
              },
              "required": {
                "insertedAsDefault": true
              }
            }
          }
        }
      },
```

As you can see, metadata of `Address` itself has 
```
              "required": {
                "insertedAsDefault": true
              }
```
while same metadata of `street` does not. `insertedAsDefault` and `calculated` are two keywords  indicating there is no such attribute in the original code.

Turning metadata info on sample:
```
api.toJSON({serializeMetadata: true})
```

**Comment by jstoiko** [comment]
> Spec in this paragraph regulates the changes of required for the properties in subclasses.

You're right. The specs talk about `required` for the properties of a type. It does not mention that a type could have `required` set, nor that it says that it shouldn't. However, given that the specs don't talk about it, I extrapolated and concluded that if `required: true` is set on a type, then any property inheriting from that type would not be able to inherit from it if that property had `required:false`.

> I understand that this required in top-level type makes it more difficult for you to analyze types. We can consider removing it from top-level types.

Yeah, I would consider removing it. Unless there is a really good reason for it to be there.

**Comment by ddenisenko** [comment]
>However, given that the specs don't talk about it, I extrapolated and concluded that if required: true is set on a type, then any property attempting to inherit from that type would not be able to do so if such property had required:false.

As I said, `required` appearing in the top-level types is just a side-effect, nothing really intentional. Spec never suspected this can happen :)

**Comment by petrochenko-pavel-a** [comment]
Hi Denis,
>I do not agree with this spec interpretation. required: true in question is set for the type Address itself, not >for one of its properties.

As for me this is clearly an issue in the parser, I do not see how type itself may be required.

Regards,
Pavel
