### ISSUE TITLE
Improve JSON Schema output from the parser

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#562]
We've got a lot of very good feedback about the current JSON object that comes back from the parser. Most predominantly, the output should be more consistent. 

This issue describes the different changes we'd like to make. Please feel free to help and discuss in this matter.

**Improvements**

| Schema Field | Current Type | Change |RAML version|
|:---------------|:---------------|:---------------|:----|  
| `mediaType` | Its either a `string` or an `array` | Only `array` |1.0|
| `types` | An `array` of single key objects | `map` |1.0|
| `traits` | An `array` of single key objects | `map` |1.0, 0.8|
| `resourceTypes` | An `array` of single key objects | `map` |1.0, 0.8|
| `annotationTypes` | An `array` of single key objects | `map` |1.0|
| `securitySchemes` | An `array` of single key objects | `map` |1.0, 0.8|
| `schemas` | Is serialized under the `schemas` key | serialize under the `types` key|1.0|
|`schema`| Is serialized under the `schema` key | serialize under the `type` key|1.0|
|`example` | Is serialized under the `example` key | serialize as one element array under the `examples` key|1.0|
|`value` (ExampleSpec) | string representation of example | actual example value: `string`, `object`, `array`, 'number', `boolean` or `null`|1.0|

**New**

| Field | Type | Description | RAML version |
|:---------------|:---------------|:--------------|:---------------|
| `completeRelativeUri`| `string` | Resource URI relative to Api root.  Adding it to any resource as a `string` value.| 1.0, 0.8 |
| `parentUrl` | `string` | For a nested resource it's the complete relative URI of its parent. For a top level resource it's an empty string. Adding it to any resource as a `string` value. | 1.0, 0.8 |
| `allUriParameters` | `array` | A union of URI parameters sets of the resource itself with URI parameters sets of all the resources which contain the resource. Adding it to any resource as an optional `array`.| 1.0, 0.8 |
| `allUriParameters`| `array` | `allUriParameters` value of the owning resource. Adding it to any method as an optional `array`.| 1.0, 0.8 |
| `mediaType` (for Type)| `string` | States the way of type definition: `application/json` or `application/xml` for external types and `application/raml+yaml` for the rest| 1.0 |

**Remove**
* `structuredExample`
* `structuredValue` (ExampleSpec)

**Comment by KonstantinSviridov** [comment]
Descriptions for the fields to be introduced.

| Field | Description|
|:---------------|:--------------| 
|`completeRelativeUri`| Resource URI relative to Api root.  Adding it to any resource as a `string` value.|
| `parentUrl` | For a nested resource it's the complete relative URI of its parent. For a top level resource it's an empty string. Adding it to any resource as a `string` value. |
| `allUriParameters` | A union of URI parameters sets of the resource itself with URI parameters sets of all the resources which contain the resource. Adding it to any resource as an optional `map`.|
| `allUriParameters`| `allUriParameters` value of the owning resource. Adding it to any method as an optional `map`.|

**Comment by sichvoge** [comment]
QQ: Should we also handle and transform all type expressions and give a simple to read and consistent output? I know that parsing things like `[Cow, Cat | Dog]` might be easy, but the logic to parse them to get a more appropriate format seems to be replicated on clients.

**Comment by sichvoge** [comment]
@KonstantinSviridov can you guys investigate if there are other nodes that can be expressed differently like:

```yaml
type: Dog[] 
```

```yaml
type: array
items: Dog
```

-----------

```yaml
mediaType: application/json
```

```yaml
mediaType: [ application / json ]
```

**Comment by sichvoge** [comment]
Others are

```yaml
types:
  test:
    type: object
    properties:
      name: string
    example:
      value: !include examples/actionsRead.json
```

```yaml
types:
  test:
    type: object
    properties:
      name: string
    example: !include examples/actionsRead.json
```

**Comment by sichvoge** [comment]
I'd also suggest to introduce a `mediaType` tag for types / schemas that clearly identifies the value type for a type value. For example:

```json
{
  "type": {
    "mediaType": "application/raml+yaml"
    "content": {
      "type": "array",
      "items": "Dog"
    }
  }
}
```

**Comment by KonstantinSviridov** [comment]
@sichvoge 

Why would we put actual type definition into the "content" field. May be let's just introduce an additional "mediaType" field:
```
    "types": {
      "Account": {
        "name": "Account",
        "displayName": "Account",
        "mediaType": "application/xml",
        "type": [
          "<xs:schema attributeFormDefault=\"unqualified\" elementFormDefault=\"qualified\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">\n    <xs:element name=\"TwilioResponse\">\n        <xs:complexType>\n            <xs:sequence>\n                <xs:element name=\"Account\">\n                    <xs:complexType>\n                        <xs:sequence>\n                            <xs:element type=\"xs:string\" name=\"Sid\"/>\n                            <xs:element type=\"xs:string\" name=\"FriendlyName\"/>\n                            <xs:element type=\"xs:string\" name=\"Type\"/>\n                            <xs:element type=\"xs:string\" name=\"Status\"/>\n                            <xs:element type=\"xs:string\" name=\"DateCreated\"/>\n                            <xs:element type=\"xs:string\" name=\"DateUpdated\"/>\n                            <xs:element type=\"xs:string\" name=\"AuthToken\"/>\n                            <xs:element type=\"xs:string\" name=\"Uri\"/>\n                            <xs:element name=\"SubresourceUris\">\n                                <xs:complexType>\n                                    <xs:sequence>\n                                        <xs:element type=\"xs:string\" name=\"AvailablePhoneNumbers\"/>\n                                        <xs:element type=\"xs:string\" name=\"Calls\"/>\n                                        <xs:element type=\"xs:string\" name=\"Conferences\"/>\n                                        <xs:element type=\"xs:string\" name=\"IncomingPhoneNumbers\"/>\n                                        <xs:element type=\"xs:string\" name=\"Notifications\"/>\n                                        <xs:element type=\"xs:string\" name=\"OutgoingCallerIds\"/>\n                                        <xs:element type=\"xs:string\" name=\"Recordings\"/>\n                                        <xs:element type=\"xs:string\" name=\"Sandbox\"/>\n                                        <xs:element type=\"xs:string\" name=\"SMSMessages\"/>\n                                        <xs:element type=\"xs:string\" name=\"Transcriptions\"/>\n                                    </xs:sequence>\n                                </xs:complexType>\n                            </xs:element>\n                        </xs:sequence>\n                    </xs:complexType>\n                </xs:element>\n            </xs:sequence>\n        </xs:complexType>\n    </xs:element>\n</xs:schema>"
        ]
      },
      "SomeType": {
        "name": "SomeType",
        "displayName": "SomeType",
		"mediaType": "application/raml+yaml",
        "type": [
          "object"
        ],
        "properties": {
          "name": {
            "name": "name",
            "displayName": "name",
            "type": [
              "string"
            ]
          }
        },
        "examples": [
          {
            "value": "{\n  \"name\": \"somestring\"\n}",
            "strict": true,
            "name": null,
            "structuredValue": {
              "name": "somestring"
            }
          }
        ]
      }
    },
```

**Comment by sichvoge** [comment]
Looks ok for me too :) BTW, looking at your example:

```
"examples": [
  {
    "value": "{\n  \"name\": \"somestring\"\n}",
    "strict": true,
    "name": null,
    "structuredValue": {
      "name": "somestring"
    }
  }
]
```

Whats the difference between `value` and `structuredValue`?

**Comment by KonstantinSviridov** [comment]
As for exmaple, everything is going to be fine, because we're going to serialize an erray of ExampleSpec objects which look exactly the same disregarding whether one uses
Others are

```yaml
    example:
      value: !include examples/actionsRead.json
```
or
```yaml
    example: !include examples/actionsRead.json
```

**Comment by KonstantinSviridov** [comment]
I've realized that we can not use maps for `allUriParameters` as we can come across several resources utilizing parameters with same names:
```
/res1{id}:
  /res2{id}:
```
Thus, we have to use arrays here.

**Comment by KonstantinSviridov** [comment]
@sichvoge 
|Whats the difference between value and structuredValue?
`value` is a string representation
`structuredValue` is what has actually been specified: number, string, boolean or object

**Comment by KonstantinSviridov** [comment]
As for `TypeDeclaration.type` property, I propose the following schema for it:
```json
{
  "type" : "array",
  "items": {
     "oneOf": [
        { "type": "string", "description": "type name" },
        { "ref": "#path/to/TypeDeclaration/definition" },
     ]
  }
}
```
Thus, in case of an inline type
```yaml
types:
  T1:
    type:
      properties:
        p1:
```
we'll have
```json
"types": [
      {
        "T1": {
          "type": [
            {
              "type": [
                 "object"
              ],
              "properties": {
                "p1": {
                  "type": [
                    "string"
                  ]
                }
			  }
            }
          ]
        }
      }
    ]
```

At the same time, `type: [Cow, Cat | Dog]` could be serialized to
```json
"type": [
  "Cow",
  {
    "type": "union",
    "components": [ "Cat", "Dog" ]
  }
]
```
, where `components` has the same type as `TypeDeclaration.type`

**Comment by sichvoge** [comment]
With regards to the string `value`: Do we really need that? Isn't it very easy for the client to stringify the structured output?

**Comment by sichvoge** [comment]
With regards to union. We actually already have a certain format for that https://github.com/raml-org/raml-spec/pull/541. We just haven't had much time to merge it yet, but the output could already follow that model. So `Cat | Dog` can be represented also as:

```yaml
type: union
anyOf: [ Cat, Dog ]
```

**Comment by KonstantinSviridov** [comment]
Ok, it seems that we do not need a separate field for string value. Lets remove `value` and then rename `structuredValue` to `value`.

As for union types format, lets use `anyOf` then. For my example
```
type: [Cow, Cat | Dog]
```
we will have
```
"type": [
  "Cow",
  {
    "type": "union",
    "anyOf": [ "Cat", "Dog" ]
  }
]
```

**Comment by KonstantinSviridov** [comment]
Note that `UnionTypeDeclaration.anyOf` is likely to have just the same type as `TypeDeclaration.type`

**Comment by KonstantinSviridov** [comment]
@sichvoge 
As for those type objects, which are obtained by expressions parsing, I propose `text/plain` as their mediaType. For exmaple:
```
type: [Cow, Cat | Dog]
```
will be
```
{
  "type": [
    "Cow",
    {
      "type": "union",
      "anyOf": [ "Cat", "Dog" ],
      "mediaType" : "text/plain"
    }
  ],
  "mediaType" : "application/raml+yaml"
  
}
```

**Comment by KonstantinSviridov** [comment]
The listed changes are implemented in https://github.com/raml-org/raml-js-parser-2/pull/570

**Comment by sichvoge** [comment]
Thanks @KonstantinSviridov. Can you please add what we discussed about `structuredValue` and `value`? Lets forget about the type expression resolving for now.

**Comment by KonstantinSviridov** [comment]
@sichvoge Thanks for reminding about `value` and `structuredValue`

.Actually, I've already implemented type expressions resolving. Should I remove it?

**Comment by KonstantinSviridov** [comment]
For example,
https://github.com/raml-org/raml-js-parser-2/blob/tck-schema-changes/src/raml1/test/data/TCK/raml-1.0/Types/Type%20Expressions/test008/api.raml#L19

becomes

https://github.com/raml-org/raml-js-parser-2/blob/tck-schema-changes/src/raml1/test/data/TCK/raml-1.0/Types/Type%20Expressions/test008/api-tck.json#L136-L148

**Comment by sichvoge** [comment]
> Actually, I've already implemented type expressions resolving. Should I remove it?

Yes please remove it again. Only the items that has been put into the OP (first comment) has been agreed on.

**Comment by ddenisenko** [comment]
I guess this one can be closed. Please reopen if there are still matters to discuss.
