### ISSUE TITLE
Create .md description for the new API

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#564]

**Comment by ddenisenko** [comment]
Here is the description: https://github.com/raml-org/raml-js-parser-2/blob/tck-schema-changes/documentation/TheNewApi.md . Please comment what can be improved.

**Comment by ddenisenko** [comment]
@sichvoge 👆

**Comment by sichvoge** [comment]
Thanks Denis for your effort putting that together. That will definitely help people to understand the differences between whats new vs whats already there. 

Additionally to that information, can we also compile an MD file that explains the API in general? I can compile some initial structure on how that should look like for you as a blueprint.

**Comment by sichvoge** [comment]
The current documentation also includes internal function etc. So I wonder if it is not better for us to build and maintain a simple MD file for the API documentation, or continue to compile the documentation from code.

If the latter, lets make sure only the necessary things are in there. At least, could change the MD file with the new API so that you include the complete top level API? For example:

---------------

## RAML Parser API

### Parsing Functions

_There are dedicated functions for executing below functions synchronously (function name + `Sync`) or asynchronously. For example, `load` is an asynchronous function and returns a promise where as `loadSync` is synchronous. The below list only covers the asynchronous functions since the main purpose is exactly the same._

- `load(path, [options])`
- `loadRAML(path, [extensionsAndOverlays], [options])`
- `loadApi(path, [extensionsAndOverlays], [options])`
- `parseRAML(content, [options])`

#### `load(path, [options])`

Loads the given RAML document and returns it as a single JavaScript object. This method does expand the original RAML document by applying traits, resource types, and also including libraries to generate the single JavaScript object.

_Questions (Christian):_

* _The current JSON output also includes information about `traits`, `resourceTypes`, `is`, etc. even after the expansion; should we provide an option to ignore these nodes to generate a more concise output without information that might not be relevant? Not saying we should completely remove it since some tools might find that data very useful, but there are others that does not need them._
* _Should we also give an option to expand types with that process or not?_   

* _Every other function has an additional input for Overlays & Extensions. Does this function not include that as well?_

#### `loadRAML(path, [extensionsAndOverlays], [options])`

_Denis, is this deprecated in the future?_ 

#### `loadApi(path, [extensionsAndOverlays], [options])`

_Denis, is this deprecated in the future?_ 

#### `parseRAML(content, [options])`

_Denis, is this deprecated in the future?_ 

### Options Class

_Denis can you fill out the options available please_

-----------------------

In general, I'd like to understand what functions will be deprecated (we leave them there for people who still use them but remove it in a future version - that gives tooling vendors time to switch) and what functions will stay. Recent discussions we had, I remember that we want to have two access points at the moment. One to retrieve the AST and another a JavaScript Object. Please change this comment so that we understand that a bit more.

**Comment by sichvoge** [comment]
I also wonder if we should generalize the `path` parameter into `api` that could be either a `string` or `object`, where the `object` is a simple JavaScript object of a RAML document and the `string` either a file path or URL. 

We could define the path as following:

> The path can be absolute or relative. In Node, the path is relative to process.cwd(). In the browser, it's relative to the URL of the page.

Not sure if that makes sense though, but I throw it into the room anyways for feedback ;)

**Comment by ddenisenko** [comment]
>and the string either a file path or URL.

That is already supported.

>where the object is a simple JavaScript object of a RAML document

In which format? JSON being a result of YAML->JSON conversion?

I guess we could try to check the string to determine if it is a path/URL or actual document content (in example, by demanding that valid content must always start from RAML header otherwise not recognized) and support the pure string content this way.

Btw, we also need to discuss what to do with an option for file system resolver, it is needed in case of the RAML file containing any outgoing FS links (includes, libs, etc).

**Comment by sichvoge** [comment]
@ddenisenko there are still todos for you, see https://github.com/raml-org/raml-js-parser-2/issues/564#issuecomment-265731622.

Regarding:

> In which format? JSON being a result of YAML->JSON conversion?

Good question. I'd say, lets forget about my comment for now :) 

> I guess we could try to check the string to determine if it is a path/URL or actual document content (in example, by demanding that valid content must always start from RAML header otherwise not recognized) and support the pure string content this way.

I think the previous way was good enough. Wouldn't change anything yet.

**Comment by ddenisenko** [comment]
>So I wonder if it is not better for us to build and maintain a simple MD file for the API documentation, or continue to compile the documentation from code.

We need both. The old API is better described by the current documentation, and we should maintain it while the old API is intact.

The new API is better described by a simple .md with the description of two top-level methods and JSON schema (with docs inside) describing JSON output. It may be a good idea to generate more user friendly HTML from that schema, but for now the schema should be enough.

>At least, could change the MD file with the new API so that you include the complete top level API?

It is done. I added a section in the bottom, which described both the new API and the old API combined. 

I should not that the current documentation described the old top-level API better:
https://raml-org.github.io/raml-js-parser-2/interfaces/_src_raml1_wrapped_ast_parsercoreapi_.options.html

>Denis, is this deprecated in the future?
Added a notion that the old API may be deprecated in future when there is an alternative for the clients that want more in-depth analysis of RAML, but for now nothing in the old API methods changes, only the JSON conversion output is updated.

**Comment by sichvoge** [comment]
> only the JSON conversion output is updated.

What does that mean?

Can you also answer my questions inside https://github.com/raml-org/raml-js-parser-2/issues/564#issuecomment-265731622, pls.

**Comment by ddenisenko** [comment]
>What does that mean?

That means exactly that: functions and their signatures are not changed. The result of conversion of top-level node to JSON is changed according to the list of changes in the same document.

>Can you also answer my questions inside 

>The current JSON output also includes information about traits, resourceTypes, is, etc. even after the expansion; should we provide an option to ignore these nodes to generate a more concise output without information that might not be relevant? Not saying we should completely remove it since some tools might find that data very useful, but there are others that does not need them

On the other hands, this information does not hurt anyone, it is easy to just ignore those top-level nodes. We have intention to reduce the number of options, not to increase it, so I would just leave it as-is.

>Should we also give an option to expand types with that process or not?

In my opinion we can not provide type expansion that works in most of the cases, so we'd better leave it to the 3rd-party tools, or, at least, to the tools separate to the parser.

>Every other function has an additional input for Overlays & Extensions. Does this function not include that as well?

Yes, it is excluded. The reason for such an exclusion is that we try to reduce the number of options, and for now it looks like current users mostly rely on just providing an extension or overlay as a main file, and then the parser finds out all the dependencies automatically. It does not look like this options is really used.

**Comment by sichvoge** [comment]
Thanks Denis. Before I respond to your comments, there are still open todos for you ;)

![image](https://cloud.githubusercontent.com/assets/498114/22590064/67050f52-ea05-11e6-8622-842cf0bc1a9b.png)

**Comment by sichvoge** [comment]
> That means exactly that: functions and their signatures are not changed. The result of conversion of top-level node to JSON is changed according to the list of changes in the same document.

So this is the improved JSON representation? That means, people will end up with the "better JSON" regardless of the use the new or old way to parse?

**Comment by ddenisenko** [comment]
>Before I respond to your comments, there are still open todos for you ;)
>Denis, is this deprecated in the future?

From https://github.com/raml-org/raml-js-parser-2/blob/tck-schema-changes/documentation/TheNewApi.md :

`Old API methods stay as-is and are not changed in any way compared to the current state, the only difference is in the JSON output.`

`Old API methods may be deprecated in future when an alternative based on high-level AST is ready. It is recommended to use the new API when possible.`

>Denis can you fill out the options available please

The type is described in the bottom of https://github.com/raml-org/raml-js-parser-2/blob/tck-schema-changes/documentation/TheNewApi.md

**Comment by ddenisenko** [comment]
>So this is the improved JSON representation? That means, people will end up with the "better JSON" regardless of the use the new or old way to parse?

Exactly.

**Comment by sichvoge** [comment]
Is this desired? I mean we break backwards compatibility for any existing application and that could create a lot of problems. Isn't it better to leave it and say its deprecated and people should use the new function? At least that would give everyone some time.

**Comment by ddenisenko** [comment]
After a meeting regarding the updated JSON format, it was decided that for the compatibility reasons the old API conversion to JSON will remain untouched, and only the new API will result in the new JSON.

**Comment by ddenisenko** [comment]
Here is Christian's comment and questions converted/upgraded to the new section in the document, cross-posting it here to ease the discussion:

## RAML Parser API Summary

This section provides an overview of the top-level methods of both old API and new API combined. Old API methods stay as-is and are not changed in any way compared to the current state, the only difference is in the JSON output.

### Parsing Functions

_There are dedicated functions for executing below functions synchronously (function name + `Sync`) or asynchronously. For example, `load` is an asynchronous function and returns a promise where as `loadSync` is synchronous. The below list only covers the asynchronous functions since the main purpose is exactly the same._

- `load(path, [options])` - new
- `loadRAML(path, [extensionsAndOverlays], [options])` - old
- `loadApi(path, [extensionsAndOverlays], [options])` - old
- `parseRAML(content, [options])` - old

Old API methods may be deprecated in future when an alternative based on high-level AST is ready. It is recommended to use the new API when possible.

#### `load(path, [options])`

Loads the given RAML document and returns it as a single JavaScript object. This method does expand the original RAML document by applying traits, resource types, and also including libraries to generate a single JavaScript object.

Method gets file `path` string and optional `options` map as parameters.

#### `loadRAML(path, [extensionsAndOverlays], [options])`

Loads the given RAML document and returns it as top-level API node promise. This node can be further expanded by calling `expand(true)` and converted to JSON by calling `toJSON()`.

Method gets file `path` string, optional `extensionsAndOverlays` string array and `options` map as parameters. `extensionsAndOverlays` is an array of additional extensions and overlays to be applied to the file specified in `path` parameter.

This method will be removed in the distant future.

#### `loadApi(path, [extensionsAndOverlays], [options])`

Loads the given RAML API document and returns it as top-level API node promise. This node can be further expanded by calling `expand(true)` and converted to JSON by calling `toJSON()`. Fails for fragment types different from API.

Method gets file `path` string, optional `extensionsAndOverlays` string array and `options` map as parameters. `extensionsAndOverlays` is an array of additional extensions and overlays to be applied to the file specified in `path` parameter.

This method will be removed in the distant future.

#### `parseRAML(content, [options])`

Loads the given RAML API document and returns it as top-level API node promise. This node can be further expanded by calling `expand(true)` and converted to JSON by calling `toJSON()`. Fails for fragment types different from API.

Method gets file `content` string and optional `options` map as parameters. Parser will still reach out from the original file contents if there are any outgoing links like libraries and includes.

This method will be removed in the distant future.

#### Old API Options

* `attributeDefaults` - If true, attribute defaults will be returned if no actual vale is specified in RAML code. Affects only attributes.

* `filePath` - Absolute path of the RAML file. May be used when content is provided directly on RAML parser method call instead of specifying file path and making the parser to load the file.

* `fsResolver` - Module used for operations with file system. Should implement `content` method returning file contents taking file path as a parameter and `contentAsync` method returning file contents promise and taking file path as a parameter.

* `httpResolver` - Module used for operations with web. Should implement `getResource` method returning file contents taking file url as a parameter and `getResourceAsync` method returning file contents promise and taking file url as a parameter.

* `rejectOnErrors` - Whether to return Api which contains errors. If false, asynchronous methods promise result will fail.


#### New API Options

* `fsResolver` - Module used for operations with file system. Should implement `content` method returning file contents taking file path as a parameter and `contentAsync` method returning file contents promise and taking file path as a parameter.

* `httpResolver` - Module used for operations with web. Should implement `getResource` method returning file contents taking file url as a parameter and `getResourceAsync` method returning file contents promise and taking file url as a parameter.

**Comment by ddenisenko** [comment]
Extracted API overview to a separate document: https://github.com/raml-org/raml-js-parser-2/blob/tck-schema-changes/documentation/ApiOverview.md

**Comment by sichvoge** [comment]
Why do we remove the option `rejectOnErrors`? Its quite helpful in certain scenarios.

**Comment by ddenisenko** [comment]
Because one of our goals is to make things simpler, including the reduction of the number of options. There is no such big difference between handling promise rejection and just checking that resulting JSON has no errors. One liner both, so why duplicating it.

**Comment by ddenisenko** [comment]
Changed terms: "Old API"->"Current API", "New API" -> "Beta version of the new API" in the following documents:

https://github.com/raml-org/raml-js-parser-2/blob/develop/documentation/TheNewApi.md
https://github.com/raml-org/raml-js-parser-2/blob/develop/documentation/ApiOverview.md

**Comment by KonstantinSviridov** [comment]
The documentation file is
https://github.com/raml-org/raml-js-parser-2/blob/master/documentation/GettingStartedNewApi.md
