### ISSUE TITLE
Error message not helpful when missing parameter for an applied trait.

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#567]
Hi, I am using [this example](https://github.com/advanced-rest-client/raml-example-api) where I apply a trait to the `/products` resource at line 170. Just to test something, I removed the parameter `resourceType` and got the following error message 

![image](https://cloud.githubusercontent.com/assets/498114/20895036/b66c6b82-bb0f-11e6-9bd4-b3ab6ef06dde.png)

The error message is not very helpful as it does not tell me that I am missing the parameter `resourceType`. Is that something we can improve?

**Comment by ddenisenko** [comment]
I agree, we need at least a warning when a trait reference has some parameters unspecified (excluding builtins).

**Comment by KonstantinSviridov** [comment]
the error messages are already fine in `develop`
