### ISSUE TITLE
line numbers are off by one

### ISSUE THREAD

**Issue by alexch** [raml-org/raml-js-parser-2#575]
See https://github.com/raml2html/raml2html/issues/283 and https://github.com/raml2html/raml2html/issues/289

Text editors count lines and columns starting at 1, not at 0. I'm using `raml2html` and some of the error messages include off-by-one line number counts. 

Is the intent of this library to support the text editor convention (start at 1) or an internal C-string style convention (start at 0)? If the former then please change the output; if the latter then please document that tools like `raml2html` that take files and pass them in to `raml-js-parser` need to add one to the results.

**Comment by ddenisenko** [comment]
We can not change it from 0 to 1 now as this will make all existing users to patch their code.

I added the description mentioning line number starting from 0 to the JSON schema https://github.com/raml-org/raml-js-parser-2/blob/master/tckJsonSchema/tckJsonSchema.json
and the link to the schema itself to the parser readme.

Will be released in 1.1.11
