### ISSUE TITLE
Create a prototype of reusing a previous version of AST as a cache

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#576]
This is a first step in speeding up parsing in a case when user is editing a single file and we can try to reuse the parsing data of all other files, current file depends from.

**Comment by KonstantinSviridov** [comment]
the result is in the `ast-reuse` branch: https://github.com/raml-org/raml-js-parser-2/tree/ast-reuse

in order to pass the node to be reused, utilize the `reusedNode` option:
https://github.com/raml-org/raml-js-parser-2/blob/ast-reuse/src/raml1/wrapped-ast/parserCoreApi.ts#L61

**Comment by KonstantinSviridov** [comment]
The AST reuse prototype has been brought into `develop` branch with https://github.com/raml-org/raml-js-parser-2/commit/cb99a46c55abec5407ca67b39b9a393e64b3d17a
