### ISSUE TITLE
Cannot reference to type names like `'ServiceResponse[String]'`

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#577]
The parser returns "Inheriting from unknown type" using the following RAML:

```yaml
#%RAML 1.0
title: TestRAML

types:
  'ServiceResponse[String]':
    properties:
      success:
        facets:
          readOnly: boolean
        type: boolean
        readOnly: true
        required: false

/GenerateSplitInvoices:
  post:
    displayName: ApiInvoiceGenerateSplitInvoicesPost
    responses:
      '200':
        body:
          text/plain:
            type: 'ServiceResponse[String]'
```

After consulting with Pavel, the type `'ServiceResponse[String]'` is completely valid.

**Comment by sichvoge** [comment]
@petrochenko-pavel-a how would we handle type names like `ServiceResponse[]`? For example:

```yaml
#%RAML 1.0
title: TestRAML

types:
  'ServiceResponse[]':
    properties:
      success:
        facets:
          readOnly: boolean
        type: boolean
        readOnly: true
        required: false

/GenerateSplitInvoices:
  post:
    displayName: ApiInvoiceGenerateSplitInvoicesPost
    responses:
      '200':
        body:
          text/plain:
            type: 'ServiceResponse[]'
```

You could interpret `ServiceResponse[]` also as array of type `ServiceResponse`. Where are we drawing the line?

**Comment by ddenisenko** [comment]
>After consulting with Pavel, the type 'ServiceResponse[String]' is completely valid.

I disagree. While spec does not explicitly forbid this, the spec does not also explicitly allow this. Thus this case is undefined and we need to use our best judgement.

And allowing the character, which is a special for both YAML arrays syntax and type expressions syntax right inside the type expression looks like a bad idea for me.

**Comment by ddenisenko** [comment]
How about this "valid" exotic class name:

`type: YouNeverKnowWhatIsClassName|`

or this one:

`type: (AndThisIsAlsoIdentifier` ?

We should just create a list of reserved characters.

**Comment by petrochenko-pavel-a** [comment]
>And allowing the character, which is special for both YAML arrays syntax and type expressions syntax.

Is it possible to parse it? It is obviously yes. Is it hard to support such cases? To best of my memory it is just a simple fix of type expression peg grammar and regeneration of type expression parser then. 

When I look in [Type Expression Syntax Definition](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#type-expressions), I am reading it as that only `[]` should be treated as an type expression array short cut, and I do not see any reason why '[' which is not followed by ']' should be a something special.  

How ever yes I agree it is confusing and in more complex cases it may be extremely confusing.

@ddenisenko provides some very nice examples here. 

Where is a border? As for me we should support simple cases like a special characters inside of identifier like `ServiceResponse[String]` and then publish a PEG grammar which formalises type expression resolution some where. 


Regards,
Pavel

**Comment by sichvoge** [comment]
Seems that might be a discussion we should probably have [here](Disallow reserved characters in type names).

I am closing this issue for now.
