### ISSUE TITLE
Request headers are a map, but response headers are an array.

### ISSUE THREAD

**Issue by nickwb** [raml-org/raml-js-parser-2#582]
Hello maintainers,

Apologies if I'm mistaken with this bug - I am new to this project.

There seems to be an inconsistency when comparing the output of the parser between request headers and response headers.

Take this example spec:
```
#%RAML 1.0
title: Bug Example
version: 1.0


/animals:
    /bird:
        get:
            headers:
                X-NestingAffinity: string
    /dog:
        get:
            responses:
                200:
                    headers:
                        X-BarkType: string
```

For the request headers we see:
```
     "methods": [
      {
       "headers": {
        "X-NestingAffinity": {
         "name": "X-NestingAffinity",
         "displayName": "X-NestingAffinity",
         "type": [
          "string"
         ],
         "required": true
        }
       },
       "method": "get"
      }
     ],
```

Whereas for the response headers we see:
```
     {
       "responses": {
        "200": {
         "code": "200",
         "headers": [
          {
           "name": "X-BarkType",
           "displayName": "X-BarkType",
           "type": [
            "string"
           ],
           "required": true
          }
         ]
        }
       },
       "method": "get"
      }
```

We can see that the request headers are an object map, with the header name as the key. The response headers however are simply an array, with each element containing a name property.

This makes for some buggy behavior upstream in `raml2html`, see [this issue](https://github.com/raml2html/raml2html/issues/287).

Regards,
Nick

**Comment by ddenisenko** [comment]
@KonstantinSviridov , what do you think of it? Looks like an inconsistency.

**Comment by KonstantinSviridov** [comment]
Hi @nickwb  !

The fix is now in the 'develop' branches set and it will be brought to 'master' and NPM with the nest release.

Regards,
Konstantin
