### ISSUE TITLE
AST reusing mechanism should be applied only for those changes which do not affect AST obtained from external files.

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#585]
The AST reusing mechanism prototype implemented in 
https://github.com/raml-org/raml-js-parser-2/tree/ast-reuse
supposes that changes in the main RAML file do not affect AST obtained from external files.

However, this condition is not always satisfied. For example, an external RAML file may refer a type defined in the main file or it may be affected by a template deifined in the main file.

Thus, we should implement some algorithm of defining whether a particular edit case of the main RAML file may affect AST obtained from some external file.

**Comment by ddenisenko** [comment]
Implemented in ast-reuse branch.
