### ISSUE TITLE
Tracing errors only appear when expanding libraries with expand(true)

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#591]
When using the following [project](https://github.com/raml-org/raml-js-parser-2/files/683384/Z_System_API-v1.0.0.zip), there is an inconstancy in the error output, it only reports errors after performing a library expansion.

Example usage:
```
parser.loadApi(file).then((api) => {
  api = api.expand(true) // it only fails when expanding libraries
  const json = api.toJSON({ rootNodeDetails: true });
  if (json.errors && json.errors.length)  console.error("Errors found after library expansion")
  else console.log("Ok!")
}).catch((errors) => {
    console.error("Errors found while loading api")
})
```

**Comment by ddenisenko** [comment]
I confirm there is a difference in the error output depending on whether library expansion is turned on or off.

It looks like there is a repeating usage of `type: TypeName?` construction across the code, the interesting part is why this is not reported without library expansion.
