### ISSUE TITLE
"required: true" not set by default starting at 1.1.11

### ISSUE THREAD

**Issue by naterkane** [raml-org/raml-js-parser-2#592]
just starting to look into things now... as I was working on my branch of raml2obj i came across an issue when updating `raml-1-parser` from `1.1.10` to `1.1.11`

the potential irony here is the `1.1.11` release notes state
* Parser `toJSON()` method sets `"required": true` on types, yet it appears to now do the opposite.

example output from `1.1.10`
```js
{ name: 'Foos',
  displayName: 'Foos',
  type: 'array',
  required: true,
  items:
   { additionalProperties: true,
     type: 'object',
     displayName: 'Foo',
     name: 'Foo',
     required: true,
     properties:
      [ { type: 'string',
          displayName: 'id',
          name: 'id',
          required: true,
          key: 'id' } ] },
  key: 'application/json' }
```

example output from `1.1.11`
```js
{ name: 'Foos',
  displayName: 'Foos',
  typePropertyKind: 'TYPE_EXPRESSION',
  type: 'array',
  items:
   { additionalProperties: true,
     type: 'object',
     displayName: 'Foo',
     name: 'Foo',
     typePropertyKind: 'TYPE_EXPRESSION',
     properties:
      [ { type: 'string',
          displayName: 'id',
          name: 'id',
          typePropertyKind: 'TYPE_EXPRESSION',
          required: true,
          key: 'id' } ] },
  key: 'application/json' }
```

**Comment by jstoiko** [comment]
It's referring to #560 although I agree it's a little confusing, maybe prefixing all issues in the release notes with `Closing "[title of issue]" (#[issue_id])` or `Fixing "[title of issue]" (#[issue_id])`would help.

also, IMHO, this breaking change should have granted at least a minor increment.

**Comment by naterkane** [comment]
Agreed, it should have been at least a minor

**Comment by ddenisenko** [comment]
@naterkane , as @jstoiko commented out, the change is referring https://github.com/raml-org/raml-js-parser-2/issues/560 . In order to avoid confusion in future, I will include full issue URLs into release notes.

**Comment by naterkane** [comment]
Wonderful, thanks!

- sent from my potato
