### ISSUE TITLE
Pipe symbol is allowed in key name of data-type

### ISSUE THREAD

**Issue by JonathanMontane** [raml-org/raml-js-parser-2#596]
**Version: 1.1.12**

**Issue:**
Pipe symbol is allowed in the key name of data-types, which makes interpretation of union types ambiguous, as one would not be able to tell whether `Cat|Dog` refers to the union type of `Cat` and `Dog` or the data-type `Cat|Dog`.

**Proposed Solutions:**
- Disallow `|` in data-type key names
- or Specifically state that union type is (pipe with spaces) `  |  ` (use `U+205F` to force space inside backticks)

**Comment by ddenisenko** [comment]
I agree with you.

Honestly, there is no list of what symbols are allowed and what are not in the spec.

Here you can find out another attempt to use type-expression-related symbols in type names, also ending bad: https://github.com/raml-org/raml-js-parser-2/issues/577

In my opinion, we should create and clearly list all the symbols having a special use in type expression syntax and ban them all from type names. Yes, sometimes it is possible to determine what user actually meant, but potential user confusion does not worth it.

@sichvoge ☝️

**Comment by sichvoge** [comment]
Makes sense. As this is a spec related issue, we should move it into its respective repository. I'll take that action and post a link into this thread.

**Comment by sichvoge** [comment]
https://github.com/raml-org/raml-spec/issues/596. Closing this issue.
