### ISSUE TITLE
Not able to define additional properties at body default node

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#606]
Having the following example where default node includes an additional attribute that it is not defined at base type.

[additionalPropertiesArray.raml.zip](https://github.com/raml-org/raml-js-parser-2/files/699245/additionalPropertiesArray.raml.zip)

It seems that, although additional properties are true by default, when default content is parsed, it is considered as invalid

![image](https://cloud.githubusercontent.com/assets/19980188/21854278/eb424e7a-d7f8-11e6-82fd-3861b1ecbfe3.png)

**Comment by ddenisenko** [comment]
`additionalProperties` regulate whether you can have the properties in type instance object, which are not declared in the defining type. 

In this particular case you are adding `default` property to the descendant type declaration, basically you are trying to use an unknown facet, and that is invalid.

The error message is weird though. If you replace the unknown facet name from `default` to `default123`, you'll have the proper`Specifying unknown facet 'default123'` message. With `default` facet name, its looks like a legacy leftover, this error message should be fixed.

**Comment by ddenisenko** [comment]
I was wrong. It appeared, that according to the spec any type can have default value, not just value types. So in this case we should recognize `default` facet as valid and validate its contents against the type. 

This is something parser already does, but it interprets the type as closed even when `additionalProperties` is set to true and thus reports the error for `title`. 

Instead, it should report a warning for `title` property to make user paying attention to the property not described in the type, but not marking the instance as invalid.

**Comment by KonstantinSviridov** [comment]
This is how the warning is going to look:
![defaultwarning](https://cloud.githubusercontent.com/assets/6206034/22041360/2a81bbee-dd39-11e6-9655-dda06f0589b0.png)

**Comment by nmarinel01** [comment]
Great ! Same experience as when examples have additional properties included, right ?
Will this be included as 1.1.14 ?
Thanks !

**Comment by KonstantinSviridov** [comment]
Right, same experience as with examples.
Yes, it is going to be included in 1.1.14.
