### ISSUE TITLE
raml-typesystem changed raml-xml-validation to optional dependency

### ISSUE THREAD

**Issue by thomaschaaf** [raml-org/raml-js-parser-2#609]
As `raml-typesystem` has changed `raml-xml-validation` to an optional dependency see:
https://github.com/raml-org/raml-typesystem/commit/18bce2a91b523b05f383c32c2578091127e4e5eb

This parser should add it as a dependency.

**Comment by ddenisenko** [comment]
`raml-typesystem` has changed `raml-xml-validation` to an optional dependency long ago. The change you reference is a revert of a previous change, which was never released.

Is there any particular reason for you to consider making `raml-xml-validation` being not optional?
