### ISSUE TITLE
Error in browser when using raml-xml-validation-browser v0.0.10

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#614]
When using `raml-xml-validation-browser : 0.0.10` in bower, I get this error: 
```api-console-vendor.js:8202Uncaught Error: Cannot find module "fs"```
It seems this module is not correctly build for browser usage.
It works when using the old version `0.0.9`.

**Comment by ddenisenko** [comment]
Fixed. 0.0.11 released, updated zip archive in parser 1.1.13 release.
