### ISSUE TITLE
RAML project reports errors only after expanding

### ISSUE THREAD

**Issue by agustinlg** [raml-org/raml-js-parser-2#619]
Using this project [Z_System_API-v1.0.0 (1).zip](https://github.com/raml-org/raml-js-parser-2/files/724439/Z_System_API-v1.0.0.1.zip), you can parse and see that there are no errors.
But, when using `api.expand(true)` and then getting the errors using `getJson({rootNodeDetails: true})`, errors suddenly appear.
Maybe the parser tests could check for errors after expanding to check that it doesn't break.

**Comment by KonstantinSviridov** [comment]
Hi, @agustinlg 

You're right. Comparing errors before and after library expansion is a good idea.

Regards, Konstantin
