### ISSUE TITLE
[xmldom error] invalid doc source

### ISSUE THREAD

**Issue by thebinarypenguin** [raml-org/raml-js-parser-2#628]
I'm getting a strange error message on STDERR when I execute `loadRAML()`

Example
```js
"use strict";                                                                                                                     

const raml = require("raml-1-parser");

raml
  .loadRAML("existent-but-empty-file", [], { rejectOnErrors: true })
  .then((data) => {
    // Do nothing 
  })
  .catch((err) => {
    // Do nothing
  });
``` 

I get the following output on STDERR
```
[xmldom error]	invalid doc source 
@#[line:0,col:undefined]
```

Since I'm developing a command line tool this is VERY annoying as it screws with my tests. I don't remember having this issue in the past. Has something changed recently that would cause this? Do I need to go investigate the `xmldom` package?

**Comment by thebinarypenguin** [comment]
Upon further investigation it looks like when a new `DOMParser()` is created it needs to be passed an options object with error handler functions. **[Reference](https://github.com/jindw/xmldom#api-reference)**

xmldom's default error handler functions call `console.warn` and `console.error` and I'm pretty sure that is the root of this issue. **[Reference](https://github.com/jindw/xmldom/blob/56eb39f82dd2052a683b1870fb1f4a105e184f66/dom-parser.js#L178)**

**Comment by SimonSchick** [comment]
Having the same problem, getting a bunch of warnings here.

**Comment by dreamflyer** [comment]
will be published in v1.1.15.

**Comment by thebinarypenguin** [comment]
Just pulled down the `develop` branch. Can confirm this issue is fixed.

**Comment by jy95** [comment]
Any known release date for 1.1.15 ?
