### ISSUE TITLE
Implement the new simplified API for JSON output

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#634]
Here is the description: https://github.com/raml-org/raml-js-parser-2/issues/564

**Comment by sichvoge** [comment]
Before doing that, we should really talk about the backwards compatibility that I mentioned [here](https://github.com/raml-org/raml-js-parser-2/issues/564#issuecomment-277514294)

**Comment by KonstantinSviridov** [comment]
implemented in https://github.com/raml-org/raml-js-parser-2/commit/cb99a46c55abec5407ca67b39b9a393e64b3d17a
