### ISSUE TITLE
Speed up toJSON

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#636]

**Comment by KonstantinSviridov** [comment]
implemented in https://github.com/raml-org/raml-js-parser-2/commit/cb99a46c55abec5407ca67b39b9a393e64b3d17a

related tickets:
https://github.com/raml-org/raml-js-parser-2/issues/656
https://github.com/raml-org/raml-js-parser-2/issues/654
https://github.com/raml-org/raml-js-parser-2/issues/627
