### ISSUE TITLE
Enhancement: Obtain file path for type definition like abc.xsd#blah

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#638]
Using this RAML file, 
#%RAML 1.0
title: My API With Types
types:
Foo:
  **type: !include ../../types/songs.xsd#City**

Need to obtain file path for type definition.
Pavel said me that there is a schemaPath attribute when you define type like 
Foo: types/songs.xsd 
but doesn't available when definition is like this 
Foo 
  type: types/songs.xsd

Also using 
Foo: !include ../../types/songs.xsd#City
parser returns schemaPath attribute like Li4vLi4vdHlwZXMvc29uZ3MueHNkL0NpdHk.xsd
Thanks!

**Comment by KonstantinSviridov** [comment]
Hi, @glodieu 

The fix is available in the `develop` branches set, and the next parser release will bring it to `master`.

Regards, Konstantin
