### ISSUE TITLE
Type not being parsed properly in RAML 0.8

### ISSUE THREAD

**Issue by lbauret** [raml-org/raml-js-parser-2#643]
When parsing the following RAML 0.8 api it seems that the type of the default value is not being parsed correctly. As the RAML 0.8 spec states, when a parameter's type is not specified it defaults to string. In this case the parameter's type is not specified, but after being parsed the value `0` of the `default` attribute is of type number instead of string, as it should. The value `0` of the `example` attribute, however, is correctly parsed to type string.

```
#%RAML 0.8
title: Example API
version: v1
/users:
  post:
    queryParameters:
      position:
        description:
        default: 0
        example: 0
    description: User post
    responses:
      400:
        description: Bad request
```

**Comment by ddenisenko** [comment]
Here is the parser JSON output for this example:

```
{
  "ramlVersion": "RAML08",
  "type": "Api",
  "specification": {
    "title": "Example API",
    "version": "v1",
    "resources": [
      {
        "relativeUri": "/users",
        "methods": [
          {
            "responses": {
              "400": {
                "code": "400",
                "description": "Bad request"
              }
            },
            "queryParameters": {
              "position": {
                "name": "position",
                "displayName": "position",
                "type": "string",
                "required": false,
                "default": 0,
                "example": "0",
                "repeat": false,
                "description": {}
              }
            },
            "description": "User post",
            "method": "post"
          }
        ],
        "displayName": "/users",
        "relativeUriPathSegments": [
          "users"
        ],
        "absoluteUri": "/users"
      }
    ]
  },
  "errors": []
```

`position ` parameter is correctly assigned with `"type": "string"`

Just to clarify, you expect the value of `default` attribute to be quoted, that is the issue? 
`"default": "0"` instead of `"default": 0`

**Comment by lbauret** [comment]
@ddenisenko Thanks for your reply!
> Just to clarify, you expect the value of default attribute to be quoted, right?
"default": "0" instead of "default": 0?

That's right. As the `position` parameter is correctly assigned with `"type": "string"` , the value of `default` attribute should be quoted as type string (`"default": "0"`), just like the example attribute is correctly assigned to `"example": "0"`.

**Comment by KonstantinSviridov** [comment]
Hi, @lbauret !

The fix is now in the 'develop' branches set and it will brought to 'master' and npm with the next release.

Regards,
Konstantin
