### ISSUE TITLE
map type expression not supported

### ISSUE THREAD

**Issue by woodp** [raml-org/raml-js-parser-2#65]
When trying to use **map** type expression, as stated [here](http://docs.raml.org/specs/1.0/#raml-10-spec-type-expressions)
I get  *"Syntax error:Expected \"|\" or end of input but \"{\" found.*

Example:
```
#%RAML 1.0
title: My Api
/maps:
    get:
      responses:
        200:
          body:
            type: number{}
```

**Comment by ddenisenko** [comment]
Thank you for reporting, it is reproducible. We will investigate.

**Comment by petrochenko-pavel-a** [comment]
Map types expression shortcut was removed  in RC2. So closing this for now.

Regards,
Pavel
