### ISSUE TITLE
JS error when empty node

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#659]
Let's assume we have the following RAML:

```yaml
#%RAML 1.0
title: A
baseUri:
```

The parser returns an error `Cannot read property 'length' of null`. That's a rather strange error and I don't see anything in the spec that `baseUri` cannot be empty. Even if thats not the case, we should at least return that this node shouldn't be empty and not some underlying function problems.

**Comment by dreamflyer** [comment]
will be published in v1.1.15.
