### ISSUE TITLE
How do I get the value from a valueType

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-js-parser-2#662]
Hi. Currently I use a mix of the high level api from loadApi and the runtimeType system. I'm using the api10.Api to get values such as baseUri etc and the runtimeTypes when dealing with the type system. It seems loadApi is deprecated though so I would need to move completely to the runtimeTypes? I can find the property definitions via loadRAML, where I find valueTypes, but can't see any way of getting the actual user defined value..
```
let api = await loadRaml('...');

let title = api.definition().allProperties().find(prop => prop.nameId() === 'title');

title.isValueProperty() === true;
title.range().isValueType() === true;

// where is title value??
```

Help appreciated :sweat_smile:

**Comment by KonstantinSviridov** [comment]
Hi, @domarmstrong

Have you tried `let titleValue = api.title()` ?

**Comment by domarmstrong** [comment]
Think I read the 'ApiOverview' wrong.. In my code I am using `loadApi` at the moment and I do use `api.title()`. I was looking at moving to `loadRAML` as I thought `loadApi` is going to be removed in the future. Now re-reading, it looks like all of these will be removed.. 

load(path, [options]) - new
loadRAML(path, [extensionsAndOverlays], [options]) - current (This method will be removed)
loadApi(path, [extensionsAndOverlays], [options]) - current (This method will be removed)
parseRAML(content, [options]) - current  (This method will be removed)

But `load` just returns json right? I'm using the top level api for api and resources, but the runtimeType system for type handling and validation (using my own wrapper on the runtimeType system). How will I get this if loadRAML and loadApi are removed? I found working with the runtimeTypes simplified my code quite a lot over trying to process types from the JSON via parsing type expressions.

**Comment by KonstantinSviridov** [comment]
Ok, I see.

In case loadApi, loadRAML (and top level AST also) wiill be removed, you'll have to switch to high level AST. Right now highLevel root node can be obtained as
```
let hlApi = api.highLevel();
```
and in future (if all the mentioned methods and top level AST will be removed) there will be a method which accepts path and options and returns high level AST root.

In order to retrieve title from the high level root node you'll have to use
```
let titleAttr = hlApi.attr("title");
let titleValue = titleAttr && titleAttr.value();
```
or just
```
let titleValue = hlApi.attrValue("title")
```

As for runtime typesystem, it does not provide this data.

**Comment by domarmstrong** [comment]
OK thanks, I'll close this. I'm going to stick to `loadApi` for now and cross this bridge later when the methods are actually deprecated.
