### ISSUE TITLE
Trace information contains warning for a root error

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#669]
Using the attached RAML project, the parser response perfectly fine with an error that there is an issue inside a library. Although the root error is correct, it seems that the trace information contains a warning for that, but I would expect that it's an error as well.

```
[
  {
    "code": "INHERITING_UNKNOWN_TYPE",
    "message": "Inheriting from unknown type",
    "path": "/Users/christianmule/projects/raml/raml-tck/tests/semantic/raml-1.0/libraries/libs/bar-lib-unknown-type.raml",
    "range": {
      "start": {
        "line": 7,
        "column": 4,
        "position": 67
      },
      "end": {
        "line": 7,
        "column": 8,
        "position": 71
      }
    },
    "isWarning": false,
    "trace": [
      {
        "code": "ISSUES_IN_THE_LIBRARY",
        "message": "Issues in the used library: 'libs/bar-lib-unknown-type.raml'",
        "path": "api-with-invalid-lib.raml",
        "range": {
          "start": {
            "line": 4,
            "column": 2,
            "position": 32
          },
          "end": {
            "line": 4,
            "column": 5,
            "position": 35
          }
        },
        "isWarning": true // this here should be 'false'
      }
    ]
  }
]
```

[libraries.zip](https://github.com/raml-org/raml-js-parser-2/files/817037/libraries.zip)

I am executing the parser like the following (**NO EXPANSION**):

```js
var api = raml1Parser.loadApiSync(path.resolve(__dirname, ramlPath), 
  {rejectOnErrors: false, attributeDefaults: true}
)
```

**Comment by agustinlg** [comment]
This can be reproduced if you
parser.loadApi(file, {
      attributeDefaults: false,
      rejectOnErrors: false
    }).then((api) => {
      if (expand && api.expand) api = api.expand(true)

      const json = api.toJSON({
        serializeMetadata: false,
        dumpSchemaContents: false,
        rootNodeDetails: true
      });

      if (json.errors && json.errors.length)
        util.exit(json.errors)
      else
        console.log(util.stringify(json.specification))

    }).catch(util.exit)

**Comment by sichvoge** [comment]
Actually, if you execute the same RAML after expansion all errors disappear magically and the file is valid again. Not the expected result :)

**Comment by ddenisenko** [comment]
The last comment is most important. This makes it critical.

**Comment by KonstantinSviridov** [comment]
@sichvoge , @ddenisenko 
Actually, the result is expected as the main RAML tree does not depend on those types which have errors, and, thus, these types do not appear in the library expanded AST. 

If you switch line 14 from `type: bar.A` to `type: bar.B` you'll have the errors back.

**Comment by sichvoge** [comment]
I don't understand. This is definitely not the expected behaviour. Can you elaborate more?

**Comment by KonstantinSviridov** [comment]
The library expandedAST is supposed to contain only those componsents which the main raml file depends on. in our case its only `bar.A` type.

The error happen in the `bar.B` type, which the main file does not depend on. Thus, `bar.B` does not appear in the library expanded AST, and the library expanded AST itself does not have errors.

**Comment by KonstantinSviridov** [comment]
@sichvoge
As for the warning, I do remmember the following dicision (but I can not find where it has been done):

For each library issue the parser should produce an error object (with `isWarning` equal `true` or `false` depending on whether we consider it a warning or not) pointing to the actual error and having a warning object (with `isWarning==true`) in its trace, which points to the uses entry where the library is imported.

Do we actually want the trace object to inherit `isWarning` property from the actual issue object?

**Comment by eduardo-rubio** [comment]
It will be treated as a feature see #688
