### ISSUE TITLE
Version 1.1.16: Invalid JSON schema: There is no validation function for format 'int32' int32

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#673]
Received this error "Invalid JSON schema: There is no validation function for format 'int32' int32" when parsing the following RAML file using parser.loadApi method.

**Comment by glodieu** [comment]
[raml.txt](https://github.com/raml-org/raml-js-parser-2/files/818438/raml.txt)

**Comment by glodieu** [comment]
Working fine using parser version 1.1.15.

**Comment by ddenisenko** [comment]
This format is known by z-schema we use for validation. It is also not included in the official list here: http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3

What we can do is to make validator to ignore unknown formats.

Fix will be available in 1.1.17.
