### ISSUE TITLE
Version 1.1.16: Invalid JSON schema: There is no validation function for format 'YYYY-MM-DD' YYYY-MM-DD

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#674]
Received this error "Invalid JSON schema: There is no validation function for format 'YYYY-MM-DD' YYYY-MM-DD" when parsing the following RAML file using parser.loadApi method.
Working fine using parser version 1.1.15.

```
#%RAML 1.0
title: Mobile Banking API
version: 2.0
baseUri: http://www.placeholder.com/api

types:
  Customer: |
    {
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "id": "http://jsonschema.net",
    "required": true,
    "properties": {
      "id": {
        "type": "string",
        "required": true
        },
      "userName": {
        "type": "string",
        "required": true
        },
      "dob": {
        "type": "string",
        "required": true,
        "format": "YYYY-MM-DD"
        }
      }
    }
```

**Comment by ddenisenko** [comment]
This format is known by z-schema we use for validation. It is also not included in the official list here: http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3

What we can do is to make validator to ignore unknown formats.

Fix will be available in 1.1.17.
