### ISSUE TITLE
Add CI tests for API reuse based on comparison of direct parsing with parsing based on AST reuse

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#682]

**Comment by KonstantinSviridov** [comment]
The tests are contributed in https://github.com/raml-org/raml-js-parser-2/commit/cb99a46c55abec5407ca67b39b9a393e64b3d17a and https://github.com/raml-org/raml-js-parser-2/commit/145abe20edd721377adf591e8750ccffb65ee887
