### ISSUE TITLE
Run the parser against Platform APIs

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#684]

**Comment by KonstantinSviridov** [comment]
The plugin used to collect platform snapshots
https://github.com/KonstantinSviridov/PlatformSnapshot
Right now the plugin uses a hardcoded list of public APIs.

The plugin used to run two versions of parser (plus the old JS parser) agains the collected platform snapshot
https://github.com/KonstantinSviridov/PlatformComparisonScript
