### ISSUE TITLE
Add hierarchy to the complex error report traces

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#688]
The idea is to add more details to the errors and use current traces mechanism for that.

Two areas, which quite require an attention with this regard are JSON validation (syntax and against the schema) and typesystem.

We will start from the JSON to test how it goes, then proceed to other cases.

- [Improve positioning for errors in JSON](https://github.com/raml-org/raml-js-parser-2/issues/723)
- [Error messages on JSON schema validation not really helpful](https://github.com/raml-org/raml-js-parser-2/issues/444)
- [Strange behaviour when space is missing after !include](https://github.com/raml-org/raml-js-parser-2/issues/718)
- [Invalid errors for case of resource type using default media type](https://github.com/raml-org/raml-js-parser-2/issues/714)
- [Trace information contains warning for a root error](https://github.com/raml-org/raml-js-parser-2/issues/669)
- [Not very helpful error message](https://github.com/raml-org/raml-js-parser-2/issues/427)

**Comment by postatum** [comment]
Closing for now as no answers. Feel free re-open if this is still relevant.

Note that raml-js-parser-2 has been deprecated, the new official parser is [webapi-parser](https://github.com/raml-org/webapi-parser). Feel free to attempt to reproduce this issue with webapi-parser and report any issue you may have on that repository.
