### ISSUE TITLE
Api.expand() not working with modules

### ISSUE THREAD

**Issue by potato620** [raml-org/raml-js-parser-2#69]
```
var api = ramlParser.loadApiSync('api.raml', [ 'module1.raml', 'module2.raml' ]);
api.resources().forEach(function(resource) {
        console.log('Adding resource: ' + resource.displayName());
});
```
This logs all resources in module1 and module2. 

But when I add the `api.expand()`, it only logs resources in module2.
```
var api = ramlParser.loadApiSync('api.raml', [ 'module1.raml', 'module2.raml' ]);
api.expand().resources().forEach(function(resource) {
        console.log('Adding resource: ' + resource.displayName());
});
```

Did I misinterpret the expand function?

**Comment by sichvoge** [comment]
What do you mean by `module`?

**Comment by potato620** [comment]
Sorry I meant extension like referenced in
https://github.com/raml-org/raml-js-parser-2/pull/55

I only get the resources from the last extension after using the expand
function.

**Comment by sichvoge** [comment]
Can you post, if possible, an example that we can use to reproduce your problem?

**Comment by potato620** [comment]
oh woops. I wasn't paying attention. There were errors from the parsing because I mistyped my RAML. I'll close my issue.

**Comment by sichvoge** [comment]
haha - cool :+1:
