### ISSUE TITLE
Version 1.1.17: Schema validation exception: Cannot create property '__$validated' on string '[object Object]'

### ISSUE THREAD

**Issue by glodieu** [raml-org/raml-js-parser-2#692]
Get this error when parsing following api.raml and user.json files.
I know that the user.json is not valid ("name": "[object Object]") and there is a new json validation from 1.1.16 but using parser version 1.1.15 doesn't throw any error, I think that new version have to give an option for throw or not error for json validation.

**Comment by glodieu** [comment]
[Archive.zip](https://github.com/raml-org/raml-js-parser-2/files/828870/Archive.zip)

**Comment by ddenisenko** [comment]
As a part of https://github.com/raml-org/raml-js-parser-2/issues/701 , all standalone schema (schemas that have no examples referring them) issues are now warnings. This particular exceptions is also handled and now looks like:

```
  "errors": [
    {
      "code": "INVALID_JSON_SCHEMA_DETAILS",
      "message": "Invalid JSON schema: Unexpected value '[object Object]' ",
      "path": "api.raml",
      "range": {
        "start": {
          "line": 11,
          "column": 2,
          "position": 313
        },
        "end": {
          "line": 11,
          "column": 7,
          "position": 318
        }
      },
      "isWarning": true
    }
  ]

```

**Comment by ddenisenko** [comment]
Fix will be available in 1.1.18

**Comment by glodieu** [comment]
Hi @ddenisenko 
Using parser version 1.1.18, parser error still showing isWarning attribute as false.
```
{
  "parserErrors": [
    {
      "code": "JSON_SCHEMA_VALIDATION_EXCEPTION",
      "message": "Schema validation exception: Cannot create property '__$validated' on string '[object Object]'",
      "path": "api.raml",
      "range": {
        "start": {
          "line": 11,
          "column": 2,
          "position": 313
        },
        "end": {
          "line": 11,
          "column": 7,
          "position": 318
        }
      },
      "isWarning": false
    }
  ]
}
```

**Comment by ddenisenko** [comment]
Can not reproduce. 

Both "isWarning" and error message are different for me. Could you please double-check that you are using 1.1.18 (including all sub-modules, especially raml-typesystem), and if so, could you please describe the way you launch the parsing. Sync/async, expanded or not, library expansion or not etc.

**Comment by glodieu** [comment]
Steps to reproduce:
1-unzip file.
2-npm install
3-npm start

**Comment by glodieu** [comment]
[issue692.zip](https://github.com/raml-org/raml-js-parser-2/files/851413/issue692.zip)

**Comment by ddenisenko** [comment]
[issue692 2.zip](https://github.com/raml-org/raml-js-parser-2/files/854485/issue692.2.zip)

How do you print the errors? I just noticed that instead of `errors` key in parser JSON output your sample output contains "parserErrors".

I modified your example, please see it attached, the main difference is that `toJSON` method gets an argument to print root node details, which contains the errors. And, I got:

```
"errors": [
    {
      "code": "INVALID_JSON_SCHEMA_DETAILS",
      "message": "Invalid JSON schema: Unexpected value '[object Object]' ",
      "path": "api.raml",
      "range": {
        "start": {
          "line": 11,
          "column": 2,
          "position": 313
        },
        "end": {
          "line": 11,
          "column": 7,
          "position": 318
        }
      },
      "isWarning": true
    }
  ]

```

Let me know what you get running this example.

**Comment by glodieu** [comment]
Output in your case doesn't show isWarning attribute.
```
  "errors": [
    {
      "code": "JSON_SCHEMA_VALIDATION_EXCEPTION",
      "message": "Schema validation exception: Cannot create property '__$validated' on string '[object Object]'",
      "path": "api.raml",
      "range": {
        "start": {
          "line": 11,
          "column": 2,
          "position": 313
        },
        "end": {
          "line": 11,
          "column": 7,
          "position": 318
        }
      }
    }
  ]
```

**Comment by glodieu** [comment]
FYI
```
~/Downloads/issue692 :nvm current
v7.7.3
```

**Comment by ddenisenko** [comment]
Could you please run this command in the sample's root and let me know what the output is?
`npm ls | grep "raml-1-parser\|raml-typesystem"`

> Also check that code and message attributes are different.
I know. This is exactly what it were in 1.1.17 as compared to the new ones in 1.1.18.

**Comment by ddenisenko** [comment]
Nevermind. The issue is reproduced. It looks like z-schema produces different errors depending on unknown circumstances. I cant reproduce it locally, but we reproduced it on other environment.

**Comment by glodieu** [comment]
Ok, thanks.

**Comment by ddenisenko** [comment]
Fixed. Fix should be available in 1.1.19.

**Comment by glodieu** [comment]
Hi @ddenisenko Do you have an ETA for parser version 1.1.19?
Thanks.

**Comment by ddenisenko** [comment]
Next Tuesday evening, Wednesday if something urgent is at hands.
