### ISSUE TITLE
[bug] Method.protocols() return the default protocol from the baseUri instead of empty list

### ISSUE THREAD

**Issue by JonathanMontane** [raml-org/raml-js-parser-2#694]
Test Case:

```yaml
#%RAML 1.0
title: Hello world # required title
protocols: [ HTTPS, HTTP ]
baseUri: https://{sub}.paw.cloud/
baseUriParameters:
  sub:
    type: string
    enum: [ 'echo', 'app' ]
/helloworld: # optional resource
  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            type: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: # example how a response looks like
              {
                "message": "Hello world"
              }

```

**Expected Behavior:**
```js
const test = raml.loadApiSync('input.raml')
assert(test.protocols() === [ 'HTTPS', 'HTTP' ], true)
assert(test.resources()[0].methods()[0].protocols() === [], true)
```

**Actual Behavior:**
```js
const test = raml.loadApiSync('input.raml')
assert(test.protocols() === [ 'HTTPS', 'HTTP' ], true)
assert(test.resources()[0].methods()[0].protocols() === [ 'HTTPS' ], true)
```

**Why this is an issue:**
It is impossible to tell If we have voluntarily restricted the use of `/helloworld get` to only `https` or if that is because our baseUri protocol is `https`

**Comment by KonstantinSviridov** [comment]
Hi, @JonathanMontane 

By the parser by default calculates some of the unspecified values, and `protocols` value is among them. In order to preven the parser from doing it, you should set the [attributeDefaults](https://raml-org.github.io/raml-js-parser-2/interfaces/_src_raml1_wrapped_ast_parsercoreapi_.options.html#attributedefaults) option to `false`:
``` javascript
const test = raml.loadApiSync('input.raml', {attributeDefaults: false})
```

Regards, Konstantin

**Comment by JonathanMontane** [comment]
@KonstantinSviridov thanks for the info. What was the rationale behind having the attributeDefaults set to true by default ? Also, is there any place in the documentation where I could have easily found this ?

**Comment by JonathanMontane** [comment]
@KonstantinSviridov I would also argue that it might not be a good idea to include `protocols` in those calculations (as can be seen with this issue).

**Comment by sichvoge** [comment]
I think the parser follows what the specification actually states.

> If the protocols node is not explicitly specified, one or more protocols included in the baseUri node is used; if the protocols node is explicitly specified, the node specification overrides any protocol included in the baseUri node. The protocols node MUST be a non-empty array of strings, of values HTTP and/or HTTPS, and is case-insensitive.

**Comment by JonathanMontane** [comment]
@sichvoge how would you go and write multiple protocols in the baseUri ?

like so `{protocol}://......` ? (does not work as explained further below)

If so, what would be the purpose of the `protocols` field ?

If you consider this behavior to be according to the spec, does this mean that the spec requires to write the same protocols for EVERY methods ? I thought one of the main selling points of RAML was its low verbosity. This directly contradicts the purpose of the `protocol` field.

Additionally, if you define the baseUri like previously mentioned
```yaml
baseUri: {protocol}://www.example.com
baseUriParameters:
  protocol:
    type: string
    enum: [ 'https', 'http' ]
```
you get the following errors:
```js
const test = raml.loadApiSync('input.raml')
test.errors()
/*
[ { code: 'YAML_ERROR',
    message: 'JS-YAML: can not read a block mapping entry; a multiline key may not be an implicit key at line 4, column 18',
    path: 'input.raml',
    range: { start: [Object], end: [Object] },
    isWarning: false },
  { code: 'SCALAR_EXPECTED',
    message: 'Scalar is expected here',
    path: 'input.raml',
    range: { start: [Object], end: [Object] },
    isWarning: false },
  { code: 'PROPERTY_UNUSED',
    message: 'Base uri parameter unused',
    path: 'input.raml',
    range: { start: [Object], end: [Object] },
    isWarning: true } ]
*/
```

**Comment by KonstantinSviridov** [comment]
@JonathanMontane As for the errors, the starting `{` symbol of a string literal must be escaped or the whole literal must be quoted. I can't find the exact place in the YAML spec which says this, but [here](http://symfony.com/doc/current/components/yaml/yaml_format.html), for example, they require every string literal which contains a special character to be quoted.

Inluding protocols into calculations is part of accepted standard, and there must be truely strong reasons in order to change it.
