### ISSUE TITLE
[documentation] method.queryString() is not included in the html documentation?

### ISSUE THREAD

**Issue by JonathanMontane** [raml-org/raml-js-parser-2#696]
For some reason, `method.queryString` is not included in the html documentation provided with the parser.

![image](https://cloud.githubusercontent.com/assets/5136989/23864235/2d556678-0812-11e7-9f9c-e3fbcd3c5417.png)

**Comment by KonstantinSviridov** [comment]
Hi, @JonathanMontane 

You're probably looking at the RAML 0.8 `MethodBase` interface, and in RAML 0.8 there is no `queryString` property for methods.

As for RAML 1.0, `queryString` is on [its place](https://raml-org.github.io/raml-js-parser-2/interfaces/_src_raml1_artifacts_raml10parserapi_.methodbase.html#querystring)

Regards, Konstantin

**Comment by JonathanMontane** [comment]
That's it! Sorry about that.
