### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#7]
It seems that some of the dependencies make no sense for this package (for example, typescript). Please check which ones are actually used and remove the rest.

Thanks!

**Comment by ddenisenko** [comment]
Okay, this will be anyway performed while we create NPM package for the parser.

**Comment by juancoen** [comment]
Ok, thanks!

**Comment by shlomiassaf** [comment]
This is a ghost repo anyway, the source code is here, but its bundled so typescript will be useless anyway.

I think Typescript is part of the dependencies but there arent any .ts files :)

**Comment by sichvoge** [comment]
@ddenisenko what about that repo?

**Comment by ddenisenko** [comment]
That is done. We are also checking if we can remove more used dependencies to reduce the size.
