### ISSUE TITLE
Output raml file

### ISSUE THREAD

**Issue by drobison** [raml-org/raml-js-parser-2#702]
Is it possible to output a parsed api once it has been loaded in?  What I am looking to do is load in a fragmented raml and output a single flattened raml file.

**Comment by ddenisenko** [comment]
So, you want to serialize the API from memory back to RAML code? No, it is not possible at the moment.

**Comment by drobison** [comment]
Yes that is what I am trying to do.  The use case would be to utilize file fragments during development, yet still be able to upload a single RAML file to tooling that is able to interpret RAML, but not fragmented RAML.

**Comment by thenanox** [comment]
Also interested on this topic. Virtualization server from CA load RAML single files to check examples to create mock servers. 

Ive been investigating and it already exists something similar for previous parser https://github.com/mulesoft-labs/raml-object-to-raml, but it doesnt work in RAML 1.0

Also in https://github.com/raml-org/api-modeling-framework seems that "resolves" the model, but it doesnt handle properly data types on libraries.

Any estimation on this functionality?

**Comment by sichvoge** [comment]
AMF (API Modeling Framework) will be able to do that also. We are currently running sprints to finish the PROD version of that framework, but its hard to estimate at the moment. We do have a plan and we are looking into soon (probably next two months) rather than later.

I would probably wait till then. What do you think?

**Comment by thenanox** [comment]
ok thank you very much for the answer

i think is the best option too

**Comment by sichvoge** [comment]
Hence, I will close this issue as this is suspended with what we do around AMF. Happy to open it again if someone still thinks its important.
