### ISSUE TITLE
Body default type is 'object' which is incorrect

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#704]
As per spec, default body type [is 'any'](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#determine-default-types)
But the following RAML spec

```yaml
#%RAML 1.0
title: test
/test:
  post:
    body:
      application/json:
```
is serialized to JSON as (with unnecessary elements removed manually):

```json
{
    "title": "test",
    "resources": [
      {
        "methods": [
          {
            "body": {
              "application/json": {
                "name": "application/json",
                "type": [
                  "object"
                ]
              }
            },
            "method": "post"
          }
        ],
        "relativeUri": "/test"
      }
    ]
  }
```

There should be `"type": [ "any" ]`, but anyway, handling bodies in a special way is a bit strange. Why not having `string` type as default also for them?

**Comment by sichvoge** [comment]
You might want to ask that inside the spec repo directly and not inside the parser.

**Comment by sichvoge** [comment]
Can we close this then?

**Comment by KonstantinSviridov** [comment]
ok
