### ISSUE TITLE
Rename 'TCKDumper' to something more appropriate

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#708]
The dumper that is being called with `toJSON` is currently called `TCKDumper`. We should rename it to make it more clear what it is doing. The term "TCK" comes from our test suite, but we should probably not use it in this context.

What is the dumper doing at the moment? Matching the high-level nodes to a well-defined JSON object?

**Comment by KonstantinSviridov** [comment]
`TCKDumper` has been renamed to `jsonSerializer`
