### ISSUE TITLE
RAML-parser not able to parse JSON schemas with inner definitions

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#709]
Having a JSON schema defined that references other objects specified under "definitions" node. Parser is not able to parse it successfully. Then, examples compliant with the schema are marked as invalid as well
Check attached example.
[schemas_inner_definitions.zip](https://github.com/raml-org/raml-js-parser-2/files/893687/schemas_inner_definitions.zip)

**Comment by KonstantinSviridov** [comment]
Hi, @nmarinel01 !

Thanks for the report. The fix will be available in the next release.

Regards,
Konstantin

**Comment by nmarinel01** [comment]
Great Konstantin! Thanks!!!
