### ISSUE TITLE
Can't find type name for ArrayTypeDeclaration imported from library

### ISSUE THREAD

**Issue by jepatel** [raml-org/raml-js-parser-2#71]
Example:
-----
uses:
&nbsp;&nbsp;AnimalLibrary: !include Animals.raml

types:
&nbsp;&nbsp;Zoo:
&nbsp;&nbsp;&nbsp;type: object
&nbsp;&nbsp;&nbsp;properties:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;animal: AnimalLibrary.Animal
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;animals: AnimalLibrary.Animal[]

---

For the animal property of type Zoo (ObjectTypeDeclaration):
  typeDeclaration.runtimeType().superTypes[0].nameId() returns "Animal", (which is GOOD)

However, for the animals property of type Zoo (ArrayTypeDeclaration):
  typeDeclaration.runtimeType().componentType().superTypes[0].nameId() returns "ValueType"
  and
  typeDeclaration.runtimeType().componentType().nameId() returns "StringType"

How do I figure out the type for the property animals?  Things seem to work fine if the Animal type isn't defined in a library.  Is this a bug, or am I doing something wrong?

**Comment by ddenisenko** [comment]
This is a bug. Thanks a lot for reporting it!

**Comment by jepatel** [comment]
Any idea of when you think this would be fixed?  I had to stop using libraries for now.

**Comment by ddenisenko** [comment]
I guess it will be fixed in 1-1.5 weeks. Type system is going to get some fixes soon.

**Comment by nnance** [comment]
@ddenisenko what's the status of this bug now that release 0.2.x is out?

**Comment by ddenisenko** [comment]
JS code:

```
    var zooTypeDeclaration = api.types()[0];
    var animalTypeDeclaration = zooTypeDeclaration.properties()[0];
    console.log("animal type name: " +
        animalTypeDeclaration.runtimeType().superTypes()[0].nameId())

    var animalsTypeDeclaration = zooTypeDeclaration.properties()[1];
    console.log("animals component type name: " +
        animalsTypeDeclaration.runtimeType().componentType().nameId())
```

Output:

```
animal type name: Animal
animals component type name: Animal
```

Looks fine for me.

Now, instead of analyzing types hierarchy and knowing how it works, we can use appropriate helpers of ITypeDefinition:

JS code:
```
var zooTypeDeclaration = api.types()[0];
    var zooProperties = zooTypeDeclaration.properties();

    zooProperties.forEach(function(propertyType) {
        if (propertyType.runtimeType().hasArrayInHierarchy()) {
            console.log("Found an array of: " +
                propertyType.runtimeType().arrayInHierarchy().componentType().nameId())
        }
        else if (propertyType.runtimeType().isGenuineUserDefinedType()) {
            console.log("Found user-defined type: " +
                propertyType.runtimeType().genuineUserDefinedType().nameId())
        }
    })
```

Output:
```
Found user-defined type: Animal
Found an array of: Animal
```

**Comment by nnance** [comment]
@ddenisenko I haven't validated your example above but what I have found is that isGenuineUserDefinedType returns true in all cases.  This includes properties defined as string, boolean, integer, number, etc.  This is on release 0.2.6.  Is this a known issue?  Also are you guys open to receive pull requests for bug fixes?

**Comment by petrochenko-pavel-a** [comment]
Hi @nnance 
I also tested your sample and it works fine for me with a small correction:
```raml
#%RAML 1.0
title: Test
uses:
  AnimalLibrary:  Animals.raml
types:
  Zoo:
   type: object
   properties:
     animal: AnimalLibrary.Animal
     animals: AnimalLibrary.Animal[]
```
(please note that you should not use `!include` with uses in RC2)

>Is this a known issue?
No, thanks for bringing this in, I have just fixed issue in the type system so nominal transformations of built in types are not user types any more.

>Also are you guys open to receive pull requests for bug fixes?
Yes , sure. 

Closing this for now, please feel free to reopen if you see something which is related. (note `isGenuineUserDefinedType` fix is in rc2 branch of type system at this moment)
Regards,
Pavel

**Comment by ddenisenko** [comment]
I am not seeing isGenuineUserDefinedType fixed in RC2.

```RAML
#%RAML 1.0
title: Book Library API
types:
    TestType:
        properties:
         name: string

/resource:
    get:
        body:
            application/json:
                type: TestType
```

JS:
```js
var bodyType = api.resources()[0].methods()[0].body()[0];
console.log(bodyType.runtimeType().isGenuineUserDefinedType())
```

Output:
```
true
```

The output should be false.
Note: `bodyType.runtimeType().genuineUserDefinedType()` look to be returning a correct type, needs more testing though.

**Comment by ddenisenko** [comment]
Should be better now (RC2 branch, the change will be published to beta stream in several days).

Note that genuineUserDefinedType() is not a way to differentiate "object" types from arrays or unions. It is a way to differentiate genuine user defined types from the synthetic ones, in other words it is a way to collapse hierarchy.

So when analyzing hierarchy, arrays, unions, external types etc should be check first, and only then, when you know it is a "general" kind of type, genuineUserDefinedType() helpers should be used to get rid of synthetic types.

I also changed helper names and meanings to be with accordance to other similar helpers:
`isGenuineUserDefinedType()` returns whether this particular type at hands is genuine.
`hasGenuineUserDefinedTypeInHierarchy()` check if there is a genuine type in hierarchy.
`genuineUserDefinedTypeInHierarchy()` returns the closest genuine type in hierarchy.

So the JS code above should look like:

```
    var zooTypeDeclaration = api.types()[0];
    var zooProperties = zooTypeDeclaration.properties();

    zooProperties.forEach(function(propertyType) {
        if (propertyType.runtimeType().hasArrayInHierarchy()) {
            console.log("Found an array of: " +
                propertyType.runtimeType().arrayInHierarchy().componentType().nameId())
        }
        else if (propertyType.runtimeType().hasGenuineUserDefinedTypeInHierarchy()) {
            console.log("Found user-defined type: " +
                propertyType.runtimeType().genuineUserDefinedTypeInHierarchy().nameId())
        }
    })
```
