### ISSUE TITLE
Parsing a raml library file should also support ´lib.expand(true)´ method

### ISSUE THREAD

**Issue by carowright** [raml-org/raml-js-parser-2#710]
There are use cases where you may want to parse a Library raml file, and in this case the ´expand´ method would be very useful.
Our particular use case is from the API console, when viewing the documentation for a Library the types from it are shown, and we are having issues due to the lack of library expansion in this case.

**Comment by KonstantinSviridov** [comment]
Hi, @carowright 

Now in the "develop" branches set Library has an expand() method which contributes all its dependencies from other libraries.
The method will be available in the "master" branches set with the next release.

Regards,
Konstantin

**Comment by carowright** [comment]
Hi @KonstantinSviridov. 

Is there an estimated date for the release?

Thanks
