### ISSUE TITLE
Compare raml-1-parser output to 0.8 parser output

### ISSUE THREAD

**Issue by ddenisenko** [raml-org/raml-js-parser-2#711]
For API Platform service to check if there are important differences

**Comment by KonstantinSviridov** [comment]
As a result of comparison, the following tickets have been created:

https://github.com/raml-org/raml-js-parser-2/issues/714
https://github.com/raml-org/raml-js-parser-2/issues/715
https://github.com/raml-org/raml-js-parser-2/issues/716
https://github.com/raml-org/raml-js-parser-2/issues/717
https://github.com/raml-org/raml-js-parser-2/issues/718
https://github.com/raml-org/raml-js-parser-2/issues/721
