### ISSUE TITLE
Improve positioning for errors in JSON

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#723]
JSON errors can be divided into three groups:

1. JSON syntax errors
2. JSON schema syntax errors
3. Example vs schema validation errors

All these errors should piont to actual places whrere error occurs.

**Comment by ddenisenko** [comment]
Please expand this even more and create a ticket for each general case.

**Comment by KonstantinSviridov** [comment]
Related issue https://github.com/raml-org/raml-js-parser-2/issues/727

**Comment by KonstantinSviridov** [comment]
Related issue https://github.com/raml-org/raml-js-parser-2/issues/728
