### ISSUE TITLE
When RAML includes a schema that references another schema, enable $ref via schema key

### ISSUE THREAD

**Issue by dcrossleyau** [raml-org/raml-js-parser-2#726]
The attached set of example files do "!include" a JSON schema file in another directory,
and that schema refers to another schema in a separate file.

There are two methods for the parent schema to refer to the second schema:

A) By schema key -- `"$ref": "petSchema"` (i.e. As declared in the top-level RAML file. See below.)

B) By filename -- `"$ref": "pet.json"`

Method A is successful when using "raml-for-jax-rs".

However it fails when using tools based on "raml-js-parser-2" (e.g. api-workbench, raml-cop).

Method B is successful with "raml-js-parser-2".

However it fails with "raml-for-jax-rs". 
This seems to be a long-standing problem, e.g. see [#202](https://github.com/mulesoft-labs/raml-for-jax-rs/issues/202) and related ones.

Perhaps "raml-js-parser-2" can solve this dilemma by also enabling Method A.

[pets.zip](https://github.com/raml-org/raml-js-parser-2/files/953751/pets.zip)
e.g. in RAML ...
```
schemas:
  - petSchema: !include ../schema/pet.json
  - petsSchema: !include ../schema/pets-key.json
```

and in the parent schema pets-key.json ...
```
        "$ref": "petSchema"
```

Note that z-schema does not facilitate this, which seems reasonable because the key is declared in the RAML file. Maybe raml-js-parser-2 can do so at a higher level.

**Comment by KonstantinSviridov** [comment]
Hi @dcrossleyau 

The RAML 1.0 and 0.8 specifications do not claim names of schemas (or types for 1.0) being usable in JSON schemas, thus, the parser does not support it. Instead it supports JSON references standard. According to it, valid `$ref` value is a URI which points to one of the following things:

1. Some JSON schema file, e.g.
```
{ "$ref" : "https://www.example.com/schema.json" }
{ "$ref" : "../someDir/schema.json" }
```

2. A fragment of some JSON schema file, e.g.
```
{ "$ref" : "https://www.example.com/schema.json#/definitions/MyType" }
{ "$ref" : "../someDir/schema.json#/definitions/MyType" }
```

3. A fragment of the same file where the reference occurs, e.g.
```
{ "$ref" : "#/definitions/MyType" }
```

Regards,
Konstantin

**Comment by dcrossleyau** [comment]
Thanks for the clear description. That helps to put this and related issues to rest.

So the focus is on [raml-for-jax-rs/issues/202](https://github.com/mulesoft-labs/raml-for-jax-rs/issues/202) being able to handle Method #B.
