### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by gingermusketeer** [raml-org/raml-js-parser-2#73]
Hi,

I noticed that there were a few issues with the `help wanted` tag. How do i go about this?

It appears as though the source code for this project is held elsewhere and a compiled version is committed into this project. Is that correct?

Keen to help get RAML 1.0 parsers to a point where I can use them in my daily work.

**Comment by ddenisenko** [comment]
>I noticed that there were a few issues with the help wanted tag. How do i go about this?
This tag simply means that the ticket is not classified as a bug or enhancement request, but as a question from a user to answer.

>It appears as though the source code for this project is held elsewhere and a compiled version is committed into this project. Is that correct?

Yes. The parser is developed in TypeScript. And its not only compiled, the parser is also partially generated from something we call "Definition System". The original source code and the generator are planned to be open sourced in some time.

**Comment by gingermusketeer** [comment]
@ddenisenko Many thanks for the info

**Comment by robvanmieghem** [comment]
@ddenisenko Any idea on the timeframe of open sourcing the code? I wanted to work on issue #65 but indeed noticed that the real code is missing.

**Comment by ddenisenko** [comment]
Well, I cant really make any commitments with that regard, can just say that the timeframe is measured in months, not years :)

**Comment by sichvoge** [comment]
@robvanmieghem we are currently working on different iterations to make the open source version available as soon as possible and we are already making some compromises to do that quickly ;) 

Overall, the plan is to do that before we start to implement changes for RC2 to have something for the community not in years as Denis said.

**Comment by sichvoge** [comment]
@robvanmieghem the code is open sourced now ;)

**Comment by robvanmieghem** [comment]
@sichvoge I noticed, super!

**Comment by petrochenko-pavel-a** [comment]
`Contributing` section added to the README.

Closing issue for now.

Regards,
Pavel
