### ISSUE TITLE
queryString & queryParameters mutual exclusive error message

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#730]
![image](https://cloud.githubusercontent.com/assets/498114/25815420/3474be9a-3418-11e7-846f-0f5a288f9bd9.png)

The error message is not very clear. The spec explicitly states that queryString and queryParameter is mutual exclusive and we should call that out.

**Comment by KonstantinSviridov** [comment]
Ok, now it is going to be

![qqmutex](https://user-images.githubusercontent.com/6206034/27599556-561eb51c-5b93-11e7-82ee-9629bea3af7e.jpg)
