### ISSUE TITLE
Can't differentiate between integer and number when looking at runtimeType

### ISSUE THREAD

**Issue by jepatel** [raml-org/raml-js-parser-2#74]
Error scenario:

types:
  Foo:
  properties:
    bar: integer[]

typeDeclaration.runtimeType().componentType() for Foo returns NumberType when bar is both number[] and integer[]

**Comment by ddenisenko** [comment]
Same applies to a case without an array. Clearly a bug. It should be either IntegerType, or NumberType with appropriate format facet.

**Comment by petrochenko-pavel-a** [comment]
pushed to RC2. (please not that fix depends from the latest changes to ramp-definition-system which are pushed to cleanup branch).

Regards,
Pavel
