### ISSUE TITLE
Parsing fails with unclear "Specifying unknown facet error"

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#748]
When parsing the attached project, I get a "Specifying unknown facet error" at baseUri line though the content of that line is correct.
![image](https://cloud.githubusercontent.com/assets/19980188/26555449/7e2098f8-446b-11e7-9159-47426d604b51.png)

The problem is that another file of the project (a dataType fragment) is also specifying a baseUri node that is invalid in that context.

I think that error at root raml has to include information about the file that is causing parsing to fail.

Attaching project with an example.
[BaseUri error message.zip](https://github.com/raml-org/raml-js-parser-2/files/1036171/BaseUri.error.message.zip)

**Comment by KonstantinSviridov** [comment]
Hi, @nmarinel01 

Actually, the error does contain information about the file which causes the error:
```
"errors": [
    {
      "code": "UNKNOWN_FACET",
      "message": "Specifying unknown facet: 'baseUri'",
      "path": "types/contract.raml",
      "range": {
        "start": {
          "line": 1,
          "column": 0,
          "position": 20
        },
        "end": {
          "line": 1,
          "column": 7,
          "position": 27
        }
      }
    }
  ]
```
The problem is that it does not provide any trace object which points to the place in `api.raml` where the fragment is referenced.

**Comment by KonstantinSviridov** [comment]
Now the error object is 
```
"errors": [
    {
      "code": "UNKNOWN_FACET",
      "message": "Specifying unknown facet: 'baseUri'",
      "path": "types/contract.raml",
      "range": {
        "start": {
          "line": 1,
          "column": 0,
          "position": 20
        },
        "end": {
          "line": 1,
          "column": 7,
          "position": 27
        }
      },
      "trace": [
        {
          "code": "UNKNOWN_FACET",
          "message": "Specifying unknown facet: 'baseUri'",
          "path": "api.raml",
          "range": {
            "start": {
              "line": 6,
              "column": 2,
              "position": 144
            },
            "end": {
              "line": 6,
              "column": 10,
              "position": 152
            }
          }
        }
      ]
    }
  ]
```

Thanks for your report, @nmarinel01

**Comment by nmarinel01** [comment]
Thanks @KonstantinSviridov ! Which release will include this fix ?
Regards
Nati
