### ISSUE TITLE
Confusing error message when !include is missing

### ISSUE THREAD

**Issue by nmarinel01** [raml-org/raml-js-parser-2#749]
Given the following raml project we get an error message that does not give the correct information to solve the problem. Message should lead to add the !include reserved word but instead of this, gives a compliance error.

![image](https://cloud.githubusercontent.com/assets/19980188/26595926/510eae44-4543-11e7-98c7-fb6850d8a003.png)

Attached project reproduces the problem.
[include-error-message.zip](https://github.com/raml-org/raml-js-parser-2/files/1039158/include-error-message.zip)

**Comment by nmarinel01** [comment]
Hi @KonstantinSviridov !
Is this the error message that we'll get if !include node is not provided ?
![image](https://user-images.githubusercontent.com/19980188/26935103-7694b26c-4c41-11e7-8a50-002bf586ea9a.png)
Regards

**Comment by KonstantinSviridov** [comment]
Hi, @nmarinel01 !

In fact you should get
![missing-include](https://user-images.githubusercontent.com/6206034/26940143-cf97e4c6-4ca3-11e7-9162-08c53d488218.jpg)

But the published 1.1.24 parser produces your message for some reason.

**Comment by sichvoge** [comment]
Hi Konst. How do you test that the include is missing? How does the parser differentiate between a simple string or an included file?

**Comment by KonstantinSviridov** [comment]
Hi, Christian

This is how it works:
1. The parser intercepts an error about JSON parsing failute or scalar instead of object occurence.
2. Then it checks if the scalar value is a URI with one of the following extensions: ".raml", ".yaml", ".yml", ".json", ".xml".
3. If the check succeeds, the parser decides that the string value is an URI that has been supposed to be used with !include tag and generates another error istead of the intercepted one.

**Comment by nmarinel01** [comment]
Thanks @KonstantinSviridov !
Which release is including this ?

**Comment by KonstantinSviridov** [comment]
For now it is only available in the 'develop' branch. It will be published with the next release.

**Comment by sichvoge** [comment]
Thanks, @KonstantinSviridov. 

So in the following case, I don't get an error that the include tag is missing right?

```yaml
type: string
example: examples/test.json
```

**Comment by KonstantinSviridov** [comment]
@sichvoge yes, this example would not cause any error.

**Comment by sichvoge** [comment]
Perfect, thank you Konst! 

Did we test this in different scenarios with XML, and YAML as well? Also what happens if you just do the following:

```
application/json:
  example: examples/test.json
```

**Comment by KonstantinSviridov** [comment]
As for
```yaml
application/json:
  example: examples/test.json
```
in 0.8 you get an error, and in 1.0 you do not as the default type in 1.0 is "string".

Yes, we have some XML tests:
https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/test/data/TCK/raml-1.0/InvalidIncludeTags/test007/api.raml
https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/test/data/TCK/raml-0.8/InvalidIncludeTags/test007/api.raml

And some RAML tests which do not involve examples:
https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/test/data/TCK/raml-0.8/InvalidIncludeTags/test005/api.raml
https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/test/data/TCK/raml-1.0/InvalidIncludeTags/test005/api.raml
https://github.com/raml-org/raml-js-parser-2/blob/develop/src/raml1/test/data/TCK/raml-1.0/InvalidIncludeTags/test008/api.raml

We could also add some YAML, YML tests and RAML tests for examples

**Comment by sichvoge** [comment]
Yes, please add some for YAMLs and RAMLs like the following:

```yaml
application/json:
  type: object
  properties:
    message: string
  example: ./examples/message.yaml
```

or even

```yaml
application/json:
  type: object
  properties:
    message: string
  example: ./examples/message.raml
```

YAML, RAML, YML :D

**Comment by sichvoge** [comment]
Just realized that what happens if you actually include a string value? For example:

```yaml
application/json:
  example: examples/test.txt
```

**examples/test.txt**
```
Hello World!
```

In this case, your intention was to include, but you forgot it. Should we actually try to support these cases when there is just a string? IMHO, that's a corner case here and I would need try to validate that. Happy to hear other opinions.
