### ISSUE TITLE
Name spaces for libraries?

### ISSUE THREAD

**Issue by jepatel** [raml-org/raml-js-parser-2#75]
Example:

foo.api uses baselibrary.raml  with name: Base
bar.api uses baselibrary.raml with name: BaseLibrary

I want my code generation tool to generate classes/types for baselibrary.raml using the same namespace (e.g. I don't want to have 2 copies of the same classes in my app).  Does RAML support a way to do this?  Alternatively, I was thinking I could potentially use the name of the library file as it's name space...

**Comment by ddenisenko** [comment]
Well, namespaces are local to a file, which uses a library. The only identifier of a library, which is kind of universal is library file's name or path.

**Comment by petrochenko-pavel-a** [comment]
File path/names are also not guaranteed to be good enough to unique identify content of the library, so
as for me the correct way of dealing this is to create some annotation type named for example `Namespace` and then annotate your libraries with annotation (Namespace): "com.somecompany.Base"

P.S. Hope that we will publish some common annotation types as a libraries at some moment.

Closing this issue for now as not parser related. Please feel free to reopen if you have any further questions or suggestions.

Regards,
Pavel
