### ISSUE TITLE
Timeout error when an example contains a long word

### ISSUE THREAD

**Issue by tomasmateus** [raml-org/raml-js-parser-2#754]
In the following RAML 0.8 api, there is an `example` with a word of length 180. When parsing this api in a test, the parser remains working for minutes, until eventually the test exits with timeout exception. I've analyzed the case and figured out that when a single word (no spaces, just chained characters) has length greater than 68/69/70 approximately, the parser's response time begins to increase exponentially.

Example with word of 180 chars:

```
responses:
  200:
    body:
      application/json:
          example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJ0b2tlbiI6ImU2ZjZjZDJmNjMxNWVkMmM2MjIyNjdjNDU4ZTE5YzE2IiwiaWQiOiIxOWxxNDA5NG16bmoiLCJmaXJzdF9uYW1lIjoiRmVsbGlwZSIsImxhc3RfbmFtZSI6IkJyaXRvIn0."
```

**Comment by KonstantinSviridov** [comment]
Thanks for the report, @tomasmateus 

The fix will be available in the next release.

Regards,
Konstantin

**Comment by tomasmateus** [comment]
Great, thanks @KonstantinSviridov

**Comment by tomasmateus** [comment]
@KonstantinSviridov I'm using new version 1.1.26 and don't seem to see this bug fixed, am i wrong?
The complete file would be:
```
#%RAML 0.8
title: Token API
/token:
  post:
    responses:
      200:
        body:
          application/json:
            example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJub"
```
