### ISSUE TITLE
Parser wrongly complain about non-existing subtypes

### ISSUE THREAD

**Issue by dreamflyer** [raml-org/raml-js-parser-2#759]
in api.raml:

![screen shot 2017-06-14 at 3 47 23 pm](https://user-images.githubusercontent.com/712787/27126309-39cfd78c-5121-11e7-8b9a-ecc8d8591012.png)

but error is wrong, since Mammal type present in api.

[Archive.zip](https://github.com/raml-org/raml-js-parser-2/files/1074186/Archive.zip)

**Comment by KonstantinSviridov** [comment]
Hi, @dreamflyer!

The fix is going to be available in the next release.
