### ISSUE TITLE
Parser does incorrectly validate resource type parameter for a key node

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-js-parser-2#760]
The following RAML should be valid in 1.0 (it is in 0.8):

```yaml
#%RAML 1.0
title: Parameterizing media type gives "invalid media type" error
resourceTypes:
  thingy:
    get:
      responses:
        200:
          body:
            <<mediaType>>:
              type: file
/books:
  type:
    thingy:
      mediaType: application/json
```

**Comment by sichvoge** [comment]
Both tests in the TCK fails [here](https://github.com/raml-org/raml-tck/tree/wip/2.0.0/tests/semantic/raml-1.0/patterns/parameter).

**Comment by KonstantinSviridov** [comment]
Thanks for the report, Christian

Passing both tests have been fixed

**Comment by sichvoge** [comment]
can you state when this will be released, please!

**Comment by KonstantinSviridov** [comment]
This question should be discussed with @ddenisenko as he is the one responsible for releases.
