### ISSUE TITLE
validation issue

### ISSUE THREAD

**Issue by WAvdBeek** [raml-org/raml-js-parser-2#771]
if the example is an string like: "DEBUG"
and the json draft 04 schema is 
{
"id": "http://api.reference/configLogLevel.schema",
"$schema": "http://json-schema.org/draft-04/schema#",
"description" : "Log Level",
"type": "string",
"enum": [ "ALL", "ERROR", "WARN", "INFO", "DEBUG", "NONE" ]
}
the tool should validate as correct.
e.g. check this with
http://www.jsonschemavalidator.net/

**Comment by KonstantinSviridov** [comment]
Hi @WAvdBeek !

Thanks for your report. The fix will be available with the next parser release.

Regards,
Konstantin

**Comment by WAvdBeek** [comment]
Thanks!
