### ISSUE TITLE
The parser is showing "Unused parameter" as error when it should be a warning

### ISSUE THREAD

**Issue by marinarv** [raml-org/raml-js-parser-2#774]
The js parser says that it is failing due to an unused parameter error (design center and APIkit console in Studio), while if I use java parser this kind of error does not appear because is a warning (RAML editor in Studio). This behavior shows some inconsistency between the two parsers. See the attached images in order to have more details.
<img width="1431" alt="screen shot 2017-07-10 at 2 25 51 pm" src="https://user-images.githubusercontent.com/28363452/28073780-314b9f76-662d-11e7-8b7e-1e0f6df6a103.png">

![2017-06-22_1312](https://user-images.githubusercontent.com/28363452/28073919-a075688c-662d-11e7-827c-f21bc219be88.png)

**Comment by KonstantinSviridov** [comment]
Hi, @marinarv !

I can not reproduce your case from the first attempt -- with 1.1.26 parser and both 1.0 and 0.8 RAML versions.

Morower, at [https://anypoint.mulesoft.com](https://anypoint.mulesoft.com) I see warnings:

![unused-uri-parameter](https://user-images.githubusercontent.com/6206034/28082566-052bd486-669d-11e7-99f4-da5cb10de2a1.jpg)

May it happen that your tools utilize outdated parser?
If you're sure about your parser version, please, provide an example.

Regards,
Konstantin

**Comment by marinarv** [comment]
Hi Konstantin!
Yes, I can provide you the version where I can reproduce de issue. With the v1.1.26 is happening but with other example, maybe the issue is that the name of the error "unused parameter" is not correct in this case, but there in the attached image you could see that the parameter "exampleItem" shows the error.

<img width="965" alt="screen shot 2017-07-11 at 3 48 29 pm" src="https://user-images.githubusercontent.com/28363452/28084907-84150620-6650-11e7-8d1e-56ecdeefd11a.png">

Let me know if you need more information.
Thanks!
Regards, 
Marina.

**Comment by KonstantinSviridov** [comment]
Ah I see, it's about template parameters. Thank you!

**Comment by KonstantinSviridov** [comment]
Thanks for you report, @marinarv 

The fix will appear in the next release.

Regards,
Konstantin

**Comment by marinarv** [comment]
Great! Thanks!

Regards,
Marina.
