### ISSUE TITLE
1.1.27 is not importable

### ISSUE THREAD

**Issue by cebor** [raml-org/raml-js-parser-2#775]
```javscript
var raml1Parser = require('raml-1-parser');
```

Returns following Error: 

```log
Error: Cannot find module 'raml-1-parser'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at repl:1:19
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
```

**Comment by valdemon** [comment]
Confirm that.
Looks like the `npm` package misses some contents:
```shell
cat node_modules/raml-1-parser/package.json | grep main
  "main": "dist/index.js",

ls -go node_modules/raml-1-parser
total 32
-rw-r--r--  1   3717 Feb  1 04:53 README.md
drwxr-xr-x  3    102 Dec 13  2016 documentation
drwxr-xr-x  3    102 Dec 13  2016 examples
-rw-r--r--  1    557 Apr  7  2016 license.txt
-rw-r--r--  1   5061 Jul 14 11:11 package.json
drwxr-xr-x  3    102 Jul 13 21:43 resources
drwxr-xr-x  7    238 Jul 14 11:11 test
drwxr-xr-x  4    136 Jul 14 11:11 web-tools
```

**Comment by postatum** [comment]
I have this issue too.

**Comment by sichvoge** [comment]
Sorry about that guys. We investigate.

**Comment by simon-scherzinger** [comment]
looks like this is happening every other version? #755 :-(

**Comment by sichvoge** [comment]
Yes, and we are immensely sorry about that happening again. We will investigate why it happens and set things in place to avoid in in the future.

**Comment by wgil82** [comment]
i just spent an hour trying to figure this one out lol.

**Comment by ddenisenko** [comment]
The fix will be published in about 1-1.5 hours.

**Comment by WoZ** [comment]
experiencing the same problem

**Comment by cdierkens** [comment]
Did someone publish with an NPM version less than 4? https://github.com/npm/npm/issues/8510

**Comment by WAvdBeek** [comment]
is there an version stable version that i can use..
e.g. i tried 1.2.6 and see the same issue that the dist directory is missing.

**Comment by ddenisenko** [comment]
1.1.28 is published, please use it.

**Comment by ddenisenko** [comment]
>Did someone publish with an NPM version less than 4? npm/npm#8510
Yes, NPM with version less than 4 was used. Why do you think the mentioned issue is related?
