### ISSUE TITLE
Default displayName is missing

### ISSUE THREAD

**Issue by xaka** [raml-org/raml-js-parser-2#78]
As per spec, `displayName` value should be equal to property name of resource, method, query parameter, etc. unless explicitly provided.

RAML:

```yaml
#%RAML 1.0
baseUri: http://localhost:8080/
/api:
  /pets:
    get:
      description: List pets ordered by name.
      queryParameters:
        max:
          type: integer
          description: Max page size, useful for paging. Default is `200`.
          required: false
      responses:
        200:
          description: Pets ordered by name.
          body:
            application/json:
```

JSON:

```json
{
  "baseUri": "http://localhost:8080/",
  "/api": {
    "/pets": {
      "get": {
        "description": "List pets ordered by name.",
        "queryParameters": {
          "max": {
            "type": "integer",
            "description": "Max page size, useful for paging. Default is `200`.",
            "required": "false"
          }
        },
        "responses": {
          "200": {
            "description": "Pets ordered by name.",
            "body": {
              "application/json": ""
            }
          }
        }
      }
    }
  }
}
```

**Comment by ddenisenko** [comment]
Three issues here:
1) title needs to be added for having no parsing errors.
2) toJSON should not be used to convert RAML AST to JSON. Instead, RAML AST should be used directly.
3) As stated here: https://raml-org.github.io/raml-js-parser-2/interfaces/_raml1_wrapped_ast_parsercore_.options.html , attributeDefaults setting needs to be  enabled to get attribute defaults. This is a subject to change at the next release, defaults will be always visible, instead there will be available metadata methods to see if something is a default or not.

**Comment by petrochenko-pavel-a** [comment]
`displayName` value default is inserted  with  default `toJSON` options now. So closing this issue as not relevant any more.
