### ISSUE TITLE
Parsing of `<<param>>.<<param>>[]` type

### ISSUE THREAD

**Issue by AnatolyRugalev** [raml-org/raml-js-parser-2#792]
Hi there

I just got an issue with transforming my RAML to HTML and looks like this problem is related to this project.

Reproducing RAML:

```raml
#%RAML 1.0
---
version: v2
mediaType: [ "application/json" ]
uses:
  app: libraries/app.raml
resourceTypes:
  collection:
    description: Collection of available <<resourcePathName>>
    get:
      description: Get a list of <<resourcePathName>>
      queryParameters:
        page:
          description: "Page number"
          example: 1
          required: false
          type: integer
        per_page:
          description: "Number of elements per page"
          example: 25
          required: false
          type: integer
      responses:
        200:
          body: "<<resourcePathName|!singularize>>.<<resourcePathName|!singularize|!uppercamelcase>>[]"
    post:
      description: Add a new <<resourcePathName|!singularize>>
      body: "<<resourcePathName|!singularize>>.<<resourcePathName|!singularize|!uppercamelcase>>Create"
      responses:
        200:
          body: "<<resourcePathName|!singularize>>.<<resourcePathName|!singularize|!uppercamelcase>>"
/apps:
  type: collection
```

Problem is in `"<<resourcePathName|!singularize>>.<<resourcePathName|!singularize|!uppercamelcase>>[]"` expression. Somehow it appears as `appApp`, but I expected to see `app.App[]`.

Is this a parsing issue? Thanks in advance

UPD: `<<resourcePathName|!singularize>>.<<resourcePathName|!singularize|!uppercamelcase>>` works as expected

UPD2: if it helps somehow, I found that `<<resourcePathName|!singularize>>.App[]` works fine, but `app.<<resourcePathName|!singularize|!uppercamelcase>>[]` doesn't

**Comment by KonstantinSviridov** [comment]
Thanks for your report, @AnatolyRugalev !

The fix is now available in the "develop" branches set and is going to be merged into "master" during in next release.

Regards,
Konstantin

**Comment by AnatolyRugalev** [comment]
Great! Thanks for such a quick response!
