### ISSUE TITLE
how to extract and modify the security schemes.

### ISSUE THREAD

**Issue by NandaBalakrishnan** [raml-org/raml-js-parser-2#801]
there is no method available to extract the security schemes and modify the existing schemes.

**Comment by KonstantinSviridov** [comment]
Hi, @NandaBalakrishnan 

The way of extracting security schemes depends on whether you prefer working with AST or JSON representation.

For example, [`loadApi`](https://github.com/raml-org/raml-js-parser-2/blob/master/src/index.ts#L140) and [`loadApiSync`](https://github.com/raml-org/raml-js-parser-2/blob/master/src/index.ts#L74) return instance of [`RAML 1.0 Api`](https://github.com/raml-org/raml-js-parser-2/blob/master/src/parser/artifacts/raml10parserapi.ts#L2028) or [`RAML 0.8 Api`](https://github.com/raml-org/raml-js-parser-2/blob/master/src/parser/artifacts/raml08parserapi.ts#L5) (wrapped into `Promise` in case of `loadApi`). Both these interfaces have `securitySchemes` methods which return security schemes AST.

If you prefer JSON, you should call the [`toJSON`](https://github.com/raml-org/raml-js-parser-2/blob/master/src/parser/highLevelAST.ts#L80) method for Api (please, pay attention to its `rootNodeDetails` option). Here are examples of `toJSON` result for [Instagram 0.8](https://github.com/raml-org/raml-js-parser-2/blob/master/src/parser/test/data/TCK/raml-0.8/Instagram/api-tck.json) and [Instagram 1.0](https://github.com/raml-org/raml-js-parser-2/blob/master/src/parser/test/data/TCK/raml-1.0/Others/Instagram1.0/api-tck.json). In both cases security schemes definitions are contained in `securitySchemes` field.

As for modification, the parser does not provide any ways for modifying RAML.

Regards,
Konstantin

**Comment by NandaBalakrishnan** [comment]
Hi, thanks for your reply!!!!!
1)I have RAML without security schemes, but i have to add security schemes is there any way to add security schemes at appropriate level and make all the resources secured by that security schemes.
2)I have RAML with security schemes and i have to modify the security with different security is ther any way to do with this api.

**Comment by KonstantinSviridov** [comment]
No, the parser does not provide any way to do it.
Moreover, it does not provide a way to serialize AST back to YAML text.
