### ISSUE TITLE
Why is property 'type' always an array??

### ISSUE THREAD

**Issue by posesop** [raml-org/raml-js-parser-2#803]
Hi all,

I wonder why the parser always parses the type as an array with one element, like this:

```

        "SomeType": {
          "name": "SomeType",
          "displayName": "SomeType",
          "type": [
            "string"
          ],
          "example": {
            "name": "somestring"
          }}
```

Is there any reason? I haven't found any case where the array has more than one type.

```
    "TypeReference10": {
      "oneOf": [
        {"type": "string"},
        {
          "type": "array",
          "items": {
             "type": "string"
          }
        },
        {"$ref": "#/definitions/Type"}
      ]
    }
```

Thanks

**Comment by KonstantinSviridov** [comment]
Hi @posesop !

The single type inheritence case is expressed by array for sake of similarity with the [mutiple inheritance case](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#multiple-inheritance).

Regards,
Kosntantin

**Comment by posesop** [comment]
Oh right, I forgot about multiple inheritance because I don't use it in my apis.

All clear,
Thanks.
