### ISSUE TITLE
Do not load schemas/examples while parsing RAML

### ISSUE THREAD

**Issue by dpfg** [raml-org/raml-js-parser-2#806]
Hi,

Is there a way to ask parser to not load examples and schemas !included into the RAML 0.8? I can't find a way in current LoadOptions.
```
expandLibraries: false,
expandTypes: false,
expandExpressions: false,
typeReferences: false,
```
None of them are working.

**Comment by ddenisenko** [comment]
No, there is no such way.

**Comment by dpfg** [comment]
Is there a plan to support it?
