### ISSUE TITLE
Used version of dependency marked has a security issue 

### ISSUE THREAD

**Issue by jenschude** [raml-org/raml-js-parser-2#808]
Please upgrade to a least marked: 0.3.9

**Comment by dcrossleyau** [comment]
Yes please. This is being reported by GitHub to lots of raml-1-parser using projects.

See the recent PR #807, which also lists the vulnerabilities.

There is a newer release "marked v0.3.12" since that, which would be useful.

**Comment by KonstantinSviridov** [comment]
Hi guys!

The  PR #807 has been merged to 'develop'. It is also going to be merged to 'master' during the next release.

Regards,
Konstantin
