### ISSUE TITLE
validateInstance passes for invalid examples against union types

### ISSUE THREAD

**Issue by tebs1200** [raml-org/raml-js-parser-2#81]
When attempting to validate against a union type using `validateInstance()`, the validation always passes.

 - An empty object will pass even if all the types in the union have required properties
 - An object with a parameter that doesn't exist in any of the union types will pass

I've put together a trivial example project that demonstrates the issue:

 - https://github.com/tebs1200/raml-parser-example

**Comment by petrochenko-pavel-a** [comment]
Pushed to RC2.
