### ISSUE TITLE
includes in resourceTypes do not get resolved correctly

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-js-parser-2#810]
Please,
See issue reported by api-console CLI tool user: https://github.com/mulesoft-labs/api-console-cli/issues/22
I believe it is parser's issue.

**Comment by KonstantinSviridov** [comment]
Hi @jarrodek 

I've responded in the original ticket.

Regards,
Konstantin

**Comment by KonstantinSviridov** [comment]
@jarrodek 
I've created a jira issue for improving the error message for this case
