### ISSUE TITLE
[Performance] Issue with `JSON.parse`

### ISSUE THREAD

**Issue by jarrodek** [raml-org/raml-js-parser-2#813]
There's a place in the code somewhere where the parser does something like this:
```javascript
function r(e){
  try{
    var t=JSON.parse(e);
    return t.$schema
  } catch(n){
   return!1
}
```
(this is from compiled source)

I made a jsPerf to test this approach and according to test results it's much, much faster to check first letter of the string for only two possible characters for valid JSON: `{` or `[`.
JSON can be only an object or an array so it make sense to test it first before invoking JSON parser.

See jsPerf here: https://jsperf.com/json-parse-test-vs-json-format-test
According to this you can save ~95% of the time while processing schemas.

**Comment by postatum** [comment]
Note that raml-js-parser-2 has been deprecated, the new official parser is [webapi-parser](https://github.com/raml-org/webapi-parser). Feel free to attempt to reproduce this issue with webapi-parser and report any issue you may have on that repository.

**Comment by jarrodek** [comment]
I am using AMF parser now.
