### ISSUE TITLE
Providing an object to validateInstance on a string type passes validation

### ISSUE THREAD

**Issue by tebs1200** [raml-org/raml-js-parser-2#82]
If you create a custom type and declare it's type as `string`, passing an object to it's `validateInstance()` method passes validation.

Passing a string that doesn't match the constraints fails validation as expected.

I've updated my simple example project to include a failing string validation:

 - https://github.com/tebs1200/raml-parser-example

**Comment by petrochenko-pavel-a** [comment]
Pushed to RC2.
