### ISSUE TITLE
Fix TypeScript typings

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-js-parser-2#88]
TypeScript supports having `typings` for NPM packages (see https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages). Using the `.d.ts` already emitted by TypeScript in the `parser-typings` would be the faster and correct way to do this, it just requires minor tweaks (make sure all the dependencies are typed and we set it in `package.json`).

I reviewed all the public `.d.ts` files in the package. There’s *only* two fixes required - remove all the `///` references (you should **never** be checking in the `typings/` generated files) and correct this import of `typescript` (https://github.com/raml-org/raml-js-parser-2/blob/master/parser-typings/src/raml1/definition-system/tsStructureParser.d.ts#L5) or make it a dependency.

**Comment by nnance** [comment]
+1.  I want to be able to use this project in my current typsecript project and in the current state it isn't working.  should it be?

**Comment by blakeembrey** [comment]
Yes, it should be. The fix is mentioned above, there's not much else that can be done until it's fixed.

**Comment by ddenisenko** [comment]
@nnance Please let me know, which errors you get when you use the current parser and its typings.

**Comment by nnance** [comment]
@ddenisenko sorry I forgot to respond but the problem was on my end with my TypeScript project setup.

**Comment by ddenisenko** [comment]
Okay, thank you.

**Comment by petrochenko-pavel-a** [comment]
Okey. so it seems that issue can be closed actually. (please let me know if I miss something)

Regards,
Pavel
