### ISSUE TITLE
Improve errors when coming from included file

### ISSUE THREAD

**Issue by blakeembrey** [raml-org/raml-js-parser-2#89]
That's the file I've included from, the position of `uses` (not even the included position) and a message that so ambiguous I actually don't know what's wrong.

```
example.raml (7, 1): Unknown node: items ../../../node_modules/raml-generator/annotations.raml
```

Edit: Also, it's two parser errors, but the same error twice.

**Comment by KonstantinSviridov** [comment]
Could you, please, provide an example?

Is it similar to
```
#%RAML 1.0

title: World Music API
baseUri: http://example.api.com/{version}
version: v1
uses:
  lib1: ./unexistingLib.raml
```
?

**Comment by blakeembrey** [comment]
I don't have time to recreate the replication. Feel free to reopen yourself when you run into it.
