### ISSUE TITLE
ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/expanderLL.js at compile.

### ISSUE THREAD

**Issue by n333ck** [raml-org/raml-js-parser-2#899]
Hi Guys. Currently, I am trying to use the library in an Angular application but I got an error at

> ng serve

while using oas-raml-converter. raml-1-parser is its dependency.
Can you please tell me if there is any walk around or solution for this?
Running under NPM 6.4.1, Node v10.15.3

ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/expanderLL.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/LowLevelASTProxy.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/overloadingValidator.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/builder.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/mutators.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/linter.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/jsyaml/json2lowLevel.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\jsyaml' ERROR in ./node_modules/raml-1-parser/dist/parser/jsyaml/jsyaml2lowLevel.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\jsyaml' ERROR in ./node_modules/raml-1-parser/dist/parser/tools/schemaModelGen.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\tools' ERROR in ./node_modules/raml-1-parser/dist/parser/wrapped-ast/wrapperHelper08.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\wrapped-ast' ERROR in ./node_modules/raml-1-parser/dist/parser/wrapped-ast/wrapperHelper.js Module not found: Error: Can't resolve '../../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\wrapped-ast' ERROR in ./node_modules/raml-1-parser/dist/parser/highLevelImpl.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser' ERROR in ./node_modules/raml-1-parser/dist/parser/apiLoader.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser' ERROR in ./node_modules/raml-1-parser/dist/parser/lowLevelAST.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser' ERROR in ./node_modules/raml-typesystem/dist/src/nominal-types.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-typesystem\dist\src' ERROR in ./node_modules/raml-typesystem/dist/src/index.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-typesystem\dist\src' ERROR in ./node_modules/raml-typesystem/dist/src/xmlio.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-typesystem\dist\src' ERROR in ./node_modules/raml-typesystem/dist/src/jsonSchemaValidation.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-typesystem\dist\src' ERROR in ./node_modules/raml-typesystem/dist/src/typesystem.js Module not found: Error: Can't resolve '../../resources/errorMessages' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-typesystem\dist\src' ERROR in ./node_modules/raml-definition-system/dist/index.js Module not found: Error: Can't resolve './RAML08' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-definition-system\dist' ERROR in ./node_modules/raml-definition-system/dist/index.js Module not found: Error: Can't resolve './RAML10' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-definition-system\dist' ERROR in ./node_modules/oas-raml-converter/lib/helpers/ramlErrorModel.js Module not found: Error: Can't resolve 'fs' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\oas-raml-converter\lib\helpers' ERROR in ./node_modules/oas-raml-converter/lib/raml/ramlConverter.js Module not found: Error: Can't resolve 'fs' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\oas-raml-converter\lib\raml' ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js Module not found: Error: Can't resolve 'http' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\json-schema-ref-parser\lib\resolvers' ERROR in ./node_modules/json-schema-ref-parser/lib/resolvers/http.js Module not found: Error: Can't resolve 'https' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\json-schema-ref-parser\lib\resolvers' ERROR in ./node_modules/oas-raml-converter/lib/helpers/ramlErrorModel.js Module not found: Error: Can't resolve 'os' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\oas-raml-converter\lib\helpers' ERROR in ./node_modules/oas-raml-converter/lib/raml/ramlConverter.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\oas-raml-converter\lib\raml' ERROR in ./node_modules/raml-1-parser/dist/schema.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist' ERROR in ./node_modules/raml-1-parser/dist/parser/apiLoader.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser' ERROR in ./node_modules/raml-1-parser/dist/parser/highLevelImpl.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser' ERROR in ./node_modules/raml-1-parser/dist/parser/lowLevelAST.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/linter.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/ast.core/namespaceResolver.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\ast.core' ERROR in ./node_modules/raml-1-parser/dist/parser/jsyaml/jsyaml2lowLevel.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\jsyaml' ERROR in ./node_modules/raml-1-parser/dist/parser/wrapped-ast/wrapperHelper.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\wrapped-ast' ERROR in ./node_modules/raml-1-parser/dist/parser/wrapped-ast/wrapperHelper08.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\parser\wrapped-ast' ERROR in ./node_modules/raml-1-parser/dist/util/jsonSerializerHL.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\util' ERROR in ./node_modules/raml-1-parser/dist/util/jsonSerializer.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\util' ERROR in ./node_modules/raml-1-parser/dist/util/contentprovider.js Module not found: Error: Can't resolve 'path' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\raml-1-parser\dist\util' ERROR in ./node_modules/oas-raml-converter/lib/utils/url.js Module not found: Error: Can't resolve 'request' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\oas-raml-converter\lib\utils' ERROR in ./node_modules/xml2js/lib/parser.js Module not found: Error: Can't resolve 'timers' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\xml2js\lib' ERROR in ./node_modules/loophole/lib/loophole.js Module not found: Error: Can't resolve 'vm' in 'C:\develop\api-governance-tool\GovernanceAPIDashboard\node_modules\loophole\lib'

**Comment by postatum** [comment]
Hi @n333ck

Can you please attach a very simple project to demo this issue? Just a package.json, js file and something else to make it fail.

**Comment by postatum** [comment]
Closing for now as no answers. Feel free to provide more information and re-open if this is still relevant
