### ISSUE TITLE
How to change "__$EscapedKey$__" prefix?

### ISSUE THREAD

**Issue by baig** [raml-org/raml-js-parser-2#9]

**Comment by sichvoge** [comment]
Is this related to https://github.com/raml-org/raml-js-parser-2/issues/5?

**Comment by KonstantinSviridov** [comment]
Prefixes are no longer inserted by default.

Initially, they were introduced as a walkaround for such bugs:
https://bugs.openjdk.java.net/browse/JDK-8048718
But we decided not to use it in JS parser by default in order not to confuse people.

But if you for some reasons want it back, you may call `toJSON` as
```
RAML.toJSON(api,{escapeNumericKeys:true})
```
