### ISSUE TITLE
QueryString() in methods() Undefined

### ISSUE THREAD

**Issue by Nosthertus** [raml-org/raml-js-parser-2#90]
so basically... `resource().methods()` returns an array of all methods from a resourse.

There is an iteration for each element in the array so each method can be processed.. but when i try to get `queryString()`.. it throws an error `queryString is not a function`

the code i tried is basically like this

```Javascript
function getMethods(resource){
	var methods = {};

	var m = resouce.methods();

	for(i in m){
		var method = m[i],
			name = method.method();

		methods[name] = {
			// Get the current queryString from this method
			queryString: getQueryString(method.queryString())
		};
	}

	return methods;
}
```

**Comment by ddenisenko** [comment]
The snipped you provided works just fine for me if I correct the typo and remove `getQueryString` call. Can you provide the RAML, it does not work with?

**Comment by petrochenko-pavel-a** [comment]
Works fine for me to. So closing the issue for now.  

P.S. Just as an idea. It might be that you are actually parsing RAML 0.8 API. In this case method objects will not have `queryString()`  method because there is no such property in RAML 0.8

Regards,
Pavel
