### ISSUE TITLE
Unclear error messages

### ISSUE THREAD

**Issue by dirkaholic** [raml-org/raml-js-parser-2#92]
Hi,

I'm using this code snippet from one of the test examples to verify my RAML 1.0 specification:

```
var api = raml1Parser.loadApiSync(path.resolve(__dirname, "../raml-specs/scores-api.raml"));

api.errors().forEach(function(x){
    console.log(JSON.stringify({
        code: x.code,
        message: x.message,
        path: x.path,
        start: x.start,
        end: x.end,
        isWarning: x.isWarning
    },null,2));
});
```

Now I'm getting an output like this:

```
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
{
  "code": 7,
  "message": "string is expected",
  "path": "scores-api.raml",
  "start": 1021,
  "end": 1028,
  "isWarning": true
}
```

The path of the raml file is correct and it is actually 35 lines long but uses a library and includes an example. From the message above I have no idea where to look for a problem. What do these numbers actually mean ? Would it be possible to print the name of the affected property with the error message ?

Hint: Loading the related files in the atom editor does not show any problem.

**Comment by dirkaholic** [comment]
Any comments / updates ?

**Comment by ddenisenko** [comment]
@dirkaholic we migrated to the new type system, which replaces validation of such errors. 
If you provide the RAML I can check how the new validation treats it. Alternatively, you can either check it yourself in the `code` branch of this repository, or wait until it is applied to master and released as NPM and zip archive, which should happen quite soon.

**Comment by dirkaholic** [comment]
Thanks, will have a look on that.

**Comment by sichvoge** [comment]
Is this still open?

**Comment by ddenisenko** [comment]
This one is implemented.
