### ISSUE TITLE
Parser shouldn't swallow original errors, but propagate those, when !include cannot be resolved

### ISSUE THREAD

**Issue by xaka** [raml-org/raml-js-parser-2#93]
test.js:

```
'use strict';

var fs       = require('fs');
var bluebird = require('bluebird');
var parser   = require('./raml-1-parser//generated/src/raml1Parser.js');

parser.loadApi('api.raml', {
  attributeDefaults: true,
  rejectOnErrors:    true,
  fsResolver:        {
    contentAsync: contentAsyncFn
  }
})
  .catch(function (error) {
    console.error(error);
  })
;

function contentAsyncFn(path) {
  return bluebird.resolve()
    .then(function () {
      return fs.readFileSync(path, 'utf8');
    })
    .catch(function (error) {
      console.log(error);
      throw error;
    })
  ;
}
```

api.raml:

```
#%RAML 0.8

title: API repository
baseUri: http://google.com
mediaType: application/json
traits: !include /traits.raml
```

traits.raml:

```
<does not exist>
```

error:

```
{ [Error: Api contains errors.]
  parserErrors:
   [ { code: 6,
       message: 'Can not resolve /traits.raml due to: this.resolver.content is not a function',
       path: 'api.raml',
       start: 124,
       end: 130,
       line: 5,
       column: 0,
       range: [Object],
       isWarning: false } ] }
```

original error:

```
{ [Error: ENOENT: no such file or directory, open '/traits.raml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/traits.raml' }
```

As we can see, thrown error `Can not resolve /traits.raml due to: this.resolver.content is not a function` doesn't make much sense nor it contains any clue about original error, which is `ENOENT: no such file or directory, open '/traits.raml'`.

**Comment by KonstantinSviridov** [comment]
You have not implemented one of the required methods of the FSResolver interface. After you have implemented `content` method, you'll be obtaining something like
```
{ [Error: ENOENT, no such file or directory 'C:\traits.raml']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\traits.raml',
  syscall: 'open' }
```

**Comment by xaka** [comment]
Why do I need to implement `content` and what kind of implementation is expected? I already have `contentAsync` implemented.

**Comment by KonstantinSviridov** [comment]
If a file have not been load asynchronously, the parser falls back to synchronous loading in the moment when the file is requested.

In the case when API is loaded asynchrounously the fact of `content` being called means that the parser has already failed to load it asynchronously, so in `content` method you may throw an error. Alternatively, you may check file existence and try loading it synchronously, but it will not help if asynchronous loading is implemented correctly.
