### ISSUE TITLE
xmldom-alpha is no longer maintained

### ISSUE THREAD

**Issue by karfau** [raml-org/raml-js-parser-2#943]
Hello, I just wanted to let you know that the package xmldom (which is from the same code base as `xmldom-alpha` this is being used in [`package.json`](https://github.com/raml-org/raml-js-parser-2/blob/master/package.json#L50)) was not maintained for a while and that's why a new github organization took over maintainance under https://github.com/xmldom/xmldom .

While the new organization is publishing new versions to the `xmldom` package, there are no plans of maintaining the separate `xmldom-alpha` package.

The version you are using also contains [a bug/regression](https://github.com/xmldom/xmldom/issues/57) that has been fixed and will soon be published as part of the [v0.4.0](https://github.com/xmldom/xmldom/milestone/1) of the xmldom package.

I'm informing you about this, since this package is one of the last remaining dependents of [`xmldom-alpha`](https://www.npmjs.com/package/xmldom-alpha/v/0.1.28?activeTab=dependents).

**Comment by eduardo-rubio** [comment]
Hi @karfau, This repo is deprecated as you can see here https://github.com/raml-org/raml-js-parser-2/blob/master/README.md.
So, There is no plan to do any change to this project.
Thanks for your heads up.

Regards, Edu.
