### ISSUE TITLE
Expose internal parser

### ISSUE THREAD

**Issue by hulkish** [raml-org/raml-js-parser-2#96]
I'd like to write something like this: https://github.com/opensourcecu/raml-loader/blob/master/index.js

Currently, from what I can see with the `raml-1-parser` - There isn't much exposed that will allow me to do so. I only see the ability to load the file (ex `loadApi`, `loadApiSync`, etc). What if I just want the string parsed? Please point me in the right direction

**Comment by sichvoge** [comment]
What do you mean by only the string?

**Comment by hulkish** [comment]
A string of RAML! 

Yout `raml-1-parser` assumes that I want to load a `. raml` file.  What  if i already have it loaded and juat want to parse the raml into json?

**Comment by sichvoge** [comment]
If you just want to serialize your RAML into JSON, did you try to call `.toJSON`?

**Comment by hulkish** [comment]
how do you recommand that I access that function? Currently, I only see this exposed for the `raml-1-parser1` itself:

```json
{ loadApiSync: [Function: loadApiSync],
  loadApi: [Function: loadApi],
  loadRAMLSync: [Function: loadRAMLSync],
  loadRAML: [Function: loadRAML],
  getLanguageElementByRuntimeType: [Function: getLanguageElementByRuntimeType] }
```

**Comment by sichvoge** [comment]
This is what I have done using the parser inside the raml2html/raml2obj project:

```js
raml.loadApi(source, { rejectOnErrors: true }).then(function(raml) {
   return raml.expand().toJSON();
});
```

You can also execute:

```js
var api = raml1Parser.loadApi(path.resolve(__dirname, "test2.raml"), {rejectOnErrors: true, attributeDefaults: true})

api.then(function (result) {
    var jsonObj = result.expand().toJSON();
}).catch(function(error) {

})
```

Let me know if that helps.

**Comment by hulkish** [comment]
I've tried your first example, but I just get an error in my catch handler:

```bash
{ [Error: ENAMETOOLONG: name too long, open '/Users/myusr/dev/myproject/#%RAML 0.8
title: my api
version: v1
baseUri: http://mydomain.com/api/{version}
mediaType:  application/json
```



Per my situation - I have no need to actually *load* the file - it's already loaded. In effort of clarity, here's an example use case I'd like to be able to perform:

```js
// (es6)

import raml from 'raml-1-parser';

let myRAML = `
#%RAML 0.8
title: my api
version: v1
baseUri: http://mydomain.com/api/{version}
mediaType:  application/json
/hello-world:
  get:
    description: hello world
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/hello-world.json
            example: !include examples/hello-world.json`;

raml.loadApi(myRAML, { rejectOnErrors: true })
    .then((result) => {
        console.log('result', result.expand().toJSON());
    })
    .catch((err) => {
        console.log(err);
    });
```

Hope that makes more sense.

**Comment by ddenisenko** [comment]
You can use the dedicated mechanism for providing the content of RAML, which is described in documentation: fsResolver or httpResolver.

Here is a quick simple example of substituting "api.raml" file with a custom string using fsResolver:

```
RAML.Parser.loadApi('api.raml', {
		rejectOnErrors: true,
		fsResolver: {
			contentAsync: function (path) {
				if (path === '/api.raml') {
					return new Promise(function (resolve, reject) {
						resolve("#%RAML 1.0\ntitle: test");
					});
				}
			}
		}
	})
```

**Comment by ddenisenko** [comment]
And, internal parser is exposed.

**Comment by hulkish** [comment]
I guess I'm a little confused - if I'm using the solution you've described (`fsResolver`) Does the `loadApi('./api.raml` actually load the file? Seems unnecessary, since I've already described that I have the contents of the file already loaded.

**Comment by ddenisenko** [comment]
`fsResolver` is a mechanism, the parser uses to obtain RAML file contents. When you specify your own fsResolver, parser obtains 'api.raml' contents by calling `fsResolver.content()` or `fsResolver.contentAsync()` depending on whether you call `loadApi` or `loadApiSync`.

So, if you have the contents of your file loaded in unusual way, you just feed it to the parser by specifying a custom fsResolver, which knows where your content is actually stored.

**Comment by petrochenko-pavel-a** [comment]
For a convenience methods to parse RAML from text added to api (`parseRAMLSync`, `parseRAML`), 
please note that you still have to pass resolvers inside options if you need includes to be resolved.

pushed to RC2,
Regards,
Pavel
