### ISSUE TITLE
Problem defining type as string

### ISSUE THREAD

**Issue by juancoen** [raml-org/raml-js-parser-2#97]
This seems to be allowed in RAML 1:
```
#%RAML 1.0
title: Hello world # required title

/helloworld: # optional resource
  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            type: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: # example how a response looks like
              {
                "message": "Hello world"
              }
```

When obtaining the type from the JSON TCK output, the property type contains:
```
"{ "title": "Hello world Response", "type": "object", "properties": { "message": { "type": "string" } } }"
```

Which seems to be wrong, as that JSON string has semantics that the parser should understand, returning the information that the parser client needs (the actual type and its properties). Otherwise, all parser clients need to parse that JSON string and interpret the meaning of it.

This raises another concern. Why is this allowed in the first place? Wouldn't it be better to be prescriptive about type definitions, only accepting YAML type definitions, so we can simplify the parsing and the tools?

Thanks!

**Comment by sichvoge** [comment]
I can answer your second question @juancoen 

> Why is this allowed in the first place? Wouldn't it be better to be prescriptive about type definitions, only accepting YAML type definitions, so we can simplify the parsing and the tools?

Using `type` or `schema` is fully synonymous according to the specification. Right now, `schema` is deprecated but still available for backwards compatibility to RAML 0.8, but we might decide to remove it in a future version of RAML.

**Comment by juancoen** [comment]
@sichvoge In my opinion, making type and schema synonymous is a mistake. `schema` should retain its meaning from RAML 0.8, and should only be used for JSON or XML Schemas. `type` should only be used to reference or define a type, as defined in the RAML 1.0 Type System. This keeps things backward compatible while making the transition from `schema`to `type` easier both for the parsers and for the parsers' clients.

In my first point, I had come to the conclusion that a JSON string inside a type was a way to define a RAML 1.0 type using JSON strings, I didn't realize it was JSON Schema.

Thanks!

**Comment by sichvoge** [comment]
So can that be closed?
