### ISSUE TITLE
Cleanup published package

### ISSUE THREAD

**Issue by SimonSchick** [raml-org/raml-js-parser-2#99]
Might be opinonated, but right now you are shipping *all* files when the project gets published, making the install pretty bloated.

When publishing you can omit the /src /typings /test /examples /documentation and probably a few others, just create `.npmignore` file.

**Comment by sichvoge** [comment]
Yes, some cleanup is necessary I agree. Although there is a `.npmignore` file already and it includes the src files. 

The parser should follow some suggestions [here](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). For example, there is no need to explicitly add `/node_modules` and also `npm-debug.log`.

We could probably ignore:

* /src
* /typings
* /test
* /examples
* /documentation
* /web-tools

@ddenisenko does that sound good to you?

**Comment by SimonSchick** [comment]
You can also ditch `custom_typings` `.travis.yml` `RAML Parser.png` `gulpfile.js` `tsconfig.json` `typings.json` and `workspace.json`.

And all files that might be generated during build (except dist ofc).

**Comment by ddenisenko** [comment]
There is .npmignore.

* /custom_typings - this one is required for TS users.
* /dist - required for the module to work
* /documentation - not everyone is using web version. Many modules package documentaiton. Debatable, but I vote for leaving it as is.
* /examples - a single simple example demonstrating how to use the module in a web page. Should not be removed.
* /src - yes, this one should be removed. Actually, it is published by mistake.
* /test - several simple tests, a quick way to check that the parser works and see a couple of usage approaches. Should not be removed.
* /typings - required for TS users.
* /web-tools - required for standalone version generation. Should not be removed.
* gulpfile.js - should be removed.
* tsconfig.json - may be removed.
* typings.json - may be removed.
* workspace.json - should remain in the package, required to install dev. environment if needed.
* readme.md - should remain in the package.
* license.txt - should remain in the package.
* RAML Parser.png - was used in readme.md a day ago, not can be removed.
* .travis.yml - can be removed.

All in all, following to be removed right now:
* /src
* gulpfile.js
* tsconfig.json
* typings.json
* RAML Parser.png
* .travis.yml 

Following debatable:
* /documentation

**Comment by ddenisenko** [comment]
>The parser should follow some suggestions here. For example, there is no need to explicitly add /node_modules and also npm-debug.log.

I know node_modules and npm-debug.log do not need to be added to .npmignore. Though those ones were added on purpose to be able to compare .npmignore with .gitignore and quickly see the meaningfull difference. .gitignore requires those 2 to be added.

**Comment by ddenisenko** [comment]
That was implemented.
